### ISSUE TITLE
Documentation should be tagged

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb-web#1005]
When releasing new versions, we should also add a tag to the documentation.

**Comment by Mause** [comment]
If you mean a git tag, I'm not sure what purpose that would serve? We already do the archiving step after all

**Comment by szarnyasg** [comment]
I guess the main advantage of this would be that a tag for version X it allows travelling back to old infrastructure code (generation script, CI, etc.) that was known to work for DuckDB version X.
