### ISSUE TITLE
IS DISTINCT FROM and IS NOT DISTINCT FROM descriptions are swapped

### ISSUE THREAD

**Issue by zenazn** [duckdb/duckdb-web#1063]
On https://duckdb.org/docs/sql/expressions/comparison_operators.html#comparison-operators

- IS DISTINCT FROM means "<>" or "not equal"
- IS NOT DISTINCT FROM means "=" or "equal"

i.e., they're exactly swapped

**Comment by szarnyasg** [comment]
Thanks. Fix is on its way.
