### ISSUE TITLE
add compile document

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb-web#109]
please add a detailed compile guide for so/dll file and program that calling the functions in so file.

something like this https://sqlite.org/howtocompile.html

**Comment by Mause** [comment]
We have something like this over the other repo: https://github.com/duckdb/duckdb/blob/master/CONTRIBUTING.md#building

Could definitely be expanded upon though

**Comment by Alex-Monahan** [comment]
Yeah, I spent a decent number of hours trying to build the Python client on Windows (I think using a conda environment was not working). I think Windows is the missing piece to document.

**Comment by Mause** [comment]
> Yeah, I spent a decent number of hours trying to build the Python client on Windows (I think using a conda environment was not working). I think Windows is the missing piece to document.

Yeah I ended up giving up building duckdb on Windows, and switched to developing on my Linux machine or in a VM. Comprehensive instructions, especially in CLion, would be amazing
