### ISSUE TITLE
How to denote parameter assignments and default parameters

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb-web#1109]
How should we denote parameter assingments and default parameters? The code currently uses a mix of `=` and `:=`.

Option 1: `paramname = value`, e.g.:

https://github.com/duckdb/duckdb-web/blob/ad30da5953d6d8d8b3fb9f041efadf37e9836b3a/docs/data/multiple_files/overview.md#L22

Option 2: `paramname := value`, e.g.:

https://github.com/duckdb/duckdb-web/blob/ad30da5953d6d8d8b3fb9f041efadf37e9836b3a/docs/sql/query_syntax/unnest.md#L14

I stumbled upon this truly critical problem when working on the (also showstopper-level) PR #1108.

**Comment by szarnyasg** [comment]
This is not a documentation issue

**Comment by Tishj** [comment]
Yea you've probably found the answer already, but `x := 42` is a way to add an `alias` to an expression.
The `union_by_name=True` found in function calls are literally CompareEqual expressions, we just treat them differently in this context
