### ISSUE TITLE
Missing functions from docs

### ISSUE THREAD

**Issue by Mause** [duckdb/duckdb-web#1135]
Some of these are for binding developers only, but still worth mentioning somewhere I think: 

 * [x] add
 * [x] subtract
 * [x] multiply
 * [x] divide
 * [x] fdiv
 * [x] fmod
 * [x] import_database
 * [x] show_databases
 * [x] #1145
 * [x] array_intersect
 * [x] constant_or_null
 * [x] count_if
 * [x] #1144
 * [x] date_add
 * [x] https://github.com/duckdb/duckdb-web/pull/1176
 * [x] enable_profile
 * [x] disable_profile
 * [ ] all_profiling_output
 * [ ] pragma_detailed_profiling_output
 * [ ] pragma_last_profiling_output
 * [x] ilike_escape
 * [x] not_ilike_escape
 * [x] repeat_row
 * [x] #1177
 * [x] #1178

Some of these are aliases for functions that are documented, but they should still be recorded somewhere

**Comment by maiadegraaf** [comment]
`array_intersect` has also been added back #1150 😉

**Comment by szarnyasg** [comment]
@Mause thanks for collecting these, it was super helpful!

**Comment by Mause** [comment]
> @Mause thanks for collecting these, it was super helpful!

This list was generated by the Check Docs job - latest run is https://github.com/duckdb/duckdb-web/actions/runs/6992021674
