### ISSUE TITLE
Missing documentation on Node.js options to Database

### ISSUE THREAD

**Issue by paulrutter** [duckdb/duckdb-web#1136]
See https://duckdb.org/docs/api/nodejs/reference#module_duckdb..Database

The constructor is described as follows: `new Database(path, access_mode, config, callback)`.
The first argument is documented on https://duckdb.org/docs/api/nodejs/overview.

```
var db = new duckdb.Database(':memory:');
```

But what values can be passed to the second and third argument?
I would expect the second to be `READ_WRITE` or `READ_ONLY`, although the third is a bit more ambiguous.

Would it be something like this?

```
{
  "threads": "8",
  "max_memory": "2GB"
}
```
Can all options as described in https://duckdb.org/docs/sql/configuration#configuration-reference be passed here?
It would be good to extend the documentation on what the possible arguments to the `Database` constructor are in Node.js.

If anyone can confirm my assumptions, i could give it a shot in a PR.

**Comment by Mause** [comment]
You are correct yes, the config object that is passed to the Database object is the database config - the source of truth for that documentation is here https://github.com/duckdb/duckdb/blob/ba71015ee711d95fe13886f372824143cae7493c/tools/nodejs/lib/duckdb.js#L51 and https://github.com/duckdb/duckdb/blob/ba71015ee711d95fe13886f372824143cae7493c/tools/nodejs/lib/duckdb.d.ts#L131

**Comment by paulrutter** [comment]
Thanks @Mause, i will try it out and try to cone up with a PR with updated documentation.
It seems that the JSDoc is not correct, as it states 4 arguments, where the TypeScript file states there are three (the second one takes either a String or a config object).

**Comment by Mause** [comment]
> Thanks @Mause, i will try it out and try to come up with a PR with updated documentation.
> It seems that the JSDoc is not correct, as it states 4 arguments, where the TypeScript file states there are three (the second one takes either a number or a config object). 

Yeah there are multiple overloads, which is a bit hard to express with jsdoc

**Comment by paulrutter** [comment]
JSDoc also supports multiple types, with the pipe separator.

```
@param {(string|string[])} 
```

But we can also start with improving the documentation, then a separate PR for the JSDoc.

**Comment by paulrutter** [comment]
@Mause see the referenced PR for additional documentation.

**Comment by paulrutter** [comment]
Closing issue, as pr is merged.
