### ISSUE TITLE
Benchmark logs are empty

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb-web#114]
In the [Benchmarks page](https://duckdb.org/benchmarks/), the stdout logs are empty.

The link in the [Profiling page](https://duckdb.org/docs/dev/profiling#run-time-profiling) is broken, it points to:
* https://duckdb.org/benchmarks/logs/e7eb7154848be520159d9e1ee744989b25d4c987-graph.html?name=Q20

**Comment by Mytherin** [comment]
See #78. In general we need to replace these benchmark pages, or maybe just remove them entirely for now.

**Comment by szarnyasg** [comment]
Thanks, this is indeed a duplicate.
