### ISSUE TITLE
installation page development R instructions just loads CRAN version instead of latest/github repo?

### ISSUE THREAD

**Issue by ajdamico** [duckdb/duckdb-web#1143]
hi, on the https://duckdb.org/docs/installation/ page

	version: "github main (bleeding edge)" 
	environment: R

shows

	install.packages('duckdb', repos=c('https://duckdb.r-universe.dev', 'https://cloud.r-project.org'))

but this just installs the cran version for me -- maybe since https://duckdb.r-universe.dev/ says "No universe found for user: duckdb" ?

not sure if something needs to change on r-universe.dev or if this line should be modified to be this instead?

	remotes::install_github("duckdb/duckdb-r")

here's what happens in my console:

	> install.packages('duckdb', repos=c('https://duckdb.r-universe.dev', 'https://cloud.r-project.org'))
	Installing package into ‘C:/Users/AnthonyD/AppData/Local/R/win-library/4.3’
	(as ‘lib’ is unspecified)
	trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.3/duckdb_0.8.1-3.zip'
	Content type 'application/zip' length 8332033 bytes (7.9 MB)
	downloaded 7.9 MB

thanks!

**Comment by hannes** [comment]
Yes, we moved the repo, we should update the instructions.

**Comment by eitsupi** [comment]
I thinks this has been resolved.
