### ISSUE TITLE
Attach docs should reference `search_path` setting

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb-web#1160]
https://github.com/duckdb/duckdb-web/blob/c253b025f868e0926eef9be3526ec41fadcf6b1b/docs/sql/statements/attach.md?plain=1#L57C119-L57C119

This mentions the `catalog search path` but I think that's a little too vague still
It could use an example using either `set schema` or `set search_path` directly to drive this point home.

An example of using `search_path` would be:
```sql
D attach ':memory:' as db1;
D attach ':memory:' as db2;
D create table db1.tbl1 (i integer);
D create table db2.tbl2 (j integer);
D set search_path='db1,db2';
D select * from tbl1;
┌────────┐
│   i    │
│ int32  │
├────────┤
│ 0 rows │
└────────┘
D select * from tbl2;
┌────────┐
│   j    │
│ int32  │
├────────┤
│ 0 rows │
└────────┘
```

Both of these SELECT queries would fail if search_path was not set, because `tbl1` and `tbl2` would need to be qualified explicitly

**Comment by szarnyasg** [comment]
Great suggestion, I worked this into a PR.
