### ISSUE TITLE
v0.9.0 release

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb-web#1190]
Some tasks to perform after the v0.9.0 release.
* [x] Create a v0.9.0 stable PDF.
* [x] Update the CLI output. It currently shows `v0.3.4 662041e2b` in its prompt in `docs/api/cli.md`.
* [x] Remove "This extension currently only works on the main branch of DuckDB." from the iceberg extension
* [x] Add AWS extension page.
* [x] Add Azure extension page.

**Comment by Mause** [comment]
Ideally as part of preparing the release blog post, we'd also document the new features too

**Comment by szarnyasg** [comment]
Ideally, yes, but the documentation can lag a bit behind the release.
In any case, the change log is here: https://github.com/duckdb/duckdb/releases/tag/untagged-90162147651b5bdcce5c

**Comment by Mause** [comment]
> Ideally, yes, but the documentation can lag a bit behind the release.
> In any case, the change log is here: https://github.com/duckdb/duckdb/releases/tag/untagged-90162147651b5bdcce5c

This link 404's?

**Comment by szarnyasg** [comment]
Works for me when logged in.
