### ISSUE TITLE
Line spacing of menu items it too large

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb-web#1207]
The line spacing of menu items is identical to the spacing between subsequent list items.

<img width="253" alt="Screenshot 2023-09-22 at 11 42 20" src="https://github.com/duckdb/duckdb-web/assets/1402801/2fba4b96-68aa-4060-b8f0-79f5809b33e1">

**Comment by jonathanauch** [comment]
https://github.com/duckdb/duckdb-web/pull/1208

**Comment by jonathanauch** [comment]
<img width="247" alt="Bildschirmfoto 2023-09-22 um 12 26 07" src="https://github.com/duckdb/duckdb-web/assets/63743580/e4b85017-b2d9-4528-9f77-f9a8dda2ce53">
