### ISSUE TITLE
Merge commits fail on Link Checker

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb-web#1220]
Merge commits – when Link Checker is actually run – fail. However, there are no errors in the output of their GH Actions jobs, see e.g. https://github.com/duckdb/duckdb-web/actions/runs/6275492858

<img width="1512" alt="Screenshot 2023-09-22 at 16 59 06" src="https://github.com/duckdb/duckdb-web/assets/1402801/52027dad-0ace-47a5-b9e1-0525ee89324d">

**Comment by szarnyasg** [comment]
The problem seems to have started here:
https://github.com/duckdb/duckdb-web/commits/main?after=0a9e28c5dd2ddc4c19f432e60364e475d0754599+174&branch=main&qualified_name=refs%2Fheads%2Fmain
<img width="1389" alt="Screenshot 2023-09-22 at 17 03 29" src="https://github.com/duckdb/duckdb-web/assets/1402801/ef325697-7cc3-454c-a717-6bc6690eb7f8">

**Comment by szarnyasg** [comment]
E.g. this commit is failing with 0 errors: https://github.com/duckdb/duckdb-web/actions/runs/6247428511

**Comment by szarnyasg** [comment]
I ran it locally and it return successfully with a 0 error code.

**Comment by szarnyasg** [comment]
```bash
$ linkchecker https://duckdb.org/ --ignore-url 'https://duckdb\.org/.*' --config .github/linkchecker/linkchecker.conf --file-output html/utf-8/report.html --verbose
10 threads active,     1 link queued,   37 links in  48 URLs checked, runtime 1 seconds

$ echo $?
1
```

**Comment by szarnyasg** [comment]
https://github.com/linkchecker/linkchecker/issues/762

**Comment by Mause** [comment]
Is it just failing due to the warnings?

**Comment by szarnyasg** [comment]
Seems like it – [LinkChecker introduced this change in 10.3.0](https://github.com/linkchecker/linkchecker/releases/tag/v10.3.0):
> HTTP redirect causes a warning, http-redirected

I submitted a fix in #1230

**Comment by szarnyasg** [comment]
I think we should limit the LinkChecker job to
- the latest release
- blog posts
Currently, it takes a lot of time and fails very frequently (now almost always with a false positive).
WDYT?

**Comment by szarnyasg** [comment]
Link Checker's green now in the CI!
