### ISSUE TITLE
error(...) function not documented

### ISSUE THREAD

**Issue by zenazn** [duckdb/duckdb-web#1224]
I recently found out about the very useful `error(...)` function, but wasn't able to find documentation about it on the website. Is this something that's worth adding?

**Comment by szarnyasg** [comment]
Good point. It is in our [`functions.json` file](https://github.com/szarnyasg/duckdb-web/blob/0a9e28c5dd2ddc4c19f432e60364e475d0754599/docs/functions.json#L857-L867) but not yet in the list of our [utility functions](https://duckdb.org/docs/sql/functions/utility.html) (where it would belong). Let me look into it.
