### ISSUE TITLE
Using DuckDB in DataGrip setup guide

### ISSUE THREAD

**Issue by cdfuller** [duckdb/duckdb-web#1225]
Hi folks! I'm interested in writing a guide for setting up DataGrip to use DuckDB. Is this the proper place to do so, and if so, would that be a welcome contribution?

**Comment by l1t1** [comment]
thanks

**Comment by szarnyasg** [comment]
@cdfuller thanks for the suggestion, I'll discuss this internally at DuckDB Labs tomorrow.

@l1t1 please avoid engaging with contributors as if you were representing DuckDB. Thanks.

**Comment by szarnyasg** [comment]
Hi @cdfuller, I discussed this internally. A DataGrip contribution would be very welcome as a PR! Please consult our [contributor guide](https://github.com/duckdb/duckdb-web/blob/main/CONTRIBUTING.md) when preparing the PR. Thanks!

**Comment by szarnyasg** [comment]
@cdfuller as mentioned earlier, we would be happy to review a PR on Data Grip. Feel free to open one when it's ready.
