### ISSUE TITLE
Repository size is very large

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb-web#123]
@Alex-Monahan Currently, the size of this repository is massive, approx. 1.2 GB. Even when cloning just the last commit, the resulting directory is 81 MB:

```
$ git clone --depth 1 git@github.com:duckdb/duckdb-web.git
$ du -hd0 duckdb-web
81M	duckdb-web
```

Here's a list of the [top 50k largest files committed](https://gist.github.com/szarnyasg/1739b1d246b27ad2d29eb9ae9d5630d2), generated with [this script](https://stackoverflow.com/a/42544963/3580502).

To nuke old commits, the [BFG repository cleaner](https://rtyley.github.io/bfg-repo-cleaner/) can be used. This will still require a force push and thus break the commit tree but there are not too many forks of this repository yet.

**Comment by Mytherin** [comment]
Yes, this was from a time when we used to have a script that auto-committed benchmark results to this repository. They definitely should be cleaned up as this history is unnecessarily clogging the repo.

**Comment by corneliusroemer** [comment]
+1

Just came here to open this issue. I wanted to help a bit with documentation but cloning a 1.2GB repo for a casual PR is a hindrance. Thanks for the depth 1 workaround.

**Comment by Mytherin** [comment]
I have cleaned up the repo now, it's now down to 75MB. I ended up running the following deletion commands:

```
bfg --delete-files minibenchmarks.db
bfg --delete-folders benchmark_logs
bfg --delete-folders benchmark_results
bfg --delete-folders individual_results
bfg --delete-files "*-stdout.html"
bfg --delete-files "*-stderr.html"
bfg --delete-files "*-graph.html"
bfg --delete-files "*-results.csv"
bfg --delete-folders benchmarking
bfg --delete-files benchmark-info.json
bfg --delete-folders coverage
bfg --delete-folders graphs
```
