### ISSUE TITLE
Add anchors to "Why DuckDB" page

### ISSUE THREAD

**Issue by carlopi** [duckdb/duckdb-web#1233]
Currently it's not possible to link to a specific bullet point in https://duckdb.org/why_duckdb (or at least, not in easy way).

It would be of minor utility to have 'anchors' (or however they are called) like here: https://duckdb.org/docs/api/java#basic-api-usage, and have that clicking on a bullet point changes URL to the anchor.

**Comment by szarnyasg** [comment]
This was implemented, there are anchors now such as https://duckdb.org/why_duckdb#fast-analytical-queries
