### ISSUE TITLE
Add Extensions to "Why DuckDB" page

### ISSUE THREAD

**Issue by carlopi** [duckdb/duckdb-web#1234]
I think extensions are one of the more powerful feature of DuckDB, and likely the most powerful feature not featured in any way in the "why duckdb" page.

To add this incrementally, probably in the "Feature-Rich" section, or potentially even in a separate bullet point around extensions, happy to help draft / review it if it seems like a good idea.

**Comment by szarnyasg** [comment]
This now has its own section: https://duckdb.org/why_duckdb#extensible
