### ISSUE TITLE
Don't run deployment workflows on forks

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb-web#1241]
In particular, not on branches?

Example: <https://github.com/krlmlr/duckdb-web/actions/runs/6290378241>.

**Comment by Mause** [comment]
This is intentional, we run the build for the website to make sure it isn't broken. The actual deploy step doesn't run.

Though we can rename the job, which would stop people being confused by this

**Comment by krlmlr** [comment]
Do we need the "Setup Pages" step for forks? This has failed for me.

**Comment by Mause** [comment]
We can probably have it not run on forks yeah
