### ISSUE TITLE
Document CLI commands

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb-web#125]
Feedback to #117

The DuckDB CLI has quite a few features (e.g. `.tables`) which are not yet documented.

I started writing this earlier this year but realized it's a larger task and abandoned it. I got this far:

```
## Installation

DuckDB can be installed as a binary. Please see the [installation page](/docs/installation?environment=cli) for details.

Other than SQL commands, SQLite-like instructions can be used:

    .help

* `.tables`: Print a list of tables

## History

The command history is saved in the home directory in `.duckdb_history`.
```

**Comment by Alex-Monahan** [comment]
Please see the CLI documentation [here](https://duckdb.org/docs/api/cli) and let us know what can be improved!
