### ISSUE TITLE
Title bar of https://duckdb.org/docs/extensions/autocomplete is off

### ISSUE THREAD

**Issue by carlopi** [duckdb/duckdb-web#1253]
As per title, https://duckdb.org/docs/extensions/autocomplete looks off, unsure but looks something CSV related

**Comment by szarnyasg** [comment]
Haha, hope it's not CSV related. Something picks up AutoComplete as a keyword. Adding a single letter fixes it:

<img width="643" alt="Screenshot 2023-09-25 at 16 55 20" src="https://github.com/duckdb/duckdb-web/assets/1402801/d738a2ad-5fe8-479b-a989-4b52ff1c73b8">

Lemme fix this
