### ISSUE TITLE
Example for using wildcard in JSON Path not working

### ISSUE THREAD

**Issue by chowsanthony** [duckdb/duckdb-web#1266]
Can you please update the documentation how wildcard is supported? For example, on this page: https://duckdb.org/docs/extensions/json

Tried one of the examples posted, but to no avail:
```
D select json_extract('[{"duck":42},{"goose":43}]', ['$[*].duck', '$[*].goose',]);
Error: Invalid Input Error: JSON path error near '[*].duck'
D .version
SQLite v0.8.1 6536a77232
msvc-1935
```

**Comment by Mause** [comment]
In v0.9.0 is gives the error:

> Error: Binder Error: Cannot have wildcards in JSON path when supplying multiple paths
