### ISSUE TITLE
Interval  functions documentation

### ISSUE THREAD

**Issue by kimmolinna** [duckdb/duckdb-web#128]
[Interval functions](https://duckdb.org/docs/sql/functions/interval)

Should be like
```
to_milliseconds(integer) | Construct a millisecond interval | to_milliseconds(5) | INTERVAL 5 MILLISECOND
to_microseconds(integer) | Construct a microsecond interval | to_microseconds(5) | INTERVAL 5 MICROSECOND

```

**Comment by kimmolinna** [comment]
And there are a couple of extra apostrophes on the same page after HOUR and DAY words.

**Comment by Mytherin** [comment]
Thanks for the report! Also feel free to send a PR that fixes this :)

**Comment by kimmolinna** [comment]
I did it.
