### ISSUE TITLE
Documentation for function `dayofyear` is wrong

### ISSUE THREAD

**Issue by colinbreame** [duckdb/duckdb-web#1305]
On the page https://duckdb.org/docs/sql/functions/datepart the description and example for the function `dayofyear(date)` do not match.  It looks like it was copied from another row.

The description has:

> Numeric ISO weekday (Monday = 1, Sunday = 7)

But should have something related to the `dayofyear` function.

**Comment by szarnyasg** [comment]
@colinbreame thanks, indeed. A fix is coming.
