### ISSUE TITLE
Improve documentation on upserts (INSERT OR REPLACE)

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb-web#1342]
The current documentation is very shallow:

```sql
-- or update the table with the new values instead
INSERT OR REPLACE INTO tbl(i) VALUES(1);
```

**Comment by ila** [comment]
+1, I use this fairly often for incremental view maintenance and would love to have it clearly documented

**Comment by szarnyasg** [comment]
It'd be worth doing this in one go with #811.
