### ISSUE TITLE
Are there any plans to add time with time zone to the official documentation? 

### ISSUE THREAD

**Issue by wypb** [duckdb/duckdb-web#1365]
DuckDB  already implements the TIME_TZ type in the code([https://github.com/duckdb/duckdb/blob/main/src/include/duckdb/common/types.hpp#L212](https://www.google.com/url?q=https://github.com/duckdb/duckdb/blob/main/src/include/duckdb/common/types.hpp%23L212&sa=D&source=docs&ust=1697166304940180&usg=AOvVaw2Zk3JGQ8ny6GQnNJyO4k-J) and
[https://github.com/duckdb/duckdb/blob/main/src/include/duckdb/common/types/datetime.hpp#L89](https://www.google.com/url?q=https://github.com/duckdb/duckdb/blob/main/src/include/duckdb/common/types/datetime.hpp%23L89&sa=D&source=docs&ust=1697166304940283&usg=AOvVaw3Gw74mD-yfFcyq3XZLbn6e)), but I didn't find it in the official [documentation](https://duckdb.org/docs/sql/data_types/overview.html). Is there any plan to add it?

**Comment by szarnyasg** [comment]
Sure, we strive to have 100% coverage of types, functions, and syntax elements. So thanks for pointing this out, we'll add it.
