### ISSUE TITLE
document the `INTERVAL` data type

### ISSUE THREAD

**Issue by hamilton** [duckdb/duckdb-web#137]
Hi folks! Thank you for taking documentation seriously. Reading through the docs has helped onboard me to duckdb very quickly.

One thing I noticed: `INTERVAL` functions are documented by `INTERVAL` isn't. Could be that the function defs are enough to get started but it took me a Github issue discussion & looking at the source to understand the data type.

**Comment by Mytherin** [comment]
@Alex-Monahan this should be implemented now right?

**Comment by Alex-Monahan** [comment]
Yes! Closing this issue. Please feel free to reopen if there is more that we should add!
