### ISSUE TITLE
map_entries doc obsolete (0.9.1)

### ISSUE THREAD

**Issue by bluehat974** [duckdb/duckdb-web#1373]
Align doc with the behavior of map_entries
Check if other documented functions is obsolete

Doc says 
https://duckdb.org/docs/archive/0.9.1/sql/functions/nested
```
map_entries(map)
Return a list of struct(k, v) for each key-value pair in the map.

map_entries(map([100, 5], [42, 43]))
[{'k': 100, 'v': 42}, {'k': 5, 'v': 43}]
```

however the behavior is different on 0.9.1

`SELECT map_entries(map([100, 5], [42, 43])) as entry;`
return
```
┌──────────────────────────────────────────────────────┐
│ entry                                                │
╞══════════════════════════════════════════════════════╡
│ [{"key": 100, "value": 42}, {"key": 5, "value": 43}] │
└──────────────────────────────────────────────────────┘
```

**Comment by szarnyasg** [comment]
@bluehat974 thanks for pointing this out. There were quite a few other issues among the other functions in the nested functions page - I fixed these too.
