### ISSUE TITLE
create a node.js page in the client API section

### ISSUE THREAD

**Issue by hamilton** [duckdb/duckdb-web#138]
The node module isn't mentioned in the documentation. I totally get that it's not as much a "data friendly" language as Python and R but there is a large class of data apps that could leverage node in the future. At the minimum a link to the GH readme would suffice.

**Comment by Alex-Monahan** [comment]
Good suggestion! If it's helpful to you right now, we do have a tab on the Installation page for node.js, but we do need to add it to our Client API's!
