### ISSUE TITLE
[Prepared Statements] Add docs for the PREPARE and EXECUTE keywords

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb-web#1400]
I think this should probably be in the same list as EXPLAIN (meta/explain)

At the moment it appears as if prepared statements are only supported in the C-API if you browse the documentation.
But we support both PREPARE and EXECUTE in the core as SQL statements.

While on this subject, if you search for EXECUTE it lands you on a python documentation page, which has nothing to do with prepared statements, we should probably rename this page so it doesn't cloud this new page.

**Comment by szarnyasg** [comment]
Prepared statements are now documented as part of:
* the CLI API: https://duckdb.org/docs/api/cli#prepared-statements
* the SQL statement page: https://duckdb.org/docs/sql/query_syntax/prepared_statements
* #1678
