### ISSUE TITLE
Feature: Use `markdownlint` for consistent markdown formatting

### ISSUE THREAD

**Issue by corneliusroemer** [duckdb/duckdb-web#141]
See https://github.com/DavidAnson/markdownlint for more info

This could be enabled as a Github action for PRs

**Comment by szarnyasg** [comment]
Wow, this has been here for quite some time. Thanks for the suggestion. We'll make good use of it, including the check for header levels:
https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md001---heading-levels-should-only-increment-by-one-level-at-a-time

**Comment by techdragon** [comment]
This appears to already be in use. Commit e9bcfc2
