### ISSUE TITLE
Lack of instructions on strings with special characters

### ISSUE THREAD

**Issue by ila** [duckdb/duckdb-web#1419]
Been stuck for a hour trying to insert strings with special characters (mainly apex) in varchar fields. Example:

```sql
create table test(a varchar, b varchar);
insert into test values('a\'b', 'c');
```
hangs.

Page URL: <https://duckdb.org/docs/sql/data_types/text.html>

**Comment by Mause** [comment]
What do you mean by "apex" sorry?

If you want to escape a quote, you just double it up - which I believe is the same as most SQL dialects

**Comment by ila** [comment]
yes, that is what I was looking for - would like it to be added to the docs
