### ISSUE TITLE
Document that `SELECT` is not parallel by default but adding `ORDER BY` parallelises

### ISSUE THREAD

**Issue by corneliusroemer** [duckdb/duckdb-web#142]
I read in some Github issue that a simple `SELECT` query is not parallelized but that by adding `ORDER BY` one can workaround this limitation.

I think it'd be great if this trick was documented to help discoverability. Unfortunately I can't find the Github issue to link to, but this trick definitely works.

**Comment by Mytherin** [comment]
This is now fixed - SELECT is parallel by default as well
