### ISSUE TITLE
Glossary of terms

### ISSUE THREAD

**Issue by Mause** [duckdb/duckdb-web#1457]
Would be helpful having a glossary of terms used in the documentation that aren't easy to Google.

 * [x] [replacement scan](https://duckdb.org/docs/api/c/replacement_scans)
 * [x] platform (`os_architecture[_compiler]`)
 * [x] in-process (embeddable/embedded)
 * [x] extension

**Comment by szarnyasg** [comment]
This is currently under the FAQ but I'll move it under the main documentation.
