### ISSUE TITLE
Issue found on page 'HTTP Parquet Import'

### ISSUE THREAD

**Issue by amishsd** [duckdb/duckdb-web#1474]
_Please describe the issue on the page and include the "Page URL" link shown below._

Page URL: <https://duckdb.org/docs/guides/import/http_import.html>

select count(1) from real_parquet ('https://example/cloudfront.net/ordertest/**/*.parquet');

gives error http error : unable to connect to URL

however if i give full path then query works fine i.e.

 select count(1) from real_parquet ('https://example/cloudfront.net/ordertest/10000/10000/20231103/123.parquet');

please suggest

**Comment by szarnyasg** [comment]
Hello, `*` is not supported in HTTPS requests (neither in DuckDB, nor in general). The documentation does not suggest that it is, so this is not an issue.

**Comment by amishsd** [comment]
hello, thanks for your input

is there any other way we can fetch those queries using cloud front having (*) wildcard in path?

**Comment by szarnyasg** [comment]
No, you have to use an S3-compatible API or similar for that.
