### ISSUE TITLE
Inconsistency in documentation and duckdb with HISTOGRAM

### ISSUE THREAD

**Issue by taniabogatsch** [duckdb/duckdb-web#1489]
The [documentation](https://duckdb.org/docs/sql/aggregates) describes `HISTOGRAM ` as follows:
> Returns a LIST of STRUCTs with the fields bucket and count.

However, when I run `HISTOGRAM ` in duckdb, the return type is `MAP`.

```sql
D create table t as select range % 4 as i from range (100);
D select histogram(i) from t;
┌──────────────────────────┐
│       histogram(i)       │
│   map(bigint, ubigint)   │
├──────────────────────────┤
│ {0=25, 1=25, 2=25, 3=25} │
└──────────────────────────┘
```

This can lead to confusion, e.g., in this scenario: https://github.com/duckdb/duckdb/issues/2876.
We support `UNNEST` for `STRUCT` and `LIST`, but not for `MAP`. `Returns a LIST of STRUCTs` implies that `HISTOGRAM` should work with `UNNEST`.

**Comment by szarnyasg** [comment]
Thanks @taniabogatsch!
