### ISSUE TITLE
"copy" button does not work

### ISSUE THREAD

**Issue by ila** [duckdb/duckdb-web#1501]
Ubuntu 23.04, Firefox 119.0.1
Is it just me or the "copy" button to copy snippets of code does not do anything? I tried multiple pages and none of them work. Thanks!

**Comment by szarnyasg** [comment]
Indeed it's also broken on MacOS + Chrome. Example page:

http://duckdb.org/docs/guides/import/csv_import

@Franz-Kafka @jonathanauch could you please take a look?

**Comment by ila** [comment]
That's weird - it still does not work. I have the clipboards events enabled (other copy buttons in other websites such as GitHub itself work no problem).

**Comment by ila** [comment]
Ah no nevemind, opening a private window makes it work. Probably I am using a cached version of the website. All good :)
