### ISSUE TITLE
Issue found on page 'Excel Import'

### ISSUE THREAD

**Issue by YuriyGavrilov** [duckdb/duckdb-web#1512]
_Please describe the issue on the page and include the "Page URL" link shown below._

Page URL: <https://duckdb.org/docs/guides/import/excel_import.html>

There is a correct command to import from excel with headers. Also excel should be closed in excel. 
![image](https://github.com/duckdb/duckdb-web/assets/44679014/894f74a5-9c40-409c-8c43-04c30755f2b1)
https://github.com/duckdb/duckdb/issues/8531

OGR_XLSX_HEADERS = FORCE / DISABLE / AUTO - is not correct. Please update docs.

**Comment by szarnyasg** [comment]
@YuriyGavrilov thanks for reporting this issue. The page could indeed use some improvements, I submitted a PR to fix this issue along with reworking the page.
