### ISSUE TITLE
Create guide for metafunctions

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb-web#1550]
Idea: create a page to summarize functions which allow extracting info about the running DuckDB instance. This would include `version()`, `duckdb_extensions()`, `duckdb_functions()`, etc.

**Comment by Mause** [comment]
https://duckdb.org/docs/archive/0.9.2/sql/duckdb_table_functions ?

**Comment by szarnyasg** [comment]
This is a good start but 1) it's URL suggests it is about table functions in general; 2) it's missing `version`; 3) it's way too loo long. I think what I have in mind would be best written as a short page under `docs/guide/meta`.
