### ISSUE TITLE
How to nest query?

### ISSUE THREAD

**Issue by Asiawyz** [duckdb/duckdb-web#156]
I want to test nest query by duckdb. First I use create and insert to create a table with a map filed.
Then I want to query map data. But I didn't see some example in the documents, I trid many times, but not worked. So someone can help me ?

    import duckdb
    import time

    if __name__ == "__main__":
        con = duckdb.connect()
        start = time.time()
    
        con.execute("create table mcule(id INTEGER, map_col MAP(VARCHAR ,VARCHAR ))")    
        con.execute("insert into mcule VALUES (1,map(['asia'],['asdfa']))")

        #con.execute("select * from mcule where map(map_col)(['asia'],['asdfa']"))
       # con.execute("select element_at(map_col,['asia'])")
       # print(con.fetchall())
       # con.execute("copy (select * from mcule) to 'nesttest.csv' (FORMAT 'CSV')")
       # con.execute("select people.name from 'nesttest.parquet'")
        con.execute("select * from mcule")
        print(con.fetchall())
        end = time.time()
        print("test time: " + str(end - start))

error 

    Traceback (most recent call last):
      File "createNesTTest.py", line 12, in <module>
        con.execute("select * from mcule where map(map_col)['asia']='asdfa'")
    RuntimeError: We need exactly two lists for a map

    Traceback (most recent call last):
      File "createNesTTest.py", line 12, in <module>
        con.execute("select * from mcule where map(['asia'],['asdfa'])")
    RuntimeError: Conversion Error: Unimplemented type for cast (MAP<VARCHAR, VARCHAR> -> BOOLEAN)

**Comment by Alex-Monahan** [comment]
Hello and thanks for trying out DuckDB!

In the future, we recommend posting questions like this to our [Discord server](https://discord.gg/tcvwpjfnZx), or to the main [DuckDB repo](https://github.com/duckdb/duckdb). More people are watching those feeds so you might get a faster answer! If you have any follow up questions, please post an issue or discussion there and link to this issue.

You are very close! The key issue with the final 2 examples (the ones with errors) is that you added the `map` function when it wasn't needed. I tested out this query on the DuckDB shell, but it should work in Python!
```sql
--No need to wrap the map_col in the map function. 
--Also note that extracting from a map returns a list, 
--  so we needed to use a list on the right hand side of the equals sign
select * from mcule where map_col['asia']=['asdfa'];
```

| id |   map_col    |
|----|--------------|
| 1  | {asia=asdfa} |
