### ISSUE TITLE
Issue found on page 'SELECT Clause'

### ISSUE THREAD

**Issue by BradleyRR** [duckdb/duckdb-web#1682]
The SELECT documentation doesn't explain how to select columns that have unusual names. This page should also explain how to select columns with spaces in them and other unusual characters (ex. "Last Queue"). Thank you for your help!

Page URL: <https://duckdb.org/docs/sql/query_syntax/select.html>

**Comment by szarnyasg** [comment]
Good point, thanks! I added an example.
