### ISSUE TITLE
Update minvalue/maxvalue for CREATE SEQUENCE

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb-web#17]
Update minvalue/maxvalue once https://github.com/cwida/duckdb/issues/1056 has been resolved.

See discussion in https://github.com/cwida/duckdb-web/pull/13#issuecomment-727890152

**Comment by Mytherin** [comment]
[IsNullValue](https://github.com/duckdb/duckdb/pull/1775) has since been removed, and the [limits have been adjusted](https://github.com/duckdb/duckdb/blob/fb267c8b51862f6d08100e1953714b228630d217/src/common/limits.cpp#L11).

**Comment by szarnyasg** [comment]
Indeed, the limits in https://github.com/duckdb/duckdb-web/blob/fad377651b16eeaa29611ceda80c8a5cea57df5c/docs/sql/statements/create_sequence.md#parameters are now correct.
