### ISSUE TITLE
cli alternative: sqlline

### ISSUE THREAD

**Issue by Bartman0** [duckdb/duckdb-web#170]
just a tip: no real need to build a cli, you can reuse sqlline if required so.
I understand the integration will not be as tight as possible, but it works, and enables one to use the same cli for all kind of databases:
 
combi of DuckDB JDBC driver and sqlline
see: https://duckdb.org/docs/data/parquet, and sqlline https://github.com/julianhyde/sqlline
 
sqlline -u "jdbc:duckdb:" -d "org.duckdb.DuckDBDriver" -n '' -p '' -e "select * from 'userdata1.parquet';"

**Comment by hannes** [comment]
Maybe this can be added to the JDBC section of the documentation. Happy to review a PR.

**Comment by szarnyasg** [comment]
@Bartman0 as per our current [contributor's guide](https://github.com/duckdb/duckdb-web/blob/main/CONTRIBUTING.md#eligibility), sqlline instructions for using DuckDB should not be part of the documentation, and would be best contributed to a repository such as [`awesome-duckdb`](https://github.com/davidgasquez/awesome-duckdb/pulls). I'm happy to create a PR there but I cannot seem to get sqlline and DuckDB working, see:

```bash
$ java -cp "sqlline-1.12.0-jar-with-dependencies.jar:duckdb_jdbc-0.9.2.jar" -jar sqlline-1.12.0-jar-with-dependencies.jar -u "jdbc:duckdb:" -d "org.duckdb.DuckDBDriver" -n '' -p '' -e "select * from 'userdata1.parquet';"
```
```
scan complete in 0ms
Could not find driver org.duckdb.DuckDBDriver
No current connection
sqlline version 1.12.0
```
