### ISSUE TITLE
Proposal: Adding instructions to connect PySpark to DuckDB and read a PySpark DataFrame

### ISSUE THREAD

**Issue by erikhuck** [duckdb/duckdb-web#1712]
This took a while to figure out and there doesn't appear to be documentation that lists all the steps. Since I've figured out how to do this, I'd like to share with the community the code I had to write in order to read a DuckDB table as a PySpark DataFrame. I propose that this code sample gets added to the documentation. This is an example using the DuckDB JDBC version 0.8.1 but can be replaced by any version. The database file name in this example is `my-duckdb-database.db` and the table name in this example is 'MyTable'. Please let me know if there is interest for this and I could make a pull request.

The DuckDB `.jar` file of any version can be downloaded from [the Maven repository](https://mvnrepository.com/artifact/org.duckdb/duckdb_jdbc).

```
import pyspark.sql as psql
spark = psql.SparkSession.builder.config('spark.jars', 'path/to/duckdb_jdbc-0.8.1.jar').getOrCreate()
url = 'jdbc:duckdb:path/to/my-duckdb-database.db'
# The dataframe can be read like this:
reader = spark.read.format('jdbc').option('url', url)
df = reader.option('dbtable', 'MyTable').option('driver', 'org.duckdb.DuckDBDriver').load()
# ... or like this:
reader = psql.DataFrameReader(spark)
df = reader.jdbc(table='MyTable', url=url, properties={'driver': 'org.duckdb.DuckDBDriver'})
```

**Comment by Mause** [comment]
Surely this is better off living in the pyspark docs? There's nothing here specific to DuckDB

**Comment by erikhuck** [comment]
@Mause it uses the duckdb JDBC. And the current documentation doesn't make it clear how to connect a pyspark session to a duckdb database via JDBC.

**Comment by szarnyasg** [comment]
Hi @erikhuck thanks for opening this issue. As @Mause pointed out, this doesn't really belong to the DuckDB documentation: in general, [tools that use DuckDB](https://github.com/duckdb/duckdb-web/blob/main/CONTRIBUTING.md#eligibility) should not fit in the DuckDB documentation. Reading via the JDBC driver is also rather slow – if you have alternative options, like exporting to/importing from Parquet, consider using those.

**Comment by erikhuck** [comment]
@szarnyasg Thank you for the information. I could possibly propose this in the awesome-duckdb repo instead. But I don't understand why the JDBC would be slow? DuckDB is very fast when you load a pandas DataFrame via `con.sql()`. So why would loading a spark DataFrame via the JDBC be different?

I understand DuckDB has an export to parquet option but my table has over a million rows and over 20,000 columns (it's a machine learning dataset so it's big) and when I try to export it to parquet, it runs out of memory. Would you happen to know how to configure DuckDB to prevent running out of memory (i.e. reading a subset of the table, appending subset to parquet file, then reading the next subset of the table, etc.)? If not, it would appear I'd have to use PySpark to at least convert to parquet?

**Comment by szarnyasg** [comment]
@erikhuck 

> But I don't understand why the JDBC would be slow?

JDBC returns rows line-by-line, which adds a lot of overhead if you have many rows.

For Parquet export, did you try setting the [`preserve_insertion_order`](https://duckdb.org/docs/guides/performance/how-to-tune-workloads#the-preserve_insertion_order-option) to `false`?
```sql
SET preserve_insertion_order = false;
```

**Comment by erikhuck** [comment]
@szarnyasg would ODBC be better?

I will try setting preserve row order to false

**Comment by Mause** [comment]
ODBC would have the same problem. ADBC is your best bet

**Comment by erikhuck** [comment]
It still ran out of memory after `SET preserve_insertion_order = false;`. It appears that DuckDB is not able to export large data sets. Looks like something more heroic is necessary.

**Comment by Mause** [comment]
Depending on your exact configuration, you may need to limit the number of threads as well (DuckDB can try to be too fast sometimes)
