### ISSUE TITLE
Issue found on page 'PIVOT Statement'

### ISSUE THREAD

**Issue by DanCory** [duckdb/duckdb-web#1713]
Near the top of the page, the documentation includes the ORDER BY and LIMIT clauses in the Pivot definition. However, it is not included in the syntax diagrams. It does appear to be supported.

Page URL: <https://duckdb.org/docs/sql/statements/pivot.html>

**Comment by szarnyasg** [comment]
Thanks! These are indeed supported (along with OFFSET) in PIVOT.
