### ISSUE TITLE
Document out-of-core capabilities

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb-web#1715]
I think it's a little unclear what the prerequisites are for being able to run out-of-core and what the limitations are.

I believe the user either needs to open a persistent database or set a temp_directory to make use of it, and some of the limitations are for example that an intermediate still needs to fit in memory ?

But I am hardly the expert on this area, I think Laurens, Mark and Richard could probably write a book on it at this point though.
Also now that I think about it, this information can probably be pieced together from our blog posts on the subject

**Comment by szarnyasg** [comment]
This is likely something we can put under the series of Performance guides. It should be summarized in the main guide, e.g., we already mention (in the performance guide draft) that you need a disk to spill on for larger than memory processing; but of course there are more nuances than that.
