### ISSUE TITLE
Issue found on page 'INSERT Statement' (Typo)

### ISSUE THREAD

**Issue by txbm** [duckdb/duckdb-web#1731]
_Please describe the issue on the page and include the "Page URL" link shown below._

Page URL: <https://duckdb.org/docs/sql/statements/insert.html>

<img width="912" alt="Screenshot 2023-12-07 at 10 28 32 AM" src="https://github.com/duckdb/duckdb-web/assets/102656/84f69300-1580-4f94-b7c5-ebd1f2c1c784">

Says "INSRET" -- I think it's supposed to say `INSERT` 😄

**Comment by szarnyasg** [comment]
Indeed, thanks. Will fix this after taking care of #1730
