### ISSUE TITLE
Syntax to select multiple columns from expression api is unclear

### ISSUE THREAD

**Issue by KevDAll** [duckdb/duckdb-web#1758]
To me the 

I think it would be  clearer if the examples for the python expressions API specifically showed selecting multiple columns as positional arguments. Page URL: <https://duckdb.org/docs/api/python/expression.html>

for example:
```
import duckdb
import pandas as pd

df = pd.DataFrame({'a': [1, 2, 3, 4],
                   'b': [5, 6, 7, 8]})

col_a = duckdb.ColumnExpression('a')
col_b = duckdb.ColumnExpression('b')
res = duckdb.df(df).select(col_a, col_b).fetchall()
print(res)
# [(1, 5), (2, 6), (3, 7), (4, 8)]
```

The way the documentation is written its unclear that each expression should be a positional argument. 

I tried:
```
expression_list = [col_a, col_b]
res = duckdb.df(df).select(expression_list).fetchall()
```
and
```
expression_list = [col_a, col_b]
res = duckdb_df(df)
for e in expression_list:
    res = duckdb.df(df).select(e)
res.fetch_all()
```
before realizing the correct syntax is:
```
expression_list = [col_a, col_b]
res = duckdb.df(df).select(*expression_list).fetchall()
```

**Comment by szarnyasg** [comment]
Thanks, we'll look into this. cc @Tishj
