### ISSUE TITLE
Tutorials and How-To Guides

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb-web#178]
I found this guide on [writing good documentation](https://documentation.divio.com/introduction/). It essentially advocates for splitting documentation into four distinct groups:

* Tutorials
* How-To Guides
* References
* Explanations

Most of the documentation we have is in the form of `Reference`, which, while useful, is perhaps not sufficient particularly for beginners.

What do you guys think about splitting the documentation into three separate sections -- `Tutorials`, `How-To Guides` and `Reference`. Most of the current material would go under the `Reference` section, and we could write up a few language-specific tutorials for getting started and how-to guides for accomplishing common tasks in each of these.

Thoughts?

**Comment by Alex-Monahan** [comment]
I like this idea! I think the explanations section is well covered with our blog posts (although we could always use more of those!). Maybe we could include those in the side bar menu in a section at the bottom just as one more way for folks to find them.

For the Tutorials, I think a getting started guide for each language would be good, as well as some other things on our roadmap like compilation instructions and revisiting the contribution guide / making it more prominent. 

I'm not as sure on the first few things I would add to a How-to-guide section at the moment, but maybe some of our Blogs meet that need as well? Maybe we ought to start with the Tutorials anyway.

Could we call the Reference section "API Reference"? I see that frequently in Docs.

**Comment by Mytherin** [comment]
I have added some how-to guides to the website [here](https://duckdb.org/docs/guides/index). Feedback is appreciated!

**Comment by Alex-Monahan** [comment]
Guides are working great!
