### ISSUE TITLE
columns parameter Issue found on page 'CSV Import'

### ISSUE THREAD

**Issue by harsha-aarini** [duckdb/duckdb-web#1780]
in the read_csv method columns parameter accepts [{column_name1:type1, column_name2:type2}] for all columns. But why does the columns specified in the parameter need to be in the same order as the columns in the csv. We are passing key value pairs right. Making the functionality order independent should be possible right?

Page URL: <https://duckdb.org/docs/archive/0.9.2/data/csv/overview.html>

I am using duckdb python client version `duckdb==0.9.2` in python 3.11.5

Code to reproduce the issue:
```
import duckdb
con = duckdb.connect(database=':memory:')

# data_uri = "https://duckdb.org/data/flights.csv"
data_uri = "flights.csv"
data_types = {'UniqueCarrier': 'VARCHAR', 'FlightDate': 'DATE', 'OriginCityName': 'VARCHAR',  'DestCityName': 'VARCHAR'}
con.execute(f"""
    COPY (SELECT * FROM read_csv('{data_uri}', header=true, delim='|',COMPRESSION="none",columns={data_types}))
    TO 'myparquet.parquet'
    (FORMAT PARQUET, CODEC 'SNAPPY', ROW_GROUP_SIZE 100000);
    """)

con.close()
```

Download flights.csv from url [https://duckdb.org/data/flights.csv](https://duckdb.org/data/flights.csv) and try to run the code.

This error is not seen when using the above url itself directly (uncomment the data_uri with url and comment the flights.csv). It is also seen when using file from gcp bucket

**Comment by pdet** [comment]
The option of `columns` is used to define the name and types of the columns, by order of appearance in the file. 
It is not intended to be used as a map for type definition to column names in a header.
Alternatively, you can also define the types (again in order) with `types`.
