### ISSUE TITLE
Issue found on page 'Aggregate Functions'

### ISSUE THREAD

**Issue by paultiq** [duckdb/duckdb-web#1785]
_Please describe the issue on the page and include the "Page URL" link shown below._

When using group_concat/string_agg, it isn't clear that the way to use a custom delimiter is to put it after the delimiter in the second argument: 
` select group_concat(distinct column_name, '-- ' order by ordinal_position)
from information_schema.columns`

What's confounding is that this syntax also works (but is not documented either):
`select group_concat(distinct column_name order by ordinal_position)
from information_schema.columns`

This seems related to https://github.com/duckdb/duckdb/issues/7281, where I think the user's solution was the first example above. 

Postgres' doc makes this a bit clearer: 
https://www.postgresql.org/docs/current/sql-expressions.html#SYNTAX-AGGREGATES

Page URL: <https://duckdb.org/docs/sql/aggregates.html>

**Comment by szarnyasg** [comment]
Hi @paultiq thanks for raising this issue! Can you clarify what you see as the main issue on this page?

> it isn't clear that the way to use a custom delimiter is to put it after the delimiter in the second argument:
Do you mean "to use a custom ordering" here?

This is explained in the section above: https://duckdb.org/docs/sql/aggregates.html#order-by-clause-in-aggregate-functions. We can certainly link to this section from the affected functions.

**Comment by paultiq** [comment]
Thanks for checking this out. Here's a better example:

```py
import duckdb

print(duckdb.execute("pragma version").df())
# 0  v0.9.3-dev1996  dae3b286b0

duckdb.execute("create or replace table xyz as select 1 a, 2 b, 3 c")

result_incorrect = duckdb.execute("select group_concat(column_name order by column_name, '-' ) from information_schema.columns").df()
print(result_incorrect)

# Note that the delimiter is ignored
# group_concat(column_name ORDER BY column_name, '-')
# 0                                              a,b,c

result_correct = duckdb.execute("select group_concat(column_name, '-'  order by column_name) from information_schema.columns").df()
print(result_correct)

#  group_concat(column_name, '-' ORDER BY column_name)
# 0                                              a-b-c 

```

Altho, on reflection, perhaps this is just a bug and not a documentation issue.

* My point about Postgres was this explanation, but now that I think about it, this isn't the issue. The issue is that the delimiter is ignored if the order by is first:  "The latter is syntactically valid, but it represents a call of a single-argument aggregate function with two ORDER BY keys (the second one being rather useless since it's a constant)." <https://www.postgresql.org/docs/current/sql-expressions.html#SYNTAX-AGGREGATES>

**Comment by szarnyasg** [comment]
Thanks for elaborating on this.

I think the explanation in the Postgres docs is great:

> The latter is syntactically valid, but it represents a call of a single-argument aggregate function with two ORDER BY keys (the second one being rather useless since it's a constant).

I'll update the documentation in a second to explain that the `ORDER BY` clause has to come last, after the argument. Hopefully that helps avoid the confusion.
