### ISSUE TITLE
Issue found on page 'Command Line Arguments'

### ISSUE THREAD

**Issue by rmoff** [duckdb/duckdb-web#1813]
Page URL: <https://duckdb.org/docs/api/cli/arguments.html>

`output mode` links (`https://duckdb.org/docs/api/cli/arguments#output-formats`) don't go anywhere

**Comment by rmoff** [comment]
should link to https://duckdb.org/docs/api/cli/output-formats instead?

**Comment by szarnyasg** [comment]
@rmoff, indeed, thanks for reporting this. A fix is coming in a second.
