### ISSUE TITLE
Issue found on page 'INSERT Statement'

### ISSUE THREAD

**Issue by michael-simons** [duckdb/duckdb-web#1823]
_Please describe the issue on the page and include the "Page URL" link shown below._

Page URL: <https://duckdb.org/docs/sql/statements/insert.html>

Under [Defining a Conflict Target](https://duckdb.org/docs/sql/statements/insert.html#defining-a-conflict-target) it says

```sql
INSERT INTO tbl VALUES (1, 40, 700) ON CONFLICT (i) DO UPDATE SET k = 2 * EXCLUDED.;
```

Note the missing column at the end. Is this correct?

**Comment by szarnyasg** [comment]
Yes, indeed column `k` should be there. Thanks for reporting this! A fix is on its way.

**Comment by michael-simons** [comment]
Excellent, thank you!
