### ISSUE TITLE
CodeMirror SQL highlighting shows {}'s as errors

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb-web#183]
We are also missing some of the newer keywords like Qualify and Having. Is there a good way to pull a list of keywords with a DuckDB script where we could build a DuckDB-specific dialect for CodeMirror?

Thanks!

**Comment by Mytherin** [comment]
This will give you the list of keywords:

```sql
select * from duckdb_keywords();
```

**Comment by hawkfish** [comment]
I added curry braces to [rouge](https://github.com/rouge-ruby/rouge) a while back, but it takes a while for things to propagate.

**Comment by Mause** [comment]
@Alex-Monahan how do you feel about switching the docs site to a GitHub actions based build? Would mean we could just fix this right away, rather than wait ages for the bugfix to propogate

**Comment by Alex-Monahan** [comment]
> @Alex-Monahan how do you feel about switching the docs site to a GitHub actions based build? Would mean we could just fix this right away, rather than wait ages for the bugfix to propogate

Hmm, I don't know how different that would be from today! Would it impact local testing at all or could I still run jekyll serve on my local? If I can still do that, I don't see a reason why not!

**Comment by Mause** [comment]
> > @Alex-Monahan how do you feel about switching the docs site to a GitHub actions based build? Would mean we could just fix this right away, rather than wait ages for the bugfix to propogate
> 
> Hmm, I don't know how different that would be from today! Would it impact local testing at all or could I still run jekyll serve on my local? If I can still do that, I don't see a reason why not!

It wouldn't change anything for you locally no, just change how the deployed version is built slightly (technically it's already being built by GitHub Actions anyway, see https://github.blog/2022-08-10-github-pages-now-uses-actions-by-default/) it would just mean we can choose which versions of libraries it's built with, eg, rouge!

The only thing it would need from @hannes or @Mytherin is to flip the setting to support it (once the github action is configured in the repo)

**Comment by Mytherin** [comment]
That sounds good to me

**Comment by Alex-Monahan** [comment]
Sounds great, thank you!
