### ISSUE TITLE
Documentation on type casting would benefit from a cross reference

### ISSUE THREAD

**Issue by rpbouman** [duckdb/duckdb-web#1837]
The following two documentation pages are about type casting:

https://duckdb.org/docs/sql/data_types/typecasting
https://duckdb.org/docs/sql/expressions/cast

The first one deals with which source types can be cast to which target types (casting semantics), the second one deals with the explicit SQL CAST expression.

The topics are different but related and someone that needs information from one of these pages is likely to be interested or benefit in the other page. Right now the pages do not link to each other, which is mildly inconvenient.

If others agree the documentation could be improved by crosslinking then I can make an edit and send a PR.

**Comment by szarnyasg** [comment]
Hi @rpbouman, I'm all in for adding more cross-links to the documentation. A PR implementing this for type casting pages would be very welcome!

**Comment by rpbouman** [comment]
https://github.com/duckdb/duckdb-web/pull/1844 submitted. Let me know if you require anything else.
