### ISSUE TITLE
add documentation for `preserve_insertion_order`

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb-web#1855]
I could not find anything mentioning this option in the docs

If I just missed it, feel free to close this issue 👍

**Comment by szarnyasg** [comment]
Hey @Tishj, it is explained in 3 pages:
- https://duckdb.org/docs/sql/statements/copy.html#parquet-options
- https://duckdb.org/docs/sql/configuration#configuration-reference
- https://duckdb.org/docs/guides/performance/how-to-tune-workloads.html#the-preserve_insertion_order-option

Despite this, the search option (Cmd+K) does not find it, so there is definitely room for improvement in that area.
