### ISSUE TITLE
Difference between FILTER and FILTER WHERE 

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb-web#1858]
Given the schema,
```sql
CREATE TABLE sales(region VARCHAR, amount BIGINT);
```
is there a difference between
```sql
SELECT sum(amount), sum(amount) FILTER (region != 'north') FROM sales;
```
and
```sql
SELECT sum(amount), sum(amount) FILTER (WHERE region != 'north') FROM sales;
```
?

(see https://duckdb.org/docs/sql/aggregates.html)

From what I can tell they seem to be the same. If that's true, maybe the docs could be updated to only ever use the WHERE-less version, to avoid confusion? For example, https://duckdb.org/docs/sql/query_syntax/filter.html only uses the `FILTER (WHERE ...)` version currently but the syntax diagram shows that the WHERE is optional.

**Comment by szarnyasg** [comment]
There's no difference, and it's indeed to drop it from the docs for consistency. Thanks!
