### ISSUE TITLE
redundant BUILD_TPCH=1 for benchmark suite

### ISSUE THREAD

**Issue by ccfelius** [duckdb/duckdb-web#1914]
`BUILD TPCH=1` is stated twice, this should be once

<img width="770" alt="Screenshot 2024-01-19 at 12 00 35" src="https://github.com/duckdb/duckdb-web/assets/31962897/982aadd0-0567-42ec-9838-1344d0194406">

**Comment by szarnyasg** [comment]
Thanks!
