### ISSUE TITLE
Auto-update docs jobs is failing

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb-web#1928]
https://github.com/duckdb/duckdb-web/actions/runs/7606692874/job/20712873266

```bash
  > ×	[main] command [./scripts/generate_all_docs.sh duckdb] exited with code 1. message: + '[' duckdb = '' ']'
```

**Comment by Mause** [comment]
Just due to the extension build failing in the main repo:

```
>> Error: near line 3: HTTP Error: Failed to download extension "httpfs" at URL "http://extensions.duckdb.org/95e6a0369f/linux_amd64_gcc4/httpfs.duckdb_extension.gz"
    >> Extension "httpfs" is an existing extension.
    >> 
    >> Are you using a development build? In this case, extensions might not (yet) be uploaded.
    >> Error: near line 4: IO Error: Extension "/home/runner/.duckdb/extensions/95e6a0369f/linux_amd64_gcc4/httpfs.duckdb_extension" not found.
    >> Extension "httpfs" is an existing extension.
    >> 
    >> Install it first using "INSTALL httpfs".
```

**Comment by szarnyasg** [comment]
Ah, alright. One thing that is confusing in the current documentation of the scripts is that some places say "use the nightly build" while others say "use the debug build" (https://github.com/duckdb/duckdb-web/blob/main/scripts/generate_all_docs.sh#L4-L11). Nightly should be sufficient, right?

**Comment by Mause** [comment]
Debug isn't required no, where does it say that?

**Comment by szarnyasg** [comment]
https://github.com/duckdb/duckdb-web/blob/dbb7e10f09f63af61f75d09b2af134e4c9af1da7/scripts/generate_all_docs.sh#L4-L11

**Comment by Mause** [comment]
Hmm okay. Do you remember why you added that?

**Comment by szarnyasg** [comment]
Probably by mistake, will edit it out now.

**Comment by szarnyasg** [comment]
No, actually, reading further down the script, we run the following:
https://github.com/duckdb/duckdb-web/blob/dbb7e10f09f63af61f75d09b2af134e4c9af1da7/scripts/generate_all_docs.sh#L17

**Comment by szarnyasg** [comment]
And I think this mislead me. Okay, will amend the README.

**Comment by szarnyasg** [comment]
Okay, so I think it works with both the `debug` and the `release` builds. We just have to settle on one. Likely `release` is the simpler choice.
