### ISSUE TITLE
Documentation: Clarify usage of NUMERIC type as floating point alternative

### ISSUE THREAD

**Issue by rgieseke** [duckdb/duckdb-web#1979]
The "Numeric Types" page states in the 'Floating Points Caveats' section:
 
> If you require exact storage and calculations (such as for monetary amounts), use the numeric type instead.

Maybe 'numeric' could be changed to either 'NUMERIC type' or 'decimal type' or 'DECIMAL type' to avoid confusion with the topic of the page.

One has to already know that 'NUMERIC' is an alias for 'DECIMAL' to immediately get the sentence otherwise.

Page URL: <https://duckdb.org/docs/sql/data_types/numeric.html>

**Comment by szarnyasg** [comment]
@rgieseke that's a very good point – thanks! I submitted a fix.

**Comment by rgieseke** [comment]
Thank you, that's a very nice and thorough solution (I wasn't sure which version works best, yours does!)
