### ISSUE TITLE
Documentation: JSON dot / array syntax

### ISSUE THREAD

**Issue by lnkuiper** [duckdb/duckdb-web#1980]
We can now extract fields from JSON using our struct/array extract syntax. Examples can be found [here](test/sql/json/scalar/test_json_dot_syntax.test).

This should be documented [here](https://duckdb.org/docs/archive/0.9.2/extensions/json#json-extraction-functions).

**Comment by szarnyasg** [comment]
@lnkuiper thanks for the pointers. It seems that some of the existing examples in https://duckdb.org/docs/extensions/json no longer work, can you please confirm that this is intended?

## 1
```sql
SELECT json_keys FROM example;
-- [family, species]
```
Error: Binder Error: Referenced column "json_keys" not found in FROM clause!
Candidate bindings: "example.j"
LINE 1: SELECT json_keys FROM example;
               ^
```
```
## 2
```sql
SELECT json_contains('{"key": 1}', 1);
-- true
```
```
Error: Binder Error: No function matches the given name and argument types 'json_contains(STRING_LITERAL, INTEGER_LITERAL)'. You might need to add explicit type casts.
        Candidate functions:
        json_contains(VARCHAR, VARCHAR) -> BOOLEAN
        json_contains(VARCHAR, JSON) -> BOOLEAN
        json_contains(JSON, VARCHAR) -> BOOLEAN
        json_contains(JSON, JSON) -> BOOLEAN

LINE 1: SELECT json_contains('{"key": 1}', 1);
               ^
```
## 3
```sql
SELECT json_contains('{"key": 1}', 1);
-- true
```
```
Error: Binder Error: No function matches the given name and argument types 'json_contains(STRING_LITERAL, INTEGER_LITERAL)'. You might need to add explicit type casts.
        Candidate functions:
        json_contains(VARCHAR, VARCHAR) -> BOOLEAN
        json_contains(VARCHAR, JSON) -> BOOLEAN
        json_contains(JSON, VARCHAR) -> BOOLEAN
        json_contains(JSON, JSON) -> BOOLEAN

LINE 1: SELECT json_contains('{"key": 1}', 1);
```

**Comment by lnkuiper** [comment]
1 Should be `select json_keys(j) from example`
2 and 3 are because of changes to implicit string casting. Supplying a string arg, i.e. `'1'` should make them work again
