### ISSUE TITLE
Download link for CLI and C++ not sensitive to system detected

### ISSUE THREAD

**Issue by philip-khor** [duckdb/duckdb-web#20]
System detected seems to be hardcoded in the links: 

https://github.com/cwida/duckdb-web/blob/82d4855e69dcbaafbccf2699f7d1b0b8072d852e/index.html#L143-L144

On Windows 10 Firefox 86.0a1
![image](https://user-images.githubusercontent.com/35039795/103133598-5062b280-46e6-11eb-9a6a-3ef4b4218502.png)

Similarly on Edge 87.0.664.66 

![image](https://user-images.githubusercontent.com/35039795/103133626-75572580-46e6-11eb-8ff7-04acd3ff9dca.png)

**Comment by szarnyasg** [comment]
Auto-detect seems to be working now, can you check again?
