### ISSUE TITLE
Document friendly SQL extensions on a single page

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb-web#2041]
We have nice SQL extensions but they are currently scattered across the documentation. They are described in two blog posts but they are not exhaustive (e.g. `UNION BY NAME` is not covered):

- https://duckdb.org/2022/05/04/friendlier-sql.html
- https://duckdb.org/2023/08/23/even-friendlier-sql.html

We should add a guide page that summarizes them.

**Comment by rpbouman** [comment]
On this topic, in the 2023 article the term "reuasable column alias" (https://duckdb.org/2023/08/23/even-friendlier-sql.html#reusable-column-aliases) is used, and here is the relevant text:

> When working with incremental calculated expressions in a select statement, traditional SQL dialects force you to either write out the full expression for each column or create a common table expression (CTE) around each step of the calculation. Now, any column alias can be reused by subsequent columns within the same select statement. Not only that, but these aliases can be used in the where and order by clauses as well.

I think this is what databricks refers to as "lateral column alias". (see https://www.databricks.com/blog/introducing-support-lateral-column-alias#:~:text=In%20summary%2C%20Lateral%20Column%20Alias,within%20the%20same%20SELECT%20clause.) 

This may be nitpicks, but personally I think the term "lateral column alias" is more accurate and descriptive than "reusable alias".

Even if there is some reason to not go with "lateral column alias", I think this is not a case of "reuse" but of "referencing", in that the column alias is not reused, as reuse implies using an existing thing for another purpose. Here, the alias it being used to refer to the value of the column expression preceding the alias.

Also, where it says "...within the same select statement", I think it is more accurate to say: "...within the same SELECT-Clause". It was in some cases already possible to reference a column alias elsewhere in the same SELECT-statement, for example, in the ORDER BY clause. The described functionality is really about it now being possible to reference a column within the SELECT-clause.
