### ISSUE TITLE
Filter Clause Documentation in SQL Sidebar

### ISSUE THREAD

**Issue by g-tanzi** [duckdb/duckdb-web#205]
The documentation [page](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiy6KPB_ab3AhWYRzABHcfqDOwQFnoECAkQAQ&url=https%3A%2F%2Fduckdb.org%2Fdocs%2Fsql%2Fquery_syntax%2Ffilter&usg=AOvVaw0XfCJ0_LwtSR5GgSdBitE7) for the filter clause is available in search [engines](https://www.google.com/search?q=duckdb+filter), but is not accessible from the duckdb documentation sql sidebar:

![image](https://user-images.githubusercontent.com/80792876/164611886-5f781586-0e60-4a46-8f7d-30c3ee3f61ee.png)

**Comment by Mause** [comment]
Looks like this now rectified
