### ISSUE TITLE
File formats page: Zonemap links

### ISSUE THREAD

**Issue by csgillespie** [duckdb/duckdb-web#2052]
This [section](https://duckdb.org/docs/guides/performance/file_formats.html#reasons-for-querying-parquet-files)  contains a link to "zonemaps". 

However, the page it links to (https://duckdb.org/docs/guides/performance/schema#zonemaps) doesn't contain the word "zonemap".

**Comment by szarnyasg** [comment]
Thanks, that's a good point and this was indeed a broken link. Fix submitted now.
