### ISSUE TITLE
[duckdb/#6791] - Partitioned file naming

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb-web#2053]
See https://github.com/duckdb/duckdb/pull/6791

This PR changed the COPY option `allow_overwrite` into `overwrite_or_ignore`
Relevant docs: https://duckdb.org/docs/sql/statements/copy#copy--to-options

**Comment by szarnyasg** [comment]
@Tishj thanks for pointing this out. The fix is on its way.
