### ISSUE TITLE
Issue found on page 'Nested Functions'

### ISSUE THREAD

**Issue by michael-simons** [duckdb/duckdb-web#2057]
That rendering seems wrong:

![image](https://github.com/duckdb/duckdb-web/assets/526383/102449fa-6d4e-445c-b249-fbc2bf82a89e)

Page URL: <https://duckdb.org/docs/sql/functions/nested.html>

**Comment by szarnyasg** [comment]
That's indeed broken, thanks! A fix is incoming.
