### ISSUE TITLE
Wrong font on some headers

### ISSUE THREAD

**Issue by carlopi** [duckdb/duckdb-web#2061]
I have seen this in various devices (not always the same text, but parts with wrong fonts being loaded).
There seems to be some specific styling that needs to be updated. Issue looks to be like there is a mashup of old and new CSSs, but I don't get if that's possible after a week or so.

Anyhow, check `array_to_string` in the image, should be clear, see https://duckdb.org/docs/sql/functions/nested.html#array_to_string

![image](https://github.com/duckdb/duckdb-web/assets/842657/66d30524-82c9-4b95-abab-6d81888697b5)

**Comment by szarnyasg** [comment]
Can confirm – I got the same (serif font for monospace headers) while on the train to FOSDEM with the unreliable train wifi.

**Comment by szarnyasg** [comment]
Resolved via #2080
