### ISSUE TITLE
Issue found on page 'Enum Data Type': document enum ordering

### ISSUE THREAD

**Issue by eeriksp** [duckdb/duckdb-web#2149]
It seems that enums implement the `>` and `<` operators, however, their behaviour does not seem to be described anywhere.
Are enums compared as strings? Or are they compared based on the order the elements are defined?

Based on my experiments the later seems to be true:

```sql
CREATE TYPE bar AS ENUM ('b', 'a')
SELECT 'a'::bar > 'b'::bar
```

returns

```
┌───────────────────────────────────────┐
│ (CAST('a' AS bar) > CAST('b' AS bar)) │
│                boolean                │
├───────────────────────────────────────┤
│ true                                  │
└───────────────────────────────────────┘
```
Would be nice to add that explicitly to the enums documentation page.

Page URL: <https://duckdb.org/docs/sql/data_types/enum.html>

**Comment by szarnyasg** [comment]
This is a great point, thanks for raising this issue. A PR is incoming!
