### ISSUE TITLE
Issue found on page 'Timestamp with Time Zone Functions' for localtime function

### ISSUE THREAD

**Issue by bouvierr** [duckdb/duckdb-web#2163]
Page URL: <https://duckdb.org/docs/sql/functions/timestamptz.html> (version 0.10.0)
Page URL: <https://duckdb.org/docs/archive/0.9.2/sql/functions/timestamptz.html>

This issue affects the documentation for versions 0.9.2 and 0.10.0.

In the table under the **[ICU Timestamp Without Time Zone Functions](https://duckdb.org/docs/sql/functions/timestamptz.html#icu-timestamp-without-time-zone-functions)** section:
The `Result` cell for the `localtime` function shows `2022-12-17 08:47:56.497`, but it should only show the time portion `08:47:56.497`, as for the `current_localtime()` function.

**Comment by szarnyasg** [comment]
Indeed, thanks for raising this. I submitted a fix.
