### ISSUE TITLE
file_size_bytes option in COPY Statement documentation has incorrect type and default

### ISSUE THREAD

**Issue by jlwalsh-amazon** [duckdb/duckdb-web#2166]
On the [Copy Statement](https://duckdb.org/docs/sql/statements/copy.html) page, there is a new option that was added as part of the `0.10.0` update called `file_size_bytes`. This option is named/described such that the value should be an integer number that represents the number of bytes each output file should be, but the listed Type is `BOOL` (and the listed default is `FALSE`. 

The Type and Default should be updated to the correct values.

**Comment by szarnyasg** [comment]
Indeed those were off, thanks for reporting. I'm submitting a fix.
