### ISSUE TITLE
CSS issue, header "Documentation" dropdown unreadable

### ISSUE THREAD

**Issue by Bl3f** [duckdb/duckdb-web#2223]
Hello, there is a weird issue on the website, when hovering "Documentation" in the menu bar it's impossible to see the content of the dropdown. The text has a black color on a black background. See the screenshot.

I can reproduce the issue on Firefox, Chrome and Arc on a MacOS.

<img width="1800" alt="Screenshot 2024-02-19 at 18 03 01" src="https://github.com/duckdb/duckdb-web/assets/2658211/b3c352ce-c0c4-4e53-81ad-e23cb6533aac">

It seems the issues comes from https://github.com/duckdb/duckdb-web/blame/main/css/main.scss#L354 (cc. @jonathanauch)

**Comment by szarnyasg** [comment]
@Bl3f thanks for letting us now! I fixed this via #2224 - the website will be deployed in <10 minutes.
