### ISSUE TITLE
Format tables using DuckDB's Markdown formatter

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb-web#2236]
Two points:

1) DuckDB's outputs should be rendered as a table (in most cases).
2) Tables should have their numeric (int/float) cells right-aligned.

Related to #2, See the new feature introduced in https://github.com/duckdb/duckdb/pull/10767

Note: there are 155 tables in the documentation.

```bash
$ agidm ┌  | grep ┌ | wc -l
     155
```

**Comment by szarnyasg** [comment]
See the new feature introduced in https://github.com/duckdb/duckdb/pull/10767

**Comment by Mause** [comment]
Should we add a check for these tables to the build?

**Comment by szarnyasg** [comment]
Ultimately we should generate these tables using the CLI client and also give the users the ability to run code snippets via Wasm. But these are long-term plans. I think there's no need to add a check for these tables now.
