### ISSUE TITLE
https://duckdb.org/docs/installation/   R GitHub master (bleeding edge) link broken

### ISSUE THREAD

**Issue by bwlewis** [duckdb/duckdb-web#224]
The instructions for R at https://duckdb.org/docs/installation/  display:

`install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`

which does not work because https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz  returns a 404 error.

**Comment by Mause** [comment]
It looks like this has been fixed: https://github.com/duckdb/duckdb-web/blob/507b471bc7cdeaaeb889e527c60b0b53b24379f8/_includes/installation.html#L163
