### ISSUE TITLE
Fetching star count occasionally fails

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb-web#2244]
See here

![Screenshot 2024-02-20 at 18 03 40](https://github.com/duckdb/duckdb-web/assets/3978469/ccef9757-c640-44e2-a55f-7d1dd0453a6c)

**Comment by szarnyasg** [comment]
This is a spurious error. I triggered the build twice and it's back to its current value (14.7k). Obviously this is no way to ran a railroad, so, next:

1) I'll add a weekly update to the hard-coded value. This will fail if it fetches 0 stars
2) For the individual CI runs, if they fetch 0 stars, they will not fail but will use the (non-zero) value obtained in step 1.
