### ISSUE TITLE
Benchmarking strategy

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb-web#226]
Hey folks!

There are certainly many other how-to-guides on my list, as well as more Relational API docs, etc. However, is now a good time to do some benchmarking? What approach should we take for running benchmarks? Spin up a few AWS instances (disclaimer: I have not done that before, but would love to give it a try!), or use my Windows desktop (or should I finally install Linux/WSL?), my ~8 year old laptop, or should we build a Docker image that folks can use to benchmark? Or a DuckDB extension for it?

As far as benchmarks, here is what I was thinking:
* TPC-H
* The H2O.ai benchmarks
* Taxi dataset?

For each benchmark, I was thinking that we would run it once per version and show a trend chart of how much DuckDB has improved over time. I was thinking maybe the Python client would be the easiest to use for scripting this out, but I am open to suggestions there as well!

**Comment by Mytherin** [comment]
Great idea!

For benchmarking we usually use the benchmark_runner, which gets build in the build/release/benchmark directory if BUILD_BENCHMARKS is enabled. It might be easier to use that executable and orchestrate it through a Python script. The benchmark runner prints the benchmark results in CSV format to stdout.

As for the machine, usually we use the internal CWI machines for benchmarking, but we should probably move away from that to e.g. AWS boxes. I would prefer not to use docker here. DuckDB should be rather easy to install anyway :)

**Comment by szarnyasg** [comment]
We have now established our main method of communicating benchmark results via blog posts (e.g. https://duckdb.org/2023/11/03/db-benchmark-update.html).
