### ISSUE TITLE
Issue found on page 'Aggregate Functions': MIN_BY and MAX_BY aren't documented as being "affected by ordering"

### ISSUE THREAD

**Issue by lukaseder** [duckdb/duckdb-web#2268]
Page URL: <https://duckdb.org/docs/sql/aggregates.html>

It appears that this works as expected:

```sql
SELECT 
  min_by(b, a ORDER BY b ASC)  AS min1,
  min_by(b, a ORDER BY b DESC) AS min2, 
  max_by(b, a ORDER BY b ASC)  AS max1, 
  max_by(b, a ORDER BY b DESC) AS max2
FROM (VALUES (1, 'a'), (3, 'b'), (2, 'c'), (3, 'd'), (1, 'e')) AS t (a, b);
```

Producing:

```
|min1|min2|max1|max2|
|----|----|----|----|
|a   |e   |b   |d   |
```

But the documentation on aggregate function doesn't explicitly say that these functions are *"affected by ordering"* such as e.g. `any_value()`

- https://duckdb.org/docs/sql/aggregates.html#order-by-clause-in-aggregate-functions
- https://duckdb.org/docs/sql/aggregates.html

**Comment by szarnyasg** [comment]
@lukaseder, thanks, indeed this should be documented. I'll push a fix in a second.
