### ISSUE TITLE
Issue found on page 'PostgreSQL Extension'

### ISSUE THREAD

**Issue by jedgroev** [duckdb/duckdb-web#2287]
Page URL: <https://duckdb.org/docs/extensions/postgres.html>

The following query does not create a copy of the postgres table within the duckdb database. Instead a copy is created in the postgres public schema with the name "duckdb_table". 

`
CREATE TABLE duckdb_table AS FROM postgres_db.postgres_tbl;
`

To copy the data from postgres to a duckdb database you need to run: 

`
CREATE TABLE duckdb.table AS FROM postgres_db.postgres_tbl;
`

Where "duckdb" is the name of your local duckdb-database. 

I also noticed that duckdb only reads tables from the public schema. I did not manage query other schemas.

**Comment by cdeil** [comment]
Accidentally doing any writes on a database when all I want is to attach, select and copy it for local analytics is what I fear.

I do see here that there's the READ_ONLY option:
https://duckdb.org/docs/extensions/postgres#writing-data-to-postgres

@szarnyasg  - IMO would be good to use that earlier and more prominently at the start of the page, and then only attach without it in the "writing" section.

Also at https://duckdb.org/docs/sql/statements/attach it's pretty hidden how to use it with the comma syntax `(TYPE postgres, READ_ONLY)`, I only stumbled upon it when accidentally hovering over "attach-options" in the diagram.

Finally IMO would be good to learn what "attached" means for a production database. Presumably as good citizen I should "detach" from production servers as soon as I'm done with my select and copy? Currently https://duckdb.org/docs/extensions/postgres doesn't mention that `DETACH` exists, I only then found it when reading https://duckdb.org/docs/sql/statements/attach .

**Comment by cdeil** [comment]
@szarnyasg  - some more feedback about https://duckdb.org/docs/extensions/postgres

IMO would be nice to mention that it's possible to attach and copy a whole PostgreSQL database to a local DuckDB:
https://duckdb.org/docs/sql/statements/copy#copy-from-database--to

This is so cool, I can do that in 1 minute and then have lightning fast analytics and local model and app development!

Is it also possible to copy a list of PostgreSQL schemas or tables?

In my case I have two schemas each with 10 tables that I need to copy, and there's other schemas that I don't want to copy.

**Comment by szarnyasg** [comment]
@cdeil I submitted a PR that fixes most of the observations you pointed out. If I left anything out, please let me know in a new issue. Thanks!
