### ISSUE TITLE
Mention INSERT INTO ... BY NAME on page 'Import from Pandas'

### ISSUE THREAD

**Issue by davetapley** [duckdb/duckdb-web#2379]
Page URL: <https://duckdb.org/docs/guides/python/import_pandas.html>

Would you accept a PR to suggest using `INSERT INTO ... BY NAME` when doing this:
```py
# insert into the table "my_table" from the DataFrame "my_df"
duckdb.sql("INSERT INTO my_table SELECT * FROM my_df")
```

To avoid: https://github.com/duckdb/duckdb/issues/4793#issuecomment-1972167010

**Comment by szarnyasg** [comment]
Sure, such a PR wold be appreciated!
