### ISSUE TITLE
Issue found on page 'Summarize'

### ISSUE THREAD

**Issue by JohnApps** [duckdb/duckdb-web#2419]
The table exists and all other summarize operations work correctly.

CREATE TABLE pump$_summary AS SELECT * FROM (SUMMARIZE pump$);
Run Time (s): real 0.000 user 0.000000 sys 0.000000
Error: Parser Error: syntax error at or near ")"
LINE 1: ...mmary AS SELECT * FROM (SUMMARIZE pump$);

DuckDB 0.9.2
                                                  ^

**Comment by szarnyasg** [comment]
Hi @JohnApps, support `SUMMARIZE` for subqueries was introduced in v0.10.0:
https://duckdb.org/2024/02/13/announcing-duckdb-0100.html#new-features

So, if possible, please update your client to support this feature. v0.10.0 is backwards-compatible with v0.9.2, so it is able to read files produced by the previous DuckDB version.
