### ISSUE TITLE
segment stats shows "has null" as false in pragma_storage_info

### ISSUE THREAD

**Issue by zippond** [duckdb/duckdb-web#242]
Hi,

I created a int column and insert some null values, but the pragma_storage_info() always says "has null" is false for INTEGER segment type. Is it expected?

> D create table t(i int);
D insert into t values(null),(1);
D select column_id,column_path,segment_type,stats from pragma_storage_info('t');
┌───────────┬─────────────┬──────────────┬───────────────────────────────────┐
│ column_id │ column_path │ segment_type │               stats               │
├───────────┼─────────────┼──────────────┼───────────────────────────────────┤
│ 0         │ [0]         │ INTEGER      │ [Min: 1, Max: 1][Has Null: false] │
│ 0         │ [0, 0]      │ VALIDITY     │ [Has Null: true]                  │
└───────────┴─────────────┴──────────────┴───────────────────────────────────┘
D

**Comment by hannes** [comment]
Hey this is the wrong repo for this, also the NULLness is indicated in the VALIDITY part.
