### ISSUE TITLE
Configuration Page Improvements

### ISSUE THREAD

**Issue by taniabogatsch** [duckdb/duckdb-web#2452]
Let's improve the [configuration page](https://duckdb.org/docs/configuration/overview.html) to include more details on global (DuckDB process/instance) vs. local (per-connection) options. Let's split the table into two, one for global options and another for local options. Should I open a PR, or could you have a look at this @szarnyasg? 😄 

Motivation, i.e., how I stumbled upon that this is unclear: https://github.com/marcboeker/go-duckdb/issues/176

**Comment by szarnyasg** [comment]
Yes, splitting it into two should be fine. The table is generated via https://github.com/duckdb/duckdb-web/blob/main/scripts/generate_config_docs.py, so we'll need to edit the script.

**Comment by Mause** [comment]
How are you going to determine which are global and which are local?

**Comment by taniabogatsch** [comment]
I think we can parse it from `static ConfigurationOption internal_options[] = ... ` in `config.cpp`?

**Comment by Mause** [comment]
Why not just expose that information via `duckdb_settings()`?

**Comment by Tishj** [comment]
Wait, I didn't even see this issue, I just ran into it as part of the sqllogictest python library effort 😅

**Comment by taniabogatsch** [comment]
I'll link your PR @Tishj :) https://github.com/duckdb/duckdb/pull/11017

**Comment by szarnyasg** [comment]
@taniabogatsch I submitted a PR implementing this change. One thing I'd like to discuss is – what would be better, splitting the table in two or adding an extra column "default scope"? I lean towards the latter as the scope is merely a default that can be changed by using [`SET GLOBAL` and `SET LOCAL`](https://duckdb.org/docs/sql/statements/set#scopes). WDYT?

**Comment by taniabogatsch** [comment]
I've no clear preference, so I'd say go with whatever makes more sense to you. Two tables made more sense to me logically because we separate between configuring a connection and the whole database. But an extra column sounds reasonable as well.

**Comment by szarnyasg** [comment]
Alright, I implemented this and I went with the split-table setup.
