### ISSUE TITLE
Documentation on the website does not have search

### ISSUE THREAD

**Issue by alexey-milovidov** [duckdb/duckdb-web#246]
Or I cannot easily find it.

**Comment by Alex-Monahan** [comment]
We have a prototype, but it is not finalized! What do you think of it?
#136

**Comment by alexey-milovidov** [comment]
We have used a similar library named Lunr.js, but as documentation becomes bigger, the index starts to take multiple megabytes and users start to complain of a long pause before being able to search.

**Comment by Mause** [comment]
@Alex-Monahan is there a reason is hasn't been linked anywhere yet?

**Comment by Alex-Monahan** [comment]
> @Alex-Monahan is there a reason it hasn't been linked anywhere yet?

I'll actually redirect that question to @Mytherin who built the feature!

**Comment by Mytherin** [comment]
Mostly I was too lazy to do the UI integration myself :)

I think it can be integrated. Perhaps we should ask our web designer to have a look?

**Comment by Mause** [comment]
@Mytherin would probably be worth asking?

**Comment by rmoff** [comment]
+1 for needing docs search. I didn't realise until noticing that it wasn't there how ubiquitous it is on many other docs sites nowadays. Google and in-page search with the browser are OK, but it adds friction.

**Comment by Alex-Monahan** [comment]
Check out our prototype here!
https://duckdb.org/docs/search

**Comment by alexey-milovidov** [comment]
It feels very good, and in my opinion, it is much better than the search available in the ClickHouse documentation.

**Comment by rmoff** [comment]
I like it! Will it be integrated on each page e.g. in the search bar?

**Comment by Mause** [comment]
This has now been implemented
