### ISSUE TITLE
Issues found on some pages

### ISSUE THREAD

**Issue by teklinp** [duckdb/duckdb-web#2471]
While reading the documentation, a couple of things caught my eye. I'm not sure whether I'm right in every case.

Page URL: <https://duckdb.org/docs/sql/statements/create_macro.html>

1. Syntax diagram should have `:=` instead of `=`.
2. Incorrect:
```
SELECT add_default(b = 2, 40);
```
Correct (missing `:`):
```
SELECT add_default(b := 2, 40);
```

Page URL: <https://duckdb.org/docs/sql/statements/create_view.html>

3. Incorrect:
```
SELECT sql FROM duckdb_views() WHERE view_name = v1;
```
Correct (missing `''`):
```
SELECT sql FROM duckdb_views() WHERE view_name = 'v1';
```

Page URL: <https://duckdb.org/docs/sql/query_syntax/grouping_sets.html>

4. Incorrect:
```
right(GROUPING_ID(y, q, m)::BIT, 3) AS "y_q_m_bits"
```
Correct (missing `::VARCHAR`):
```
right(GROUPING_ID(y, q, m)::BIT::VARCHAR, 3) AS "y_q_m_bits"
```

Page URL: <https://duckdb.org/docs/sql/query_syntax/orderby.html>

5. Incorrect:
```
Using ASC NULLS LAST as default the default sorting order was a breaking change in version 0.8.0. Prior to 0.8.0, DuckDB sorted using ASC NULLS FIRST.
```
Correct (`default` twice):
```
Using ASC NULLS LAST as the default sorting order was a breaking change in version 0.8.0. Prior to 0.8.0, DuckDB sorted using ASC NULLS FIRST.
```

Page URL: <https://duckdb.org/docs/sql/data_types/overview.html>

6. Looks worse:
```
DuckDB supports five nested data types: ARRAY, LIST, STRUCT, MAP, and UNION.
```
Looks better (alphabetical order):
```
DuckDB supports five nested data types: ARRAY, LIST, MAP, STRUCT, and UNION.
```

Page URL: <https://duckdb.org/docs/sql/data_types/bitstring.html>

7. Incorrect:
```
SELECT '101010'::BIT
```
Correct (missing `;`):
```
SELECT '101010'::BIT;
```

Page URL: <https://duckdb.org/docs/sql/functions/date.html>

8. Maybe in addition to:
```
SELECT DATE '1992-03-22' + INTERVAL 1 DAY * d.days FROM (VALUES (5), (11)) AS d(days)
SELECT DATE '1992-03-27' - INTERVAL 1 DAY * d.days FROM (VALUES (5), (11)) AS d(days)
```
Add also (looks better to me):
```
SELECT DATE '1992-03-22' + INTERVAL (d.days) DAY FROM (VALUES (5), (11)) AS d(days)
SELECT DATE '1992-03-27' - INTERVAL (d.days) DAY FROM (VALUES (5), (11)) AS d(days)
```

Page URL: <https://duckdb.org/docs/sql/functions/nested.html>

9. Incorrect:
```
list_slice(list, begin, end)
list_slice(list, begin, end)
array_slice(list, begin, end, step)
array_slice(list, begin, end, step)
list[begin:end]
list[begin:end:step]
```
Correct (`list_slice` missing `step`, `array_slice` `step` twice):
```
list_slice(list, begin, end)
list_slice(list, begin, end, step)
array_slice(list, begin, end)
array_slice(list, begin, end, step)
list[begin:end]
list[begin:end:step]
```

Page URL: <https://duckdb.org/docs/sql/functions/char.html>

10. Incorrect:
```
Removes any occurrences of any of the characters from the left sduide of the string
```
Correct (`side`):
```
Removes any occurrences of any of the characters from the left side of the string
```
11. Is it needed or an error?
```
// s == "The answer is 42."
```

Page URL: <https://duckdb.org/docs/sql/functions/utility.html>

12. I think `repeat_row` is a table function and not a scalar one?

Page URL: <https://duckdb.org/docs/sql/keywords_and_identifiers.html>

13. Incorrect:
```
Additionally, it is best practive
```
Correct (`practice`):
```
Additionally, it is best practice
```

**Comment by szarnyasg** [comment]
Thanks a lot! This is a very thorough list of issues and they were all valid issues. I submitted a PR that fixes all of them.
