### ISSUE TITLE
Document dot operator function chaining

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb-web#2502]
I think there is another Friendly SQL feature that may need its own mention in the docs! I don't think the dot operator function chaining syntax is on either the functions overview page, the friendly SQL guide, or on another page. 

The original PR is here: https://github.com/duckdb/duckdb/pull/6725
There is another PR that adds support for reusable aliases in combination with this syntax: https://github.com/duckdb/duckdb/pull/7313

**Comment by szarnyasg** [comment]
And also this: https://github.com/duckdb/duckdb/pull/7313, which just came to my attention thanks to Nick's comment.

**Comment by Alex-Monahan** [comment]
Thank you!!
