### ISSUE TITLE
Document max_depth parameter in UNNEST 

### ISSUE THREAD

**Issue by douenergy** [duckdb/duckdb-web#2515]
In https://github.com/duckdb/duckdb/pull/6755/, Mark have added support for `recursive` and `max_depth` in UNNEST to facilitate the ingestion of deeply nested data.

Following https://github.com/duckdb/duckdb-web/pull/784

I would like to fix this.

**Comment by szarnyasg** [comment]
@douenergy indeed, thanks for pointing this out! I'm happy to review a PR.
