### ISSUE TITLE
Installation guide for v0.9.2 points to wrong binary file

### ISSUE THREAD

**Issue by jeewonhh** [duckdb/duckdb-web#2546]
[Installation guide for v0.9.2](https://duckdb.org/docs/archive/0.9/installation/index.html?environment=cli&platform=macos) points to Linux CLI regardless of which platform you select (Windows/MacOS/Linux). 

Instead, they should point to
- MacOS: https://github.com/duckdb/duckdb/releases/download/v0.9.2/duckdb_cli-osx-universal.zip
- Windows: https://github.com/duckdb/duckdb/releases/download/v0.9.2/duckdb_cli-windows-amd64.zip

**Comment by szarnyasg** [comment]
Thanks @jeewonhh. The likely resolution for this will be to delete the old installation pages as now – since we are backwards compatible – we'll recommend our users to the latest stable version of DuckDB.

**Comment by szarnyasg** [comment]
Scratch that – this turned out to be reasonably easy to fix, so I opened a PR to fix the old installation pages.
