### ISSUE TITLE
Issue found on page 'Schema'

### ISSUE THREAD

**Issue by PeiMu** [duckdb/duckdb-web#2550]
The last sub-section in the `Schema` page is: `Microbenchmark: The Effect of Primary Keys`. But it seems only to mention the loading time with primary keys. Users might be more interested in end-to-end execution time. E.g. if adding primary keys and foreign keys will affect the end-to-end execution time?

Page URL: <https://duckdb.org/docs/guides/performance/schema.html>

**Comment by szarnyasg** [comment]
Hi @PeiMu, that's a great question and I can see how this is not clear from the text. I'll make some adjustments.
