### ISSUE TITLE
[Python] document how to apply configuration options with `config` param for `connect()`

### ISSUE THREAD

**Issue by ned2** [duckdb/duckdb-web#2586]
For user interacting with the Python client, I don't believe there's any explicit mention of how to set DuckDB configuration options when creating a new DB connection. 

The [Python Client overview page](https://duckdb.org/docs/api/python/overview.html) mentions that `config = {"allow_unsigned_extensions": "true"}` can be used for loading unsigned extensions, but folks who are not yet aware of the [configuration machinery](https://duckdb.org/docs/configuration/overview.html), will likely be left guessing what other available keys/values can be supplied in the `config` dictionary.

I also see that the `config` param is obliquely mentioned in the Python API reference page in the `connect` method's signature, but there's no further context provided here either.

Perhaps it would be good to add a brief section in the Python client overview page explaining that the `config` param can be used to set DuckDB configuration options for the connection being created, and linking to the main configuration page for a guide to available options that can be supplied?

**Comment by szarnyasg** [comment]
Hi @ned2, that's an excellent point. I added an example.
