### ISSUE TITLE
Sync list_slice documentation with changes introduced after 0.8.0

### ISSUE THREAD

**Issue by taniabogatsch** [duckdb/duckdb-web#2655]
Changes introduces by https://github.com/duckdb/duckdb/pull/8087.

> As per issue https://github.com/duckdb/duckdb/issues/3176, slicing in DuckDB used NULL as the unbounded marker, which was not compatible with Postgres, which returns NULL if the lower or upper bound is NULL.

Related issue: https://github.com/duckdb/duckdb/issues/11431
Related link to the documentation: https://duckdb.org/docs/sql/functions/char.html#array_slicelist-begin-end

**Comment by szarnyasg** [comment]
@taniabogatsch thanks, I'll change the example.
