### ISSUE TITLE
Performance guideline

### ISSUE THREAD

**Issue by PeiMu** [duckdb/duckdb-web#2682]
Hi!

I've read these pages:
https://duckdb.org/docs/guides/performance/environment
https://duckdb.org/docs/guides/performance/my_workload_is_slow
https://duckdb.org/docs/guides/performance/how_to_tune_workloads
https://duckdb.org/docs/guides/performance/benchmarks
https://duckdb.org/docs/api/cli/overview

But still didn't have a very clear understanding of how to have a fair and best performance, e.g. when benchmarking by CLI in the in-memory mode. So maybe it's necessary to have a performance guideline?

The following are my issues.

My current experiment is running the JOB benchmark and JCC-H benchmark. I'm using CLI. To avoid loading the dataset many times which costs a lot of time, I load the necessary tables to a temporary file on disk. Then run by `.read` command.

```bash
rm -f ./imdb.db

# create schema
echo "create imdb schema"
echo -ne ".read imdb_schema.sql" | duckdb ./imdb.db

# load imdb
for table in name aka_name kind_type title aka_title char_name role_type cast_info comp_cast_type company_name company_type complete_cast info_type keyword link_type movie_companies movie_info movie_info_idx movie_keyword movie_link person_info
do
  echo "duckdb load table from ${table}.tbl"
  command="copy ${table} from '/home/pei/Project/benchmarks/imdb_job-postgres/csv/${table}.csv' (quote '\"', escape '\\');"
  echo $command
  echo -ne "${command}" | duckdb ./imdb.db
done

# execute queries
dir="/home/pei/Project/benchmarks/imdb_job-postgres/skinner_explained"
iteration=10

rm -rf job_result/
mkdir -p job_result/

for i in $(eval echo {1.."${iteration}"}); do
  for sql in "${dir}"/*; do
    echo "execute ${sql}" 2>&1|tee -a skinner_explained_imdb_${i}.txt;
    echo -ne ".read ${sql}" | duckdb ./imdb.db 2>&1|tee -a skinner_explained_imdb_${i}.txt;
  done
done
```

Do you think this is the appropriate way to get the best performance of duckdb? Do I need some extra configuration? Can I use in-memory mode in this way?

Thanks ahead!

**Comment by szarnyasg** [comment]
Hi @PeiMu, thanks for reaching out. It's not clear to me whether you would like to use in-memory mode (in which case there is no on-disk database available): your post both refers to "when benchmarking by CLI in the in-memory mode" but also states "load the necessary tables to a temporary file on disk". Would you like to run in in-memory mode or using a persistent on-disk database?

**Comment by PeiMu** [comment]
Hi @szarnyasg , thank you for the reply!

I think I got the misunderstanding here. Previously, I thought I could have both the benefits of in-memory efficiency and getting rid of the time consumption to load data. So it seems I need to choose one of them but cannot enjoy them at the same time, right?

If that is the case, the in-memory feature will be more important! So I just load tables from csv files but no longer need the db name (e.g. `imdb.db` in my code). That is `echo -ne "${command}" | duckdb` only. Am I correct here?

Other than this, do you think anything else I did in a stupid way?

Thank you!

**Comment by szarnyasg** [comment]
> I think I got the misunderstanding here. Previously, I thought I could have both the benefits of in-memory efficiency and getting rid of the time consumption to load data. So it seems I need to choose one of them but cannot enjoy them at the same time, right?

Correct but using an on-disk storage will not slow things down much - DuckDB heavily caches the data and does not reach the disk unless it needs to fetch new data, write data out, or spill to disk.

That said, there is an important thing to consider. For the caching to have an effect, you have stay in the same process. Repeatedly invoking DuckDB via `echo -ne "${command}" | duckdb` starts a completely new DuckDB Instance with cold caches. So my recommendation would be to either have a single SQL script that you read from DuckDB using the `.read my_script.sql>` command. In this case, timings can be provided via the `.timer on` command. Alternatively – and this is what I'd recommend – run DuckDB from Python where it's simple to add loops and a bit of instrumentation for the timing. HTH.

**Comment by PeiMu** [comment]
Great! Thank you so much for your kind help!

**Comment by PeiMu** [comment]
Hi @szarnyasg 

Many thanks for your previous help. 

I tried to write a python script to measure, but it couldn't work yet. Do you have a sample code to share?

I'm now using the in_memory mode with `.timer on`. And I got logs like `Run Time (s): real 0.226 user 1.686918 sys 0.239495`. From what I learned from here (https://stackoverflow.com/questions/556405/what-do-real-user-and-sys-mean-in-the-output-of-time1), `user+sys` is the actual CPU consumption time. Besides, I used a `clock()` function and the beginning and the end of `main()` in `shell.c` to confirm the time. From the logs, the `user+sys` time matched the `clock()` time.

But considering I'm using 12 threads by default, I guess it makes more sense to use `real` time? Even though it doesn't match the `clock()` numbers, which I'm quite confused.

Can you please help?

Thanks,
Pei

**Comment by szarnyasg** [comment]
Hi @PeiMu taking the beginning and end using the `clock()` function should match the `real` field's output of the run time, which is the wall clock time. So this is indeed quite confusing.

I recently ran some microbenchmarks on the command line DuckDB client. I used the [hyperfine command line benchmarking tool](https://github.com/sharkdp/hyperfine), which I can fully recommend. See my script: [`grep-vs-duckdb-microbenchmark.sh`](https://github.com/duckdb/duckdb-web/blob/main/microbenchmarks/grep-vs-duckdb-microbenchmark.sh)

**Comment by PeiMu** [comment]
> Taking the beginning and end using the clock() function should match the real field's output of the run time, which is the wall clock time. So this is indeed quite confusing.

Yeah, that's what I expected but confused me. 
Here's my code:
![image](https://github.com/duckdb/duckdb-web/assets/10811136/a71ed3b0-a3f0-4458-92c1-baa57ab79045)
![image](https://github.com/duckdb/duckdb-web/assets/10811136/5b0c52e3-72ce-4dd4-a7fd-545bd1f343a3)
You can also find them in https://github.com/PeiMu/duckdb/blob/query_split/tools/shell/shell.c#L20629C1-L20631C62

> I recently ran some microbenchmarks on the command line DuckDB client. I used the [hyperfine command line benchmarking tool](https://github.com/sharkdp/hyperfine), which I can fully recommend. See my script: [grep-vs-duckdb-microbenchmark.sh](https://github.com/duckdb/duckdb-web/blob/main/microbenchmarks/grep-vs-duckdb-microbenchmark.sh)

Great! That's amazing! 

Thank you!
