### ISSUE TITLE
potentially spurious /docs/tests/ pages appearing in web search results

### ISSUE THREAD

**Issue by ned2** [duckdb/duckdb-web#2714]
I went web searching *duckdb string functions* with the goal of finding the most relevant DuckDB docs page quickly, and it surfaced what might be an old page. It's titled *String Functions*, when the actual page in the docs is now called *Text Functions*, and seems to have an out of date set of functions. It occurs under the URL prefix `/docs/tests/`. I found a bunch of other similar endpoints that look like they could also be outdated. 

Wondering if these should be either removed or at least de-indexed from web crawlers?

Page URLs: 
* <https://duckdb.org/docs/test/functions/char.html>
* <https://duckdb.org/docs/test/functions/nested.html>
* <https://duckdb.org/docs/test/functions/date>
* etc...

**Comment by szarnyasg** [comment]
@ned2 thanks, we removed the test pages.
