### ISSUE TITLE
Highlighting inconsistencies for some of the types.

### ISSUE THREAD

**Issue by Giorgi** [duckdb/duckdb-web#2726]
`duckdb_uhugeint`, `duckdb_decimal` and `duckdb_string` are not highlighted: 

https://duckdb.org/docs/api/c/api#safe-fetch-functions

![image](https://github.com/duckdb/duckdb-web/assets/580749/45c1cf3c-89d5-4c8b-8ac7-52eff314e91c)

**Comment by szarnyasg** [comment]
Hi @Giorgi, indeed these are off. I'll update the syntax highlighter part of the generation script.
