### ISSUE TITLE
Add MSVC dependency to installation page

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb-web#2730]
Raised by @Giorgi on Discord:

> https://duckdb.org/docs/api/python/known_issues#error-when-importing-the-duckdb-python-package-on-windows the Python on Windows [...] requires  Microsoft Visual C++ Redistributable package.
>
> The dotnet library users on Windows also need to install it
>
> I think it will be better to move that note (or copy) from Python package docs to the DuckDB Installation page when Windows is selected as a Platform.

**Comment by Mause** [comment]
@szarnyasg your pr hasn't quite fixed the issue here, so I've reopened it

**Comment by szarnyasg** [comment]
@Mause can you please elaborate? We don't have a documentation / installation page on the .NET driver so I cannot include this information there.
I'd like to leave the error message in the [known Python issues](https://duckdb.org/docs/api/python/known_issues.html#error-when-importing-the-duckdb-python-package-on-windows) page as people end up there from search engines.

**Comment by Mause** [comment]
> I think it will be better to move that note (or copy) from Python package docs to the DuckDB Installation page when Windows is selected as a Platform.

The library is required on windows regardless of binding I believe

**Comment by Giorgi** [comment]
The MSVC dependency isn't Python specific, it's Windows specific, so I think the note should also be present on the [DuckDB Installation](https://duckdb.org/docs/installation/?version=stable&environment=cli&platform=win&download_method=package_manager) page.

**Comment by szarnyasg** [comment]
Thanks both!
