### ISSUE TITLE
Add "Show source" link on documentation pages

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb-web#274]
For the documentation of the latest version, a "show source" link is an easy way to tell users where the source of the documentation lives, and also to encourage contributions. Should be easy enough to add to https://github.com/duckdb/duckdb-web/blob/master/_layouts/docu.html .

Examples: See the "Source" link at the top of https://dplyr.tidyverse.org/reference/arrange.html or https://dplyr.tidyverse.org/articles/grouping.html .

**Comment by Alex-Monahan** [comment]
Love this idea! Let's get more folks involved.

**Comment by krlmlr** [comment]
Thanks. I took a look at the layout, a good place would be next to the "version" selector? I don't feel comfortable tinkering with the layout, the Jekyll code could be something like:

```html
Source: <a href='https://github.com/duckdb/duckdb-web/tree/master/docs/{{ basename }}'>{{ basename }}</a>
```

**Comment by Mause** [comment]
I'd be happy with that location? We can definitely see how it looks and tweak it later if desired

**Comment by Alex-Monahan** [comment]
Sure! Maybe "Docs Source" for the link text? DWe don't want to confuse folks that may be looking for the DuckDB core source.

**Comment by carlopi** [comment]
If someone gets to this at some point, an option is also adding just a grey pencil symbol (SVG?), that on clicks redirects to the GitHub page (plus on hover ideally becomes more visible / has explanation like "Improve this page...")

**Comment by Mause** [comment]
Fixed in https://github.com/duckdb/duckdb-web/pull/1093
