### ISSUE TITLE
`json_type` function can also return `DOUBLE`

### ISSUE THREAD

**Issue by zenazn** [duckdb/duckdb-web#2762]
`json_type(...)` is documented as follows:
<img width="987" alt="Screenshot 2024-04-23 at 3 22 05 PM" src="https://github.com/duckdb/duckdb-web/assets/12960/7536075e-4dd0-4807-840f-30b5dfec0a99">

But:
```
D SELECT json_type('1.23'::JSON);
┌───────────────────────────────────┐
│ json_type(CAST('1.23' AS "JSON")) │
│              varchar              │
├───────────────────────────────────┤
│ DOUBLE                            │
└───────────────────────────────────┘
```

**Comment by szarnyasg** [comment]
@zenazn thanks, a fix is on its way.
