### ISSUE TITLE
Inconsistency in the Casting Operation Matrix?

### ISSUE THREAD

**Issue by vlulla** [duckdb/duckdb-web#2791]
How should I read the table/figure listed at <https://duckdb.org/docs/sql/data_types/typecasting#casting-operations-matrix>? It appears that reading the cell at R1C1 the rows ought to be read as `from` type and the columns ought to be read as `to` type. But that does not make sense, at least to me. For instance, typing `select '10' > 9` in duckdb will print `true` indicating that the left operand has been _implicitly typecast_ from `varchar` to `int`. So, shouldn't the `varchar` column be transposed? I.e., all values _from_ `varchar` _can be implicitly_ converted to other types! By the way, this implicit conversion of string literal to _any_ other type is mentioned explicitly at <https://duckdb.org/docs/sql/data_types/literal_types#string-literals>. I find this figure a little confusing and am wondering if it cannot be fixed up to be more precise. Regardless, thanks for all the good work on duckdb documentation!

**Comment by soerenwolfers** [comment]
More casting quirks that should be fixed or documented in this page:
https://github.com/duckdb/duckdb/issues/11958
https://github.com/duckdb/duckdb/issues/13847
