### ISSUE TITLE
Switch to nightly.link for master builds 

### ISSUE THREAD

**Issue by Mause** [duckdb/duckdb-web#281]
Much more user friendly as it allows us to link directly to the most recent artifacts

Eg https://nightly.link/duckdb/duckdb/workflows/LinuxRelease/master

**Comment by Mause** [comment]
@Alex-Monahan what do you think?

**Comment by Alex-Monahan** [comment]
Seems really helpful! I typically am using the pip install pre or the npm equivalent, but this looks great for the other cases!

**Comment by Mause** [comment]
@carlopi can probably repurpose this old issue to switch to your nicer hosting/links for nightlies

**Comment by szarnyasg** [comment]
PR #1030 already fixed this issue. I put this in one of the comments but should have done that in the top post.
