### ISSUE TITLE
Typo in page 'Timestamp Types'

### ISSUE THREAD

**Issue by bouvierr** [duckdb/duckdb-web#2838]
Page URL: <https://duckdb.org/docs/sql/data_types/timestamp.html>

Repeated word "ingestion" in this sentence:

> When defining timestamps using a TIMESTAMP_NS literal, the decimal places beyond microseconds are ignored. Note that the TIMESTAMP_NS type is able to hold nanoseconds when created e.g. via ingestion the ingestion of Parquet files.

**Comment by szarnyasg** [comment]
Thanks!
