### ISSUE TITLE
Regex docs do not cover 'options' argument

### ISSUE THREAD

**Issue by david-cortes** [duckdb/duckdb-web#2855]
DuckDB's regex functions usually take an optional "options" argument, but it is not described what kind of options are supported or how to pass them.

The regex docs do not contain example usages either:
https://duckdb.org/docs/sql/functions/regular_expressions.html

They mention:
> For the regular expression syntax, see the [RE2 docs](https://github.com/google/re2/wiki/Syntax).

But this link does not describe the "options".

Browsing their repository, they seem to redirect the user to the header "re2.h", but this header lists the options as structs, so one would not know from looking at it that an option like "global" needs to passed as "g", for example.

**Comment by szarnyasg** [comment]
Hi @david-cortes, that's a good point. I added links to the options section from each regex function.
