### ISSUE TITLE
Issue found on page 'Full-Text Search Extension'

### ISSUE THREAD

**Issue by tandr-ssn** [duckdb/duckdb-web#2857]
Page URL: <https://duckdb.org/docs/extensions/full_text_search.html>

Windows 10 Pro , Edge Version 124.0.2478.80 (Official build) (64-bit)

Entry table for [PRAGMA create_fts_index](https://duckdb.org/docs/extensions/full_text_search.html#pragma-create_fts_index) is messed up.

![image](https://github.com/duckdb/duckdb-web/assets/120140905/bc44d75d-b787-432e-871e-8c54eb100b92)

**Comment by szarnyasg** [comment]
@tandr-ssn, thanks, this is indeed off. A fix is on its way.
