### ISSUE TITLE
none compression for json auto not working

### ISSUE THREAD

**Issue by bgadrian** [duckdb/duckdb-web#2868]
Hello, I am not sure if this is a BUG or a documentation problem.

According to https://duckdb.org/docs/data/json/overview 

> The compression type for the file. By default this will be detected automatically from the file extension (e.g., t.json.gz will use gzip, t.json will use none). Options are 'none', 'gzip', 'zstd', and 'auto'.

But when explicitly specify the value none results in a fatal error with any json

```bash
CONTENT=$(cat <<<{"whatever":1}

)
echo "$CONTENT" | duckdb -c "SELECT * FROM read_json_auto('/dev/stdin',compression='none')"
```

result:

```
'Not implemented Error: Enum value: 'NONE' not implemented'
```

**Comment by szarnyasg** [comment]
Hi @bgadrian, thanks for reporting this. This was indeed incorrect. I submitted a fix.
