### ISSUE TITLE
Issue found on page Excel Export

### ISSUE THREAD

**Issue by tonne1** [duckdb/duckdb-web#2914]
In section [Exporting Excel Sheets](https://duckdb.org/docs/guides/file_formats/excel_export#exporting-excel-sheets) there is a box stating a warning which seems to be outdated:

"The output file must not already exist."

I have no problems to export to an existing excel file, it simply gets replaced.

**Comment by szarnyasg** [comment]
Thanks, indeed this needs to be fixed. A PR is on its way.
