### ISSUE TITLE
Document new pragma's (eg, enable_verification)

### ISSUE THREAD

**Issue by Mause** [duckdb/duckdb-web#300]
From Tishj's comment below

 - [x] verify_external
 - [x] disable_verify_external
 - [x] verify_serializer
 - [x] disable_verify_serializer
 - [x] disable_object_cache
 - [x] force_checkpoint
 - [x] enable_print_progress_bar
 - [x] disable_print_progress_bar
 - [x] enable_checkpoint_on_shutdown
 - [x] disable_checkpoint_on_shutdown
 - [x] show_tables_expanded
 - [x] functions
 - [x] enable_object_cache - is documented, but not as part of pragmas, instead it's documented in configuration
 - [x] disable_progress_bar - is not mentioned anywhere, but it's existence might not need to be explicit
 - [x] progress_bar_time

**Comment by Tishj** [comment]
To add to this: we should also document the pragma functions, such as `pragma_table_info`

**Comment by Tishj** [comment]
There are a couple I missed, as they are in `settings.hpp`
Among which are:
- `progress_bar_time`
