### ISSUE TITLE
Clarify the meaning of max_temp_directory_size

### ISSUE THREAD

**Issue by jhrcek** [duckdb/duckdb-web#3058]
Hello,
could you please clarify the meaning of `max_temp_directory_size` mentioned [here](https://duckdb.org/docs/configuration/overview#global-configuration-options)?

I see the default size is 0. But it's not clear to me whether this default setting means "there's no limit" or "the limit is 0, if you want to enable offloading to disk, you have to set it to >0".

**Comment by Tishj** [comment]
Thanks for opening the issue, I agree this is something we should document
<https://github.com/duckdb/duckdb/pull/10978> is the source for this option

**Comment by jhrcek** [comment]
Thank you for the reference PR, the description answers most of my questions for now.
