### ISSUE TITLE
Issue found on page 'Regular Expressions'

### ISSUE THREAD

**Issue by Veldbloemen33** [duckdb/duckdb-web#3103]
Page URL: <https://duckdb.org/docs/sql/functions/regular_expressions.html>

Reader see example and comment.

regexp_split_to_table(string, regex[, options])

Description	Splits the string along the regex and returns a row for each part. A set of optional *options* can be set.

>>>>> Example	regexp_split_to_array('hello world; 42', ';? ') -_> must this not be ?  regexp_split_to_table('hello world; 42', ';? ')_ 

Result	Two rows: 'hello', 'world'

**Comment by szarnyasg** [comment]
Hi, thanks, indeed this was off due to a copy-paste error. I submitted a PR which also fixes the output.
