### ISSUE TITLE
使用drop table 之后磁盘的物理内存没有释放

### ISSUE THREAD

**Issue by TomJack2020** [duckdb/duckdb-web#3111]
当使用drop table 之后物理内存没有得到释放，这样无限制的使用会导致磁盘爆掉

**Comment by szarnyasg** [comment]
Hi, this limitation is documented here: https://duckdb.org/docs/sql/statements/drop#limitations-on-reclaiming-disk-space

You may try to run a [`CHECKPOINT` statement to reclaim space](https://duckdb.org/docs/sql/statements/checkpoint#reclaiming-space).
