### ISSUE TITLE
DuckDB read_csv documentation has 'skip' instead of 'skiprows'

### ISSUE THREAD

**Issue by bskubi** [duckdb/duckdb-web#3226]
The DuckDB csv [overview](https://duckdb.org/docs/data/csv/overview) page says to use the 'skip' parameter to skip rows, but the actual parameter to use appears to be 'skiprows'. Also, there appears to be no 'columns' argument, nor a 'types' argument, but instead you can specify the 'names' and 'dtype' arguments.

**Comment by szarnyasg** [comment]
Hi @bskubi, I think you are referring to the Python API. In SQL, `skip` and `columns` work fine:

```sql
from read_csv('my.csv', skip = 1, columns = {'x': 'BIGINT'});
```
```text
┌───────┐
│   x   │
│ int64 │
├───────┤
│     1 │
│     2 │
│     3 │
│     4 │
└───────┘
```
