### ISSUE TITLE
Failed to connect duckdb to Go

### ISSUE THREAD

**Issue by makoto20240703** [duckdb/duckdb-web#3235]
I am using duckdb+Python.
I followed the manual to connect to Go,
but I cannot connect duckdb to Go.
The OS is Windows and the Go version is go1.22.4.
I was able to create a mod file and run/compile it to connect Go to Sqlite3 and postgresql,
but Go + duckDb is not working.
Can someone tell me how to solve this?
The Go code is available on the official website.

**Comment by Mause** [comment]
What error are you getting?
