### ISSUE TITLE
Document order preservation

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb-web#3249]
Given e.g. https://github.com/duckdb/duckdb/discussions/12882 it seems that it is unclear what the guarantees are that DuckDB provides around preserving the order of rows. Since we have actually spent some time making sure DuckDB is order-preserving in many scenarios we should document this behavior.

**Comment by szarnyasg** [comment]
Documentation on this should go under https://duckdb.org/docs/sql/dialect/order_preservation, which currently has minimal content.
