### ISSUE TITLE
Issue found on page 'CSV Import': CSV reader returns rows in order of lines in the file. This is important information that should be documented.

### ISSUE THREAD

**Issue by rpbouman** [duckdb/duckdb-web#3266]
I was doing some work with the CSV reader and suddenly realized I don't know whether it guarantees whether it returns the rows in order of the physical order of lines in the file.

I checked with @pdet and he confirmed that it does - which is great news!

I think this information should be in the CSV reader reference as it can greatly simplify certain types of queries and use cases.
The discussion is here for reference:

https://github.com/duckdb/duckdb/discussions/12882,

I can pick up this issue and close the discussion when it lands in the docs.

Page URL: <https://duckdb.org/docs/data/csv/overview.html>

**Comment by szarnyasg** [comment]
Thanks, @rpbouman! One remark: this is closely related to #3249

**Comment by rpbouman** [comment]
Indeed! It's the same thing - thanks for pointing it out.

I'll write some text and send a PR, and once that's accepted we can close them all.
(I don't know how to formally link issues in gh but the link is good enough for now to track it I think, I won't let it linger for very long.)
