### ISSUE TITLE
Issue found on page 'Star Expression' - contradiction on where COLUMNS may be used.

### ISSUE THREAD

**Issue by rpbouman** [duckdb/duckdb-web#3288]
In https://duckdb.org/docs/sql/expressions/star#columns-expression , it reads:

> The COLUMNS expression can be used to execute the same expression on multiple columns. Like the * expression, it can only be used in the SELECT clause.

And then later, in the same section:

> COLUMNS expressions can also be used in WHERE clauses. The conditions are applied to all columns and are combined using the logical AND operator.

"only in the SELECT clause" and "also in the WHERE clause" sounds like an obvious contradiction.

**Comment by szarnyasg** [comment]
Indeed that's an error in the text. Fix incoming.
