### ISSUE TITLE
Issue found on page 'Samples'

### ISSUE THREAD

**Issue by tomsing1** [duckdb/duckdb-web#3316]
I think some of the percentages of the sampled rows might be wrong in the last 3 examples:

The text claims that 20% of the rows are sampled, but the code requests 10%:
```
Select a sample of 20% of the table using system sampling with a fixed seed (377):
SELECT * FROM tbl USING SAMPLE 10% (system, 377);
```

Conversely, this description states that 10% are sampled, but the code retrieves 20%:
```
Select a sample of 10% of tbl before the join with tbl2:
SELECT * FROM tbl TABLESAMPLE reservoir(20%), tbl2 WHERE tbl.i = tbl2.i;
```

as does this one: 
```
Select a sample of 10% of tbl after the join with tbl2:
SELECT * FROM tbl, tbl2 WHERE tbl.i = tbl2.i USING SAMPLE reservoir(20%);
```

Page URL: <https://duckdb.org/docs/sql/samples.html>

**Comment by szarnyasg** [comment]
Thanks, these were indeed off. I submitted a fix.
