### ISSUE TITLE
Mention that tables can be selected as a STRUCT when using the table name in the select clause

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb-web#3339]
I think it could have a place here: <https://duckdb.org/docs/sql/statements/select#examples>

An example of the functionality I'm referring to (does not need to be the final example used)
```sql
select d From (select 1 as a, 2 as b) d;
```
Becoming:
```
{'a': 1, 'b': 2} 
```

**Comment by Tishj** [comment]
Teggy:
> Technically, you are not „naming a table“ but you are referring to a row variable ranging over table d. This is standard SQL behavior since forever™️.

**Comment by rpbouman** [comment]
> Teggy:
> 
> > Technically, you are not „naming a table“ but you are referring to a row variable ranging over table d. This is standard SQL behavior since forever™️.

I think the SQL standard syntax construct is called `<row value expression>`. 

Although defined by the SQL standard, it is not a common feature in many SQL implementations. For example, going by SQL fiddle (https://sqlfiddle.com/), testing this statement:

`SELECT p FROM Product AS p`

we get:
MS SQL Server: 

> Msg 207, Level 16, State 1, Server 1f4a782fe066, Line 15
> Invalid column name 'p'.

Sqlite:

> Error: near line 15: no such column: p

MySQL & MariaDB:

> ERROR 1054 (42S22) at line 13: Unknown column 'p' in 'field list'

Oracle:

> ERROR at line 1:
> ORA-00904: "P": invalid identifier

There's only one product on sqlfiddle that supports it (postgres).

So while postgres users might be familiar with this feature, many users from other RDBMSes are not. I think it would be a useful contribution to the DuckDB Documentation.
Apart from the suggested location in https://duckdb.org/docs/sql/statements/select#examples, I think it would be natural to include it in the "Creating Structs" section on the STRUCT data type page.   https://duckdb.org/docs/sql/data_types/struct#creating-structs

**Comment by szarnyasg** [comment]
This is explained in the [subqueries page](https://duckdb.org/docs/sql/expressions/subqueries.html#returning-each-row-of-the-subquery-as-a-struct) but not in the `SELECT` page.

**Comment by rpbouman** [comment]
It would be really helpful to at least mention and link to that from the STRUCT datatype page (https://duckdb.org/docs/sql/data_types/struct). At least that's where I was looking: how can I instantiate a struct from a select.
