### ISSUE TITLE
Add Observable DuckDB notebook examples to the Guides section in docs

### ISSUE THREAD

**Issue by RandomFractals** [duckdb/duckdb-web#337]
Suggested new docs section: `Observable` or `Observable Notebooks` under https://duckdb.org/docs/guides/index

Would be nice to have this Observable JS notebooks collection listed there. It was created for DuckDB dev community to explore in a browser:

https://observablehq.com/collection/@randomfractals/duckdb

Also, maybe include links to other DuckDB Observable notebooks:

https://observablehq.com/search?query=duckdb&onlyOwner=false

**Comment by szarnyasg** [comment]
Hi, according to our current [Contributor's Guide](https://github.com/duckdb/duckdb-web/blob/main/CONTRIBUTING.md#eligibility), the DuckDB documentation should focus on core DuckDB feature. However, these notebooks would make an excellent addition to the awesome-duckdb repository, so I opened a PR for them: https://github.com/davidgasquez/awesome-duckdb/pull/40
