### ISSUE TITLE
[Docs] Anchor links in docs should be easier to copy

### ISSUE THREAD

**Issue by rmoff** [duckdb/duckdb-web#343]
The docs pages have anchor links which is invaluable (e.g. https://duckdb.org/docs/data/csv#examples), but the default behaviour makes it less easy to copy them. This is because the standard behaviour of clicking on it to change the page URL and thus put the URL in the browser bar to copy doesn't happen. Instead, the URL of the page remains as it was. 

https://user-images.githubusercontent.com/3671582/196922395-95a1cb7d-c7cc-4d12-9963-1cdf931d5886.mp4

It looks like this has been done deliberately: https://github.com/duckdb/duckdb-web/blob/master/js/script.js#L178-L187

This is counter-intuitive as it goes against standard behaviour. 

Whilst the user _can_ right-click on the link to copy it, in the absence of a good reason to deviate I'd suggest the default behaviour is restored: clicking on an anchor link should also change the page URL in the browser.

**Comment by hannes** [comment]
CC @Franz-Kafka

**Comment by Mytherin** [comment]
This should be implemented now
