### ISSUE TITLE
CLI: Add `.singleline` and `.multiline` to the dot command list

### ISSUE THREAD

**Issue by prrao87** [duckdb/duckdb-web#3447]
Hi,

I just tested the CLI's `.singleline` and `.multiline` modes as we're implementing something similar in the Kùzu CLI, and it seems that neither of these dot commands have been documented (at least in the 1.0.0 version).
https://duckdb.org/docs/api/cli/dot_commands

Would be nice to see docs on this, explaining to users that `.multiline` is a useful mode to handle long queries that are hard to manage in a single line (esp. useful when accessing/editing a query via the query history in the shell, as single line mode mashes it all up into one line).

**Comment by szarnyasg** [comment]
Thanks @prrao87, this is a great point! I added the commands in the table.
