### ISSUE TITLE
Issue found on page 'Information Schema': TOC is not readable because the section titles are so long.

### ISSUE THREAD

**Issue by rpbouman** [duckdb/duckdb-web#3463]
The TOC at the right top has a fixed width and on my system, I can read little more than the schema name that prefixes each object - even the window has maximum width:

![image](https://github.com/user-attachments/assets/65b794a5-c5e0-4025-bcd5-9a0c820ae8c8)

Personally, I think it would be better if the titles wouldn't use the qualified objects names. The main section title is already "Information_schema"; I believe that the schema name can be left out in the object section titles, so instead of
`information_schema.columns` one could write `columns`.

Page URL: <https://duckdb.org/docs/sql/meta/information_schema.html>

**Comment by szarnyasg** [comment]
Both this and #3464 are perfectly valid points. A fix is incoming!
