### ISSUE TITLE
Issue found on page 'DuckDB_% Metadata Functions': links to information_schema objects broken

### ISSUE THREAD

**Issue by rpbouman** [duckdb/duckdb-web#3466]
There are a couple of links referring to the information_schema. Unfortunately their anchors (url hash) point to non-existing sections in the information_schema page (i.e. the headings/titles in the information_schema page have changed)  

Page URL: <https://duckdb.org/docs/sql/meta/duckdb_table_functions.html>

**Comment by szarnyasg** [comment]
Thanks, these anchor links tend to break quite easily. Fixed now!
