### ISSUE TITLE
Rework Profiling Docs

### ISSUE THREAD

**Issue by maiadegraaf** [duckdb/duckdb-web#3499]
We should update the docs with all the recent changes around profiling.

Relevant PRs:
- https://github.com/duckdb/duckdb/pull/11101
- https://github.com/duckdb/duckdb/pull/12498
- https://github.com/duckdb/duckdb/pull/13234
- https://github.com/duckdb/duckdb/pull/13354
- https://github.com/duckdb/duckdb/pull/13430
- https://github.com/duckdb/duckdb/pull/13480
- https://github.com/duckdb/duckdb/pull/13497

Relevant Doc Pages
- [Profiling](https://duckdb.org/docs/dev/profiling.html)
- [`EXPLAIN`](https://duckdb.org/docs/guides/meta/explain)
- [`EXPLAIN ANALYZE`](https://duckdb.org/docs/guides/meta/explain_analyze)
- [Profiling Queries Pragmas](https://duckdb.org/docs/configuration/pragmas#profiling-queries)

@taniabogatsch

**Comment by taniabogatsch** [comment]
I agree; maybe @szarnyasg can give input on how to (re?)structure our profiling/`EXPLAIN ANALYZE` documentation? And then this can go live with/around the upcoming release.

**Comment by szarnyasg** [comment]
[This comment](https://github.com/duckdb/duckdb/issues/13195#issuecomment-2256260234) points out that the profiling page should mention the varios `enable_profiling` options.

**Comment by Tishj** [comment]
Was <https://github.com/duckdb/duckdb/pull/13649> already covered?

**Comment by Tishj** [comment]
https://github.com/duckdb/duckdb/pull/13160 might also need to be covered on the C-API page
