### ISSUE TITLE
Issue found on page 'Reading and Writing Parquet Files'

### ISSUE THREAD

**Issue by liquidcarbon** [duckdb/duckdb-web#3502]
I created a [feature request](https://github.com/duckdb/duckdb/discussions/13405) for writing KV metadata through DuckDB.
Turns out this was available, but [not documented](https://github.com/duckdb/duckdb/pull/9126).

Page URL: <https://duckdb.org/docs/data/parquet/overview.html>

**Comment by szarnyasg** [comment]
Hi @liquidcarbon, I added more example on metadata functions to the Parquet docs.

**Comment by liquidcarbon** [comment]
Thank you Gabor! I was looking specifically for examples **writing** Parquet files with metadata.
