### ISSUE TITLE
Undefined behaviour list_sort for STRUCT (at least)

### ISSUE THREAD

**Issue by shoffmeister** [duckdb/duckdb-web#3533]
The documentation for sorting lists at https://duckdb.org/docs/sql/functions/list.html#sorting-lists does not define the behaviour for list entries which are not "plain types".

For instance, the behaviour of sorting a list of `STRUCT` is not defined, but "something" does seem to happen:
```
  with mix as (
  select 10 as j, struct_pack(id:=2, val:='1') as s
  union all
  select 10 as j, struct_pack(id:=1, val:='2') as s
  )
  select j, list_sort(list(s), 'asc') from mix group by j
  ;
```

That "something" also seems to be reproducible in a broader context for `STRUCT`.

It would be lovely if that "seems to work" could be formally defined and documented.

**Comment by Mytherin** [comment]
`list_sort` sorts in the same manner as `ORDER BY`. @szarnyasg perhaps it would be useful to instead document the sorting order of different element types somewhere and have `list_sort` link to that?

**Comment by shoffmeister** [comment]
FWIW, on https://duckdb.org/docs/sql/data_types/struct.html#comparison-operators I see
> Nested types can be compared using all the [comparison operators](https://duckdb.org/docs/sql/expressions/comparison_operators.html)
...
> The ordering is defined positionally in the same way that words can be ordered in a dictionary

I do not understand the above text - I am unable to determine how, specifically,
```
struct_pack(id:=2, val:='1')
```
and
```
struct_pack(id:=1, val:='2')
```
compare.

Enrichment on that end I would welcome very much.

FWIW, my current use case for sorting is a large, very deeply nested type involving list and structs. I "reshape" this into a well-defined order, to enable easy data regression testing (actual vs expected).
