### ISSUE TITLE
[C++] Checking query results for SQL NULL?

### ISSUE THREAD

**Issue by sjaenick** [duckdb/duckdb-web#355]
Hi, 

C++ beginner here, trying to have some fun with DuckDB. Could you document how to properly 
extract the values from a QueryResult, including handling possible SQL NULL values?

For a query returning an INTEGER column, I came up with the following, which most likely
is awfully wrong:

```
    auto stmt = conn.Prepare(sql);
    auto result = stmt->Execute(id);

    if (result->HasError()) {
         cerr << "error " << result->GetError() << endl;
    }
    for (auto &row : *result) {
        // TODO: how to check for SQL NULL values?
        bool isnull = row.GetValue<string>(0) == "NULL";
        int val = isnull ? -1 : row.GetValue<int32_t>(0);
    }
```

**Comment by Mause** [comment]
Have you tried using the `Value#IsNull()` method?

**Comment by sjaenick** [comment]
Indeed, this works:

```
        bool isnull = row.GetValue<Value>(0).IsNull();
        int val = isnull ? -1 : row.GetValue<int32_t>(0);
```

However, I'd like to avoid the duplicate GetValue call.

**Comment by Tishj** [comment]
@sjaenick 
You can look at the CApiTester we use internally for tests
<https://github.com/duckdb/duckdb/blob/942d917145ae4a562b5e3d3649fdabe5ae202305/test/include/capi_tester.hpp>
it has a IsNull function, you can probably rip that code

**Comment by sjaenick** [comment]
Thanks!
