### ISSUE TITLE
Docs default configuration value for `enable_progress_bar` does not match actual from duckdb

### ISSUE THREAD

**Issue by d33bs** [duckdb/duckdb-web#3554]
Thanks for the great work on DuckDB and the docs here! I noticed there's a mismatch with the `enable_progress_bar` value in the docs vs what appears in the actual duckdb install. I tried this out with `duckdb==1.0.0`.

Docs are here: https://duckdb.org/docs/configuration/overview.html
They show `False` as the default value for `enable_progress_bar`.
The default is `True` within duckdb, as exhibited below:

```python
import duckdb

with duckdb.connect() as ddb:
    df = ddb.execute(
        """
    SELECT *
    FROM duckdb_settings();
    """
    ).df()

assert (
    df[df["name"] == "enable_progress_bar"]["value"].values[0] == "false"
), "enable_progress_bar default configuration value is true"
```

I wasn't sure, but maybe this default value came from an earlier version of duckdb. That said, would it be worth exploring versioned documentation if it doesn't already exist for this project to help align documentation with various versions of duckdb (could be another issue)?

**Comment by szarnyasg** [comment]
Hi @d33bs, thanks, you're right – I'm fixing this with PR #3555. 

The reason this is incorrect in the docs is because the configuration options table is auto-generated by piping the output of a duckdb process into a variable. This happens in a Python script but piping in general has the same effect: it changes to a non-interactive mode where there's no progress bar available. See e.g. this:

```
$ duckdb -c "select current_setting('enable_progress_bar') as epb"
┌─────────┐
│   epb   │
│ boolean │
├─────────┤
│ true    │
└─────────┘

$ duckdb -c "select current_setting('enable_progress_bar') as epb" > out.txt; cat out.txt
┌─────────┐
│   epb   │
│ boolean │
├─────────┤
│ false   │
└─────────┘
```

I'll add a manual override for this.

**Comment by d33bs** [comment]
Thank you @szarnyasg for the quick turnaround on this and explanation!

On the later notes from the issue: do you feel it'd be of value to explore versioned documentation for duckdb through another issue? Or has this already been decided elsewhere?

**Comment by szarnyasg** [comment]
@d33bs we do have versioning in the documentation, see the version selector in the top right corner of the pages. So if a configuration option's behavior changes, that shows in the documentation and we generally try to also add notes on this.

One thing where we compromise is that currently we only backport changes to older versions when we find 'critical' documentation issues. As DuckDB is very easy to update (compared to some older DBMSs), most of our users are using one of the latest versions of DuckDB, so this does not cause a big issue.

**Comment by d33bs** [comment]
Thanks again @szarnyasg, sounds good ! Apologies for missing the location of the version selector - I just hadn't noticed where it was on the display.
