### ISSUE TITLE
DuckDB latest binaries not found

### ISSUE THREAD

**Issue by NiclasHaderer** [duckdb/duckdb-web#3563]
I used the following URLs to download the DuckDB latest binaries for [duckman](https://github.com/NiclasHaderer/duckdb-version-manager/). 

However, these two seem to have stopped working:
https://artifacts.duckdb.org/latest/duckdb-binaries-windows.zip
https://artifacts.duckdb.org/latest/duckdb-binaries-osx.zip

While the Linux binaries still work.
https://artifacts.duckdb.org/latest/duckdb-binaries-linux-aarch64.zip
https://artifacts.duckdb.org/latest/duckdb-binaries-linux.zip

I would have moved to the GitHub actions artifacts. However, you cannot download the artifacts of a GitHub action if you are not logged in, which prevents me from downloading them with Duckman.

**Comment by szarnyasg** [comment]
Hi @NiclasHaderer, thanks, we are aware and working on a fix – likely rolled out next week.

**Comment by carlopi** [comment]
@NiclasHaderer: I have an job downloading nightly artifacts from github and storing then as a github-backed page, example: `wget -q https://carlopi.github.io/duckdb-latest/duckdb_cli-osx-universal.zip`, unsure if that could be interesting as a back-up for duckman.

See https://github.com/carlopi/duckdb-latest

**Comment by NiclasHaderer** [comment]
Thank you :) I think I'll just wait for the fix :D

But I love everything about this ;)
> Lawyer says …
> This is a personal project not backed by [DuckDB Labs](https://duckdblabs.org/).
> No guarantees are offered.

**Comment by carlopi** [comment]
They should be back online!

**Comment by NiclasHaderer** [comment]
Can confirm that it is working again. Thanks!
