### ISSUE TITLE
List comprehensions slightly under-documented

### ISSUE THREAD

**Issue by shoffmeister** [duckdb/duckdb-web#3564]
The documentation for list comprehensions at https://duckdb.org/docs/sql/functions/list#list-comprehension exists, essentially by way of saying "Python-style" and providing examples.

This is somewhat sparse, IMHO, and could use more words around the "if" part used for reducing the list.

Even more relevant might be _explicitly_ mentioning that list comprehensions are "just" (very nice!) syntactic sugar on top of lambda functions (https://duckdb.org/docs/sql/functions/lambda.html): The combination of `list_transform` and `list_reduce` is an alternative representation of the list comprehension which helps whenever third-party tooling is not enabled to work with list comprehensions (yet) - see https://github.com/sqlfluff/sqlfluff/issues/6157

**Comment by soerenwolfers** [comment]
Fixed by https://github.com/duckdb/duckdb-web/pull/4198
