### ISSUE TITLE
Missing C++ API docs

### ISSUE THREAD

**Issue by suvayu** [duckdb/duckdb-web#3566]
I'm trying to find the C++ API docs.  But the [C++](https://duckdb.org/docs/api/cpp) page doesn't seem to have/link to any.  Am I missing something?

**Comment by szarnyasg** [comment]
Hi @suvayu, thanks for opening this issue. The C++ API is not a stable API at the moment. I'm clarifying this in #3567.

**Comment by suvayu** [comment]
Thanks for the clarification.  I'll rethink how I want to proceed. :)
