### ISSUE TITLE
`epoch` is not documented

### ISSUE THREAD

**Issue by david-cortes** [duckdb/duckdb-web#360]
From https://github.com/duckdb/duckdb/issues/5167

The docs list timestamp functions:
https://duckdb.org/docs/sql/functions/timestamp

Searching in the issue tracker, there is a function `epoch` which is the inverse of `epoch_ms`: https://github.com/duckdb/duckdb/issues/1920#issuecomment-871978142

But this function is not listed in the docs above.

**Comment by renatocron** [comment]
I'm testing with duckdb 0.8.1, no version that accept timestamp nor timestamptz for epoch_ms, epoch_us or epoch_ns exists

both pages needs to be updated, or there's a bug that only the version that accepts the int64 exists (for epoch_us at least this function exists and is present on auto-complete, epoch_us and epoch_ns do exists at all)
https://duckdb.org/docs/sql/functions/timestamptz 

https://duckdb.org/docs/sql/functions/timestamp

**Comment by hawkfish** [comment]
> the feature was merged on the website after the 0.8.1 release, so maybe that's the reason!

Yes it's my change/feature and it is not released yet. Sorry for the confusion!
