### ISSUE TITLE
v1.0.0 MacOS direct download link wrong

### ISSUE THREAD

**Issue by jgrg** [duckdb/duckdb-web#3606]
If on my Mac (using Safari) I go to the [DuckDB Installation page](https://duckdb.org/docs/installation/?version=stable&environment=cli&platform=macos&download_method=package_manager), select **1.0** from the popup menu and press the **Direct Download** button, it gives the link to v1.1.0 zip archive:

> https://github.com/duckdb/duckdb/releases/download/v1.1.0/duckdb_cli-osx-universal.zip

**Comment by szarnyasg** [comment]
@jgrg thanks this was indeed broken. A fix is on its way.
