### ISSUE TITLE
Table function documentation is broken

### ISSUE THREAD

**Issue by JAicewizard** [duckdb/duckdb-web#3680]
see https://duckdb.org/docs/api/c/table_functions, the function formatting doesn't work

**Comment by szarnyasg** [comment]
Thanks! I'm travelling at the moment so I will take a look later. In the meantime, I recommend using the older version: https://duckdb.org/docs/archive/1.0/api/c/table_functions.

**Comment by szarnyasg** [comment]
This has been fixed since, closing as resolved.
