### ISSUE TITLE
Broken link from create_synthetic_data to range_functions

### ISSUE THREAD

**Issue by paultiq** [duckdb/duckdb-web#3691]
https://duckdb.org/docs/guides/snippets/create_synthetic_data.html links to https://duckdb.org/docs/sql/functions/nested.html#range-functions

nested.html doesn't have range-functions, which now lives at https://duckdb.org/docs/archive/1.0/sql/functions/list.html#range-functions

**Comment by szarnyasg** [comment]
Thanks, this was indeed off. I fixed this along with a bunch of other links to `nested.md`.
