### ISSUE TITLE
Broken Link on the Installation Page 

### ISSUE THREAD

**Issue by sbbhardwa** [duckdb/duckdb-web#3697]
![image](https://github.com/user-attachments/assets/1a7e45da-b02d-49c5-a73b-c9cfeecb3a73)

**Comment by carlopi** [comment]
Links look to be working for me via browser redirect, but as already raised elsewhere, those links do need redirects enabled (say if using them from `wget` or equivalent).

Needs for those will be removed with `v1.1.1`.

**Comment by sbbhardwa** [comment]
Hi @carlopi  , I noticed the link seems broken when you are not signed in your github account . potentially the artifact is behind secure github signed in pages. 

I tried again , if I am logged in into my github it works but won't work if not signed in 
![image](https://github.com/user-attachments/assets/ecdc6ca6-8e6b-4d5a-8377-c4595adf2462)

**Comment by carlopi** [comment]
Thanks, that I had not seen.
I don't think we have a replacement as of now, will need on Monday for release v1.1.1 I guess

**Comment by sbbhardwa** [comment]
Perfect , Thanks a lot for addressing

**Comment by carlopi** [comment]
This has been solved as part of the post v1.1.1 release cleanup, closing
