### ISSUE TITLE
Issue found on page 'SQL Introduction'

### ISSUE THREAD

**Issue by RakeshSeerviAtNoesys** [duckdb/duckdb-web#3698]
> In Updates section the UPDATE query result is same even after decrementing the temp_hi and temp_lo by 2. 
Page URL:  https://duckdb.org/docs/sql/introduction.html#updates

**Comment by RakeshSeerviAtNoesys** [comment]
![image](https://github.com/user-attachments/assets/a98df211-0741-4a72-8aca-99f9c2877511)

**Comment by szarnyasg** [comment]
Thanks, this was indeed off. I pushed a fix.
