### ISSUE TITLE
Issue found on page 'PostgreSQL Compatibility'

### ISSUE THREAD

**Issue by benjaminbauer** [duckdb/duckdb-web#3744]
Page URL: <https://duckdb.org/docs/sql/dialect/postgresql_compatibility.html>

DuckDB does not support `to_date` (https://www.postgresql.org/docs/current/functions-formatting.html). The documentation should reflect that and link to https://duckdb.org/docs/sql/functions/dateformat#strptime-examples.

**Comment by szarnyasg** [comment]
@benjaminbauer thanks for the suggestion, I added this limitation (+workaround) to the Postgres-compatibility page.
