### ISSUE TITLE
Issue found on page 'Loops'

### ISSUE THREAD

**Issue by xuxoramos** [duckdb/duckdb-web#3794]
Under the section [Data Generation without Loops](https://duckdb.org/docs/dev/sqllogictest/loops#data-generation-without-loops), the 2nd example should use the `repeat` function instead of the `range ` function.

Page URL: [<https://duckdb.org/docs/dev/sqllogictest/loops.html>](https://duckdb.org/docs/dev/sqllogictest/loops)

**Comment by szarnyasg** [comment]
Thanks for reporting this, I submitted a fix.
