### ISSUE TITLE
Issue found on page 'Securing Extensions' - Confusing recommendation

### ISSUE THREAD

**Issue by rvsit** [duckdb/duckdb-web#3869]
Dear team,
Under [Disabling Autoinstalling and Autoloading Known Extensions](https://duckdb.org/docs/operations_manual/securing_duckdb/securing_extensions.html#disabling-autoinstalling-and-autoloading-known-extensions) it says:
To disable autoinstalling known extensions, run:
```
SET autoinstall_known_extensions = true;
```
To disable autoloading known extensions, run:
```
SET autoload_known_extensions = true;
```

I think that both of these suggestions are incorrect and they should instead be set to false, not true.

If my assumption there is incorrect I would suggest to make the configuration option more clear what it means.

Thank you for looking into this, Roy

Page URL: <https://duckdb.org/docs/operations_manual/securing_duckdb/securing_extensions.html>

**Comment by szarnyasg** [comment]
Hi @rvsit, thanks for reporting. Indeed this seems to be off. I've submitted a fix.
