### ISSUE TITLE
(minor) inconsistency in docs around regr_slope

### ISSUE THREAD

**Issue by nwoolmer** [duckdb/duckdb-web#3925]
There isn't a real difference in terms of function output, so this is not a practical issue, but docs could match the code!

DuckDB uses the population variance/covariance, not the sample. This aligns with Snowflake docs: https://docs.snowflake.com/en/sql-reference/functions/regr_slope

https://github.com/duckdb/duckdb/blob/10c42435f1805ee4415faa5d6da4943e8c98fa55/src/include/duckdb/core_functions/aggregate/regression/regr_slope.hpp#L1-L4

However, docs say it uses the sample variants.

![image](https://github.com/user-attachments/assets/fa3d33c0-9cf6-4367-845b-e04ff4c2b846)

**Comment by szarnyasg** [comment]
@nwoolmer thanks for reporting this. I'm sending a PR to fix this in a moment.

**Comment by soerenwolfers** [comment]
@nwoolmer The regression slope is independent of whether population or sample scaling is used in the contributing variances. However, the contributing variance functions you quoted here are unambigously computing "sample" variances as can easily be verified. Reverting the changes in https://github.com/duckdb/duckdb-web/issues/5948

**Comment by nwoolmer** [comment]
> @nwoolmer The regression slope is independent of whether population or sample scaling is used in the contributing variances. However, the contributing variance functions you quoted here are unambigously computing "sample" variances as can easily be verified. Reverting the changes in https://github.com/duckdb/duckdb-web/issues/5948

I did not say that those functions were calculating population instead of sample values. I said that `regr_slope` was calculated using population values, which from my reading of the code and its comments, was true. 

The other two functions indeed calculate sample values, and the docs inaccuracy was simply that `regr_slope` does not use them. 

I also noted, as you have, that there is no difference in function output so long as both the numerator and denominator use either sample or population values consistently. And I said it was minor! 

Hopefully that clears things up, unless I have missed something else?

**Comment by soerenwolfers** [comment]
The "Formula" should be understood in a mathematical sense. Since there is no observable difference, it doesn't matter that this is not what the code does. If the formula was changed to `covar_pop(x, y) / var_pop(x)`, the implied `NULL` handling wouldn't be correct (since the denominator here doesn't skip rows where `y` is `NULL`), which is actually an observable difference.

**Comment by nwoolmer** [comment]
I understand the formula, but I don't understand your point. Is something still at issue here?

It seems to me that the original corrective PR  changed the descriptions of the other functions mistakenly, and it wasn't caught in a review until now.

**Comment by soerenwolfers** [comment]
All good
