### ISSUE TITLE
Document `NULL` behavior for `arg_min` and friends, and document `arg_min_null` and friends

### ISSUE THREAD

**Issue by Doekeb** [duckdb/duckdb-web#3985]
I was recently looking for a way to get the entire row corresponding to the maximum of a column. `arg_max` should do the job! But I was surprised to see the following behavior:
```sql
create table foo (a integer, b text);
insert into foo values (1, 'a'), (2, 'b'), (3, null);
select * from foo;
```
```text
┌───────┬─────────┐
│   a   │    b    │
│ int32 │ varchar │
├───────┼─────────┤
│     1 │ a       │
│     2 │ b       │
│     3 │         │
└───────┴─────────┘
```
```sql
select arg_max(columns(*), a) from foo;
```
```text
┌───────┬─────────┐
│   a   │    b    │
│ int32 │ varchar │
├───────┼─────────┤
│     3 │ b       │
└───────┴─────────┘
```
Apparently, even though `3` is the maximum of column `a`, the "ignore `NULL`" behavior of aggregate functions applies even to the first argument of `arg_max`. So really `arg_max(arg, val)` is returning:

> The element of `arg` where `val` is maximized, among rows where both `arg` and `val` are not `NULL`.

And then the expression `arg_max(columns(*), a)` applies said behavior per-column. So really my example is shorthand for
`select arg_max(a, a), arg_max(b, a) from foo;` which is not guaranteed to choose the same row for the two `arg_max`'s. I consider this behavior to be pretty confusing, even if it is technically correct and consistent, so it warrants extra documentation. This also goes for `arg_min` and aliases `argmax`, `argmin`, `argMax`, `argMin`, `max_by`, and `min_by`.

Also, I was made aware in the Discord of the existence of `arg_max_null` and `arg_min_null` which _does_ consistently choose the same row like I originally wanted. For example:
```sql
select arg_max_null(columns(*), a) from foo;
```
```text
┌───────┬─────────┐
│   a   │    b    │
│ int32 │ varchar │
├───────┼─────────┤
│     3 │         │
└───────┴─────────┘
```
But these functions are not in the documentation yet.

**Comment by szarnyasg** [comment]
Hi @Doekeb thanks for raising this. This is indeed a tricky subject and the documentation lacked two key functions. I have added them now via a PR.

**Comment by Doekeb** [comment]
Thanks, @szarnyasg! I also commented on the PR but I think the NULL behavior is actually reversed from what was written in the `_null` versions of the functions:

> | [`arg_max_null(arg, val)`](#arg_max_nullarg-val) | Finds the row with the maximum `val` and calculates the `arg` expression at that row. Rows where the `arg` expression evaluates to `NULL` are ignored. This function is [affected by ordering](#order-by-clause-in-aggregate-functions). |

Rows where the arg expression evaluates to NULL are _not_ ignored (rows where the val expression evaluates to NULL are ignored). e.g.
```sql
D create or replace table foo (arg text, val integer);
D insert into foo values ('a', 4), ('e', null), (null, 9), ('b', 5);
D select * from foo;
┌─────────┬───────┐
│   arg   │  val  │
│ varchar │ int32 │
├─────────┼───────┤
│ a       │     4 │
│ e       │       │
│         │     9 │
│ b       │     5 │
└─────────┴───────┘
D select arg_max(arg, val) from foo;
┌───────────────────┐
│ arg_max(arg, val) │
│      varchar      │
├───────────────────┤
│ b                 │
└───────────────────┘
D select arg_max_null(arg, val) from foo;
┌────────────────────────┐
│ arg_max_null(arg, val) │
│        varchar         │
├────────────────────────┤
│                        │
└────────────────────────┘
```

**Comment by szarnyasg** [comment]
@Doekeb indeed. Thanks for pointing this out, these functions are tricky and I find them quite unintuitive (they are still better than window functions though!). A PR is on its way.
