### ISSUE TITLE
Bug in Colab notebook for the "Efficient SQL on Pandas with DuckDB" blog post

### ISSUE THREAD

**Issue by sscdotopen** [duckdb/duckdb-web#3989]
Hi, 

The colab notebook linked to the [Efficient SQL on Pandas with DuckDB ](https://duckdb.org/2021/05/14/sql-on-pandas.html) throws the following error:

`BinderException: Binder Error: Cannot compare values of type VARCHAR and type DATE - an explicit cast is required`

This is because pandas interprets the `l_shipdate` column of the lineitem relation as a string instead of a date column (and this behavior probably changed recently).

Explicitly casting the column fixes the issue:

`lineitem['l_shipdate'] = pd.to_datetime(lineitem['l_shipdate'])`

**Comment by szarnyasg** [comment]
Hi Sebastian, thanks for pointing this out. I fixed the Colab notebook by adding casts in SQL. See you tomorrow! :)
