### ISSUE TITLE
Unable to install community extensions via Python client following instructions in the doc

### ISSUE THREAD

**Issue by ivanfsimeon** [duckdb/duckdb-web#4031]
I tried to install a community extension via Python following the docs:

con = duckdb.connect()
con.install_extension("h3", respository="community")
con.load_extension("h3")

I am getting this error:
TypeError: install_extension(): incompatible function arguments. The following argument types are supported:
    1. (self: duckdb.duckdb.DuckDBPyConnection, extension: str, *, force_install: bool = False, repository: object = None, repository_url: object = None, version: object = None) -> None

Invoked with: <duckdb.duckdb.DuckDBPyConnection object at 0x0000014D4EEC0870>, 'h3'; kwargs: respository='community'

**Comment by ivanfsimeon** [comment]
Figured it was a typo on the argument, should be repository without an s before the p (docs typo)

**Comment by carlopi** [comment]
Can you possibly file a PR? Thanks

**Comment by Tishj** [comment]
I can't find any mention of `respository` in this repository, please reopen if you can provide a link to the docs that are wrong
