### ISSUE TITLE
Issue found on page 'Order Preservation'

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb-web#4035]
It's quite unclear to me what 

> For many operations, DuckDB preserves the insertion order of rows, similarly to data frame libraries such as Pandas. The following operations and components respect insertion order: The CSV reader

means: A user could be forgiven to conclude from this sentence, e.g., that aggregate functions are fed inputs in the "original table order" (see https://github.com/duckdb/duckdb/issues/14755), that sorting is stable (https://github.com/duckdb/duckdb/discussions/14941), or generally that arbitrarily complex and nested queries on data respects that original order (at least for the CSV reader), none of which I don't believe is the case.

I also wonder why the paragraph starts with "For many operations preserve..." and then ends with "The following operations and components respect ..: `<EXACTLY ONE COMPONENT AND NOT A SINGLE OPERATION>` The CSV reader". 

Page URL: <https://duckdb.org/docs/sql/dialect/order_preservation.html>

**Comment by soerenwolfers** [comment]
@szarnyasg I think this is one of the biggest causes for  confusion about duckdb, so a few words about SQLs general approach and duckdb's actual specific enhancements would be super useful. I can't help out in this case because I genuinely don't know what duckdb's philosophy here is not what the current specifics look like.

**Comment by szarnyasg** [comment]
Hi @soerenwolfers, great point. A fix is coming. Still a lot more could be said about the topic but this quick patch should clarify the topic.
