### ISSUE TITLE
The `COPY ... TO` Options should indicate that some options aren't supported in some formats. 

### ISSUE THREAD

**Issue by kennycarruthers** [duckdb/duckdb-web#4037]
The documentation for `COPY ... TO` Options should indicate that some options might not be available depending on the `FORMAT` being used. 

https://duckdb.org/docs/sql/statements/copy.html#copy--to-options

For example, when `FORMAT = json`, attempting to include the `return_files` option generates a `BinderException` because of an "Unknown option". Including `return_files` when `FORMAT = csv` or `FORMAT = parquet` does not produce any errors. 

When possible, it would be helpful if the documentation indicated which formats support which options (as it does lower down where there are specific sections for `csv`, `json` and `parquet` specific options.

**Comment by soerenwolfers** [comment]
It seems to me that all of these options should be supportable by all formats, so rather than painstakingly documenting current omissions in the matrix, I think you should rather file issues for non-supported options you run into.
