### ISSUE TITLE
Issue found on page 'CSV Import'

### ISSUE THREAD

**Issue by DanCory** [duckdb/duckdb-web#4120]
> Please describe the problem you encountered in the DuckDB documentation and include the "Page URL" link shown below.

The documentation says "delimiter" is a legal parameter to the read_csv function, but it has to be delim or sep.

I found other tickets noting that this was inconsistent between read_csv and COPY, and the documentation notes that read_csv supports all parameters, but copy supports only some parameters. I was using read_csv.

Page URL: <https://duckdb.org/docs/data/csv/overview.html>

**Comment by soerenwolfers** [comment]
Page now says 
. This option is only available in the COPY statement.
