### ISSUE TITLE
Issue found on page 'Spatial Functions'

### ISSUE THREAD

**Issue by arunsworld** [duckdb/duckdb-web#4126]
In documentation example for [ST_Distance_Spheroid](https://duckdb.org/docs/extensions/spatial/functions.html#st_distance_spheroid) the coordinates of JFK are incorrect.

40.6446, 73.7797 should instead be 40.6446, -73.7797

```sql
SELECT st_distance_spheroid(
st_point(40.6446, -73.7797),
st_point(52.3130, 4.7725)
);
----
5863418.7459356235
-- Roughly 5863km!
```

Page URL: <https://duckdb.org/docs/extensions/spatial/functions.html>

**Comment by szarnyasg** [comment]
Thanks!
