### ISSUE TITLE
Python client API text obscured in dark mode

### ISSUE THREAD

**Issue by jogoodma** [duckdb/duckdb-web#4130]
Some of the text on the [Python client API documentation page](https://duckdb.org/docs/api/python/reference/) is obscured in dark mode. The text is white on a white background (below). It happens in Chrome, Firefox, and Safari, but only on this page.

e.g.
![image](https://github.com/user-attachments/assets/8660f243-868a-4bd7-9ae0-717fcc6b63de)

**Comment by szarnyasg** [comment]
Hello, thanks for reporting. This is fixed now: https://duckdb.org/docs/api/python/reference/
