### ISSUE TITLE
Python Execute SQL Suggested Clarification with "Python dataframe"

### ISSUE THREAD

**Issue by d33bs** [duckdb/duckdb-web#424]
Hello - thank you for the amazing work on DuckDB and related documentation found here! I recently noticed a minor issue with some of the documentation and wanted to suggest a correction.

https://duckdb.org/docs/guides/python/execute_sql currently includes the following sentence:
```
Use df if you would like the result to be returned as a Python dataframe instead.
```

This may be improved for clarity with the following (avoiding an implied native Python dataframe format):
```
Use df if you would like the result to be returned as a Python Pandas dataframe instead.
```

Please let me know if you have any questions or if I may clarify the above.

**Comment by lnkuiper** [comment]
Sounds good. Feel free to send a PR if you spot any inaccuracies or anything unclear in our documentation
