### ISSUE TITLE
Add generalized documentation on SQL prepared statement dollar symbol ($1) parameter usage

### ISSUE THREAD

**Issue by d33bs** [duckdb/duckdb-web#429]
Prepared statements with DuckDB clients may use question marks (?) or dollar signs ($1, $2, etc), similar to what's found within the C client documentation ([reference]( https://duckdb.org/docs/api/c/prepared.)). Using the dollar sign notation allows the parameter references to be reused within the SQL statement. Generalized documentation on this topic may assist those making use of DuckDB with other clients, for example with the Python client (where the functionality exists but is not yet documented).

**Comment by szarnyasg** [comment]
See also #767

**Comment by szarnyasg** [comment]
Fixed via #1678
