### ISSUE TITLE
Issue found on page 'JSON Type'

### ISSUE THREAD

**Issue by alastai** [duckdb/duckdb-web#4404]
Page URL: <https://duckdb.org/docs/data/json/json_type.html>

The past participle of the irregular verb "to cast" is "cast", not "casted". This docs page, and probably others, wrongly uses "casted", when it should use "cast" for present and past, as in "has been cast from a string to JSON".

The web page below gives the right recommendation and shows the Google stats that back up the absolute guidance that "casted" should never be used in Modern written English with this meaning. 

<https://writingexplained.org/cast-vs-casted>

"Casted" can be used to mean "assigned a [social] caste", or "having had a plaster cast put on a limb" but that's not what's happening here. I have never seen it used before in CS or software engineering publications.

**Comment by szarnyasg** [comment]
Hi Alastair, thanks! I submitted a fix. It will be deployed in ~10 minutes to the site.
