### ISSUE TITLE
Migrate NodeJS API reference to typescript

### ISSUE THREAD

**Issue by Mause** [duckdb/duckdb-web#454]
We should move to generating the API reference based on the typescript stubs, and include the jsdoc strings there as well (eventually, the NodeJS bindings will be written in typescript and remove some steps here)

**Comment by szarnyasg** [comment]
The node client will move to a new variant, https://github.com/duckdb/duckdb-node-neo. As this issue is targeting the old client, I'm closing this for now, feel free to reopen if it's still something we want to tackle.
