### ISSUE TITLE
Document direct download links for extensions

### ISSUE THREAD

**Issue by danthegoodman1** [duckdb/duckdb-web#474]
For doing something like making a lambda layer, pre-building a container, etc. it's really helpful to pre-download an extension from the domain path `https://extensions.duckdb.org/${REVISION (including "v" prefix)}/${PLATFORM}/${NAME}.duckdb_extension.gz;`

If this could be included under the extensions section, along with the list of `PLATFORMs` that would be very helpful to folks pre-building environments.

Is there a list available right now of the names of the platforms?

_And merry Christmas 🎄_

**Comment by Alex-Monahan** [comment]
This should be closed now! Let me know if something is missing in the merged PR above.
