### ISSUE TITLE
README Documentation for Jekyll Installation

### ISSUE THREAD

**Issue by kvnkho** [duckdb/duckdb-web#488]
Hi friends!

I was contributing a guide on how to use DuckDB with a project I maintain called [Fugue](https://github.com/fugue-project/fugue). The instructions to contribute were great until the portion where I had to build the docs for local testing. I don't have experience with either Ruby or Jekyll, so totally new on that front.

I guess at the minimum, I would appreciate if there were suggested Ruby versions to build this project. I kept getting stuck in some kind of dependency hell, but it's likely my fault. I am also on an M1 Mac, which seems to make things harder. There are a couple of [articles](https://snyk.io/blog/how-to-install-ruby-in-mac-os/) saying not to do `brew install ruby` even. Unfortunately, that's where I started so I think that really screwed up my environment.

The M1 Mac comes with Ruby 2.6, which I am unsure if it can work on this. I couldn't successfully run the `bundler`. I then went to Jekyll docs and tried their [installation](https://jekyllrb.com/docs/installation/macos/), but it seemed too complicated relying on the package manager. Though I can understand if that is indeed best practice. I tried to install stuff with `gem` but it kept going into the Ruby 2.6 folder.

I guess my overall request is if you could point to guides that you think outline how to install Jekyll well. Coming from Python land, this was pretty hard for me.

**Comment by Mause** [comment]
Hi @kvnkho! We do actually have a .ruby-version file in the repo, which most of the ruby version managers will use. I'm not sure if we can really do better than the official installation instructions beyond that though?

**Comment by Alex-Monahan** [comment]
I did not know about that! Is that automatically used when I run `bundler`?

**Comment by kvnkho** [comment]
Ah ok coming from Python, I didn't intend to install the package manager because I was intending to just install this so I didn't want to really bother editing the `.zshrc` file like the [Jekyll installation instructions suggested](https://jekyllrb.com/docs/installation/macos/#step-1-install-homebrew). It felt overkill, but I guess I really need to do it. 

Just one clarification though,  do I install Jekyll separately per their official docs, and then use `bundler`? Or should the bundler be installing Jekyll for me also?

I can give this a solid shot over the weekend and see if I'm able to get it if it helps you. I can document my experience here. I don't mind closing the issue too though if you feel there's not much room to improve the steps.

**Comment by kvnkho** [comment]
Ohh I understand what you mean. I think my issue was straight-up trying to install Jekyll myself and then using `bundler`. I should really be relying on `bundler` with a package manager to do it for me. I was struggling with some dependency hell, and I can see why now. Thanks!

**Comment by Mause** [comment]
> I did not know about that! Is that automatically used when I run `bundler`? 
> 
> If not, maybe we could add a sentence foe how to use it?

No, bundler is for installing ruby packages (gems), not for installing ruby itself

**Comment by Alex-Monahan** [comment]
I think we should be all set here! Feel free to reopen if you have other improvements you recommend @kvnkho!
