### ISSUE TITLE
Change www.duckdb.org to duckdb.org in github

### ISSUE THREAD

**Issue by annainfo** [duckdb/duckdb-web#493]
https://github.com/duckdb/duckdb-web at the right hand it says:

About
DuckDB-Web - Source code of duckdb.org

[www.duckdb.org](https://www.duckdb.org/)

Change the last line to

[duckdb.org](https://duckdb.org/)

**Comment by annainfo** [comment]
Why was that closed?

**Comment by Alex-Monahan** [comment]
> Why was that closed?

Why did you open it in the first place?

**Comment by annainfo** [comment]
> > Why was that closed?
> 
> Why did you open it in the first place?

To have it changed.

**Comment by Mause** [comment]
I'm not sure why you've raised all these cards @annainfo? They're nitpicks at best, and add no real value, as the domain redirects anyway

If you just wanted to contribute to open source documentation, the best thing you can do to get started and provide value is to improve grammar, fix typos, or just fix errors in the content of the documentation
