### ISSUE TITLE
Create a duckDB CMS using DuckDB and store the website content of duckdb.org using that CMS

### ISSUE THREAD

**Issue by annainfo** [duckdb/duckdb-web#494]
A website is a graph, make use of graph database technology for creating the website at https://duckdb.org.

The ISO GPM is stable:
https://www.gqlstandards.org/ July, 2022 – GQL Status Update
"SQL/PGQ is interesting to people focused on GQL because the Graph Pattern Matching (GPM) language in SQL/PGQ is essentially identical to GPM in GQL. Since the technical work on SQL/PGQ is now stable, GPM in GQL is now stable."

**Comment by hannes** [comment]
We are quite happy with our statically generated website.

**Comment by annainfo** [comment]
"hannes closed this as completed" - how that? shouldn't it be "not done"?

**Comment by Alex-Monahan** [comment]
> "hannes closed this as completed" - how that? shouldn't it be "not done"?

That's just the default message.

**Comment by annainfo** [comment]
> We are quite happy with our statically generated website.

1) Who is we?
2) Why is the only message before closing as "completed" referring to the happiness of "we" and not to the unhappiness and damage the flaws of the website create elsewhere?
3) Why do you mention one feature "statically generated" and not other features, e. g. stored in dozens of text files of different formats (md, yml, txt, json, html) and the generated website containing inconsistencies because of that (e.g. different URLs presenting the same content, menu hierarchy different when going different routes) and a large amount of white space, probably also because of that?

With the proposal the data would be stored in the database, getting rid of "md, yml, txt, json, html" and can still be "statically generated" while containing less inconsistencies.

Additionally other people (not included in "we") using DuckDB would have the possibility to run their websites and their data analyses based on the same technology.

**Comment by Alex-Monahan** [comment]
Howdy!

Hannes is the CEO of DuckDBLabs and a co-creator of DuckDB. That is the "we"! 😀

The changes you are proposing sound like a significant amount of work. If you wish to reimplement our website, I suggest that you fork our repo and show us what the completed reimplementation looks like. Please keep in mind that this is open source, so this website is provided as a free service to the community!

Also, would you be able to clarify the benefit a bit more? Portions of our site are automatically generated with Python scripts, but then stored in github as static files for loading speed. I don't see how your approach is superior.
