### ISSUE TITLE
Is there a parameter for wrap?

### ISSUE THREAD

**Issue by kenichiroMori** [duckdb/duckdb-web#500]
I'd like to be able to wrap the query from TERMINAL to show the whole thing when I write it, but I can't?

**Comment by Mause** [comment]
Can you provide a screenshot demonstrating what you mean?

**Comment by kenichiroMori** [comment]
Thank you for your response.

<img width="1058" alt="スクリーンショット_2023_01_20_16_13" src="https://user-images.githubusercontent.com/1147392/213638386-fb4af6a3-2614-4cc1-ac94-55b763af6acb.png">

For example, if I'm writing a query like this, I have to scroll horizontally to see the whole query, so it would be nice if there was a parameter that would wrap it.

**Comment by Mause** [comment]
> Thank you for your response.
> 
> <img width="1058" alt="スクリーンショット_2023_01_20_16_13" src="https://user-images.githubusercontent.com/1147392/213638386-fb4af6a3-2614-4cc1-ac94-55b763af6acb.png">
> 
> For example, if I'm writing a query like this, I have to scroll horizontally to see the whole query, so it would be nice if there was a parameter that would wrap it.

I don't think there is such a parameter presently, as we just use the sqlite3 cli tweaked for DuckDB. I'd recommend using something like DBeaver or DataGrips instead if this is something you absolutely require

**Comment by kenichiroMori** [comment]
Sounds good.
I'll look into other methods, including the one you taught me.
I'll close this issue.
