### ISSUE TITLE
Display page title before 'DuckDB', not after.

### ISSUE THREAD

**Issue by bhch** [duckdb/duckdb-web#510]
Please change the page `<title>` from `DuckDB - {{ page title }}` to `{{ page title }} - DuckDB`. 

Rationale:

When you've got multiple pages of DuckDB docs open in different tabs, the tabs get narrower and the page's actual title gets cut off of the browser tab.  
So, all the tabs just display `"DuckDB"` and it's hard to tell which page is where. To find a particular page, you need to click through several tabs. It gets really tiring after a while.

Please, consider changing this.

**Comment by Mytherin** [comment]
Thanks - good idea. I have implemented it now.

**Comment by bhch** [comment]
@Mytherin  Ah, great! Thank you.
