### ISSUE TITLE
Broken sentence testing page

### ISSUE THREAD

**Issue by Dtenwolde** [duckdb/duckdb-web#520]
Hi, 
On this page https://duckdb.org/dev/testing the final sentence is broken off.
```
DuckDB also has tests for various client connectors. These are generally written
```

 I suppose it happened when splitting the testing documentation up into multiple files. I am not sure what the best place for it is to go, or if the sentence should just be removed entirely.

**Comment by Alex-Monahan** [comment]
Thanks for the report!

I looked through all of the git history, and I don't see where that sentence was ever complete... Unfortunately I do not know enough about DuckDB's testing to finish it! Would someone from the dev team mind taking a peek at this one when you get a chance? Many thanks!
