### ISSUE TITLE
Version railroad diagrams

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb-web#524]
The railroad diagrams for various statements are not versioned, which causes e.g. the [insert docs](https://duckdb.org/docs/archive/0.6.1/sql/statements/insert) for older versions to now show upsert support (that was not there at the time). We should version these as well.

**Comment by szarnyasg** [comment]
For simplicity, we should add a slug (`/dev/`) first, see #960, and then tackle this issue.

**Comment by szarnyasg** [comment]
I've been thinking about this issue. To read the versioned railroad diagram, we need to get the version of the page. This can come from either the URL or from an attribute in the front matter.

It seems that we can reliably fetch the version from the URL with either a regex starting with `^/docs...` that's matching both (e.g.) `/docs/archive/0.9.2/...` and `/docs/dev/`, and also using the existing `urlParts`.
