### ISSUE TITLE
Documentation - Relational API and Pandas - Create a DuckDB relation from a dataframe

### ISSUE THREAD

**Issue by earlev4** [duckdb/duckdb-web#525]
Hi. **Huge thanks to the DuckDB creators and contributors!** 

Under the documentation:  
[Relational API and Pandas](https://duckdb.org/docs/guides/python/relational_api_pandas.html)

[https://github.com/duckdb/duckdb-web/blob/75c91dcc62a28db6337359271f66413029e7258f/docs/archive/0.6.1/guides/python/relational_api_pandas.md](https://github.com/duckdb/duckdb-web/blob/75c91dcc62a28db6337359271f66413029e7258f/docs/archive/0.6.1/guides/python/relational_api_pandas.md)

In the code snippet example:
```python
# create a DuckDB relation from a dataframe
rel = con.df(input_df)
```

Returns the following error:
```python
TypeError: df(): incompatible function arguments. The following argument types are supported:
    1. (self: duckdb.DuckDBPyConnection, *, date_as_object: bool = False) -> pandas.DataFrame
```

I believe the code should be changed to:
```python
# create a DuckDB relation from a dataframe
rel = con.from_df(input_df)
```

Thanks so much!

**Comment by Mause** [comment]
Hi, thanks for raising this issue! If you have time, you're more than welcome to submit a pr fixing this issue

**Comment by earlev4** [comment]
Hi @Mause! PR is submitted. Hopefully, the PR is okay. Thanks so much! 😄

**Comment by Mause** [comment]
Thanks!
