### ISSUE TITLE
Question: Can I use the theme skeleton for my website?

### ISSUE THREAD

**Issue by ceckoslab** [duckdb/duckdb-web#55]
Hello Duck DB team,

I really like the them and I would like to use it in order to build a website of my open source project. I tried to find license notes but I couldn't find any in this repository.

Do you think that I can use this project as boilerplate for my website where I will use only the layout but not the content (text and images).

If yes, then I can perhaps add a link to the original them,

**Comment by hannesmuehleisen** [comment]
Please don't do that. There are tons of Jekyll templates out there, but this one was custom-designed for DuckDB.

**Comment by ceckoslab** [comment]
Thanks @hannesmuehleisen 

I will not use the theme.
