### ISSUE TITLE
Building parquet multi-file dataset : duckdb.InternalException: INTERNAL Error: Comparison on NULL values

### ISSUE THREAD

**Issue by parvizfarnia** [duckdb/duckdb-web#556]
Hello everyone,

Based on the discussion thread here : https://github.com/duckdb/duckdb/discussions/6304 I was advised to create a bug report here.

**My environment:**
```
OS : Windows 11, 64 bits
Python version: 3.10.4 (64 bits)
DuckDB version installed via pip : 0.7.0

```

**Problem description:**
In the most recent version, by using the `COPY` command, one can export the content of a table from a local (persistent) DuckDB database into a directory as multi-file dataset (Parquet format). Something like 

`db_connection.execute("copy mytab to 'D:\\tmp\\parquet_data_dir' (format parquet, partition_by(col1, col2, col3, col4)))`

Now, the problem is that apparently if the first column in the `partition_by` clause (therefore `col1` in the above example) is `NULL`, then we get the following error message : 

`duckdb.InternalException: INTERNAL Error: Comparison on NULL values `

**Test case in order to reproduce the error:**
1) Create the following CSV file which has to be named `mydata.csv` in the directory of your choice which will be the current working directory once you run the Python program. Note that I introduced **intentionally** at the first column (`region_code`) of the first data line (the one after the header line) a NULL value to reproduce the error.

**mydata.csv**
```
region_code;department_code;city_code;sector_code;transaction_value
;D1;C1;S1;100000
R1;D1;C1;;79852
R1;D1;C2;S2;479305
R1;D1;C3;S3;
R1;D2;C4;S1;
R1;D2;C5;S2;200000
R1;D2;C6;S3;897450
R1;D3;C7;S1;99
R1;D4;C8;S2;1478
R2;D5;C9;S3;98712000
R3;D6;C10;S6;
R4;D7;C11;S2;8000
R4;D7;C12;S7;9740
R4;D8;C13;S12;87501
```

Now in the very same directory, create the following Python program. You don't need to change anything in the program, just copy/paste it and save it in a file named `myprog.py`.

**myprog.py**
```
import os
import shutil
import duckdb


def main():
    # Path to the database that will be created in the current directory
    db_file_path = "mydb.duckdb"

    # Path to the CSV file that has also to be put in the current directory
    # and will therefore be imported in our DuckDB database
    data_file_path = "mydata.csv"

    # Path to the directory of Parquet multi-file dataset that the program
    # will create in the very same current working directory.
    parquet_dir_path = "parquet_data"

    # Remove the databse if it already exists
    try:
        file_desc = os.open(db_file_path, os.O_RDONLY)
        os.close(file_desc)
        os.remove(db_file_path)
    except FileNotFoundError:
        pass

    # Remove the Parquet directory if it already exists
    try:
        shutil.rmtree(parquet_dir_path)
    except FileNotFoundError:
        pass

    # Create and connect to a new DuckDB database. The database file is
    # also put in the current working directory.
    db_connection = duckdb.connect(database=db_file_path, read_only=False)

    # Now let's create a table with the same structure as our CSV file
    db_connection.execute(
        "".join(
            [
                "create table mytab(",
                "region_code        varchar, ",
                "department_code    varchar, ",
                "city_code          varchar, ",
                "sector_code        varchar, ",
                "transaction_value  numeric"
                ")",
            ]
        )
    )

    # Import the CSV file into the table that we've just created above.
    db_connection.execute(
        "".join(
            [
                "copy mytab from '",
                data_file_path,
                "' with (",
                "format csv, ",
                "header TRUE, ",
                "NULL '', ",
                "quote '\"', ",
                "delimiter ';'",
                ")"
            ]
        )
    )

    # Finally, let's export the table 'mytab' into a Parquet multi-file dataset
    db_connection.execute(
        "".join(
            [
                "copy mytab to '",
                parquet_dir_path,
                "' (format parquet, partition_by(",
                #
                #
                #
                #
                # And here is where the problem appears, the column 'region_code'
                # in our CSV file is the first column, and at the first
                # row in our CSV file. We introduced intentionally a NULL value for this 
                # column. Because of that, Parquet export fails with the 
                # above-mentioned error message. It seems that the first 
		# column in 'partition_by' clause cannot be NULL.
                "region_code, ",
                #
                #
                #
                #
                "department_code, ",
                "city_code, ",
                "sector_code))"
            ]
        )
    )

    # Closing the connection to the database
    db_connection.close()


if __name__ == "__main__":
    main()

```

When you run the program you will get the following error message: 

`duckdb.InternalException: INTERNAL Error: Comparison on NULL values`

Now go back to the CSV file, **at the first data line**, add some value instead of NULL to the first column, that is, the `region_code`. This time the program works without any problem and the Parquet multi-file dataset (hive-style) is created. Consequently, based on multiple tests that I have done so far, it seems to me that the first column in `partition_by(col1, col2, col3, . . .)` cannot be `NULL`.

I hope the description is clear.

Thanks in advance

**Comment by Mause** [comment]
Can you please create issues in the https://github.com/duckdb/duckdb repository in the future? This issue has nothing to do with the website or docs

**Comment by parvizfarnia** [comment]
I am so sorry for my mistake. Thanks for the remark.
