### ISSUE TITLE
Document SQL function `glob`.

### ISSUE THREAD

**Issue by redviking1** [duckdb/duckdb-web#560]
Please document the SQL function `glob`.  Documentation for this function is missing from the SQL documentation on the DuckDB website.

**Comment by Alex-Monahan** [comment]
Let me know if you have any feedback on this!

**Comment by redviking1** [comment]
Would it be worthwhile to mention explicitly that `glob(*)` omits directory names?  Your description states that it returns a column of "filenames", but some (like me) may interpret "filenames" to also include directory names.
