### ISSUE TITLE
Add DuckDB Sql Tools VSCode extension page to SQL Editors

### ISSUE THREAD

**Issue by RandomFractals** [duckdb/duckdb-web#565]
per this discussion with @Alex-Monahan on twitter: https://twitter.com/TarasNovak/status/1620758669960052742

Extension info page in VSCode marketplace: https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.duckdb-sql-tools

Extension documentation repository: https://github.com/RandomFractals/duckdb-sql-tools

**Comment by Alex-Monahan** [comment]
Adding to my todo list! Thanks!

**Comment by RandomFractals** [comment]
@Alex-Monahan sounds good. I'll draft a copy of that page in my fork of duckdb-web to get it started.
