### ISSUE TITLE
Improve documentation of difference between read_parquet and parquet_scan or state that they are identical

### ISSUE THREAD

**Issue by phbender** [duckdb/duckdb-web#589]
See [this page](https://duckdb.org/docs/data/parquet.html#filenames).

![image](https://user-images.githubusercontent.com/114987/222088101-e0d2840f-7303-46ee-abc6-7ba3ed0e626d.png)

It should be explicitly stated that `read_parquet` and `parquet_scan` are identical - if they are.

**Comment by Tishj** [comment]
The page you linked has since been fixed it seems, but https://duckdb.org/docs/data/partitioning/hive_partitioning still mentions `parquet_scan`, and is the only page that does so
