### ISSUE TITLE
Improve development setup with devcontainer/Codespace

### ISSUE THREAD

**Issue by mehd-io** [duckdb/duckdb-web#641]
Hey there 👋 
I've put a [small devcontainer](https://code.visualstudio.com/docs/devcontainers/containers) configuration for my first contributions, I'm thinking it may be interesting to have it as part of an optional development setup.
People could then just use [Codespace](https://github.com/codespaces) for small doc contributions, everything on the browser without going to install the right version of ruby, etc.

WDYT?

**Comment by Mause** [comment]
Hi @mehd-io, this has been something I've been looking at as well - if you've already put it together, feel free to submit a pr 😁
