### ISSUE TITLE
JSON docs issue

### ISSUE THREAD

**Issue by bucweat** [duckdb/duckdb-web#662]
In the JSON docs https://duckdb.org/docs/extensions/json#json-scalar-functions one of the examples `SELECT json_structure('["duck",{"family":"anatidae"}]');` gives a different result...here is what I get running console app in windows 64 bit built with VS2019 from master:
```
v0.3.3-dev12364 b8cf6a98e2
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D CREATE TABLE example (j JSON);
D INSERT INTO example VALUES
>   (' { "family": "anatidae", "species": [ "duck", "goose", "swan", null ] }');
D SELECT json_structure(j) FROM example;
┌────────────────────────────────────────────┐
│             json_structure(j)              │
│                    json                    │
├────────────────────────────────────────────┤
│ {"family":"VARCHAR","species":["VARCHAR"]} │
└────────────────────────────────────────────┘
D SELECT json_structure('["duck",{"family":"anatidae"}]');
┌──────────────────────────────────────────────────┐
│ json_structure('["duck",{"family":"anatidae"}]') │
│                       json                       │
├──────────────────────────────────────────────────┤
│ ["JSON"]                                         │
└──────────────────────────────────────────────────┘
```
Instead of  `Invalid Input Error: Inconsistent JSON structure` it returns `["JSON"]`. To be honest I'm not sure what to expect for correct answer...but currently the docs don't match the output hence this issue :-)

**Comment by lnkuiper** [comment]
Hi @bucweat, thanks for opening this issue. This has recently been changed, as we now default to the `JSON` type when we find an inconsistent structure, instead of throwing an error. This should be changed in the docs.
