### ISSUE TITLE
DuckDB Live Demo sometimes fails on "SELECT distinct l_shipinstruct FROM lineitem"

### ISSUE THREAD

**Issue by sadikovi** [duckdb/duckdb-web#67]
I tried running "SELECT distinct l_shipinstruct FROM lineitem"  and "SELECT distinct l_shipinstruct FROM lineitem order by 1 desc" on the https://duckdb.org/demo/ website and I either get an incorrectly rendered result or HTTP 503 errors. 

But the query does work occasionally.

```
Request URL: https://duckdbdemo.project.cwi.nl//fetch?callback=jQuery3510355319707602344_1629874848617&ref=53knwZQ5mH&_=1629874848637
Request Method: GET
Status Code: 502 Proxy Error
```

```
Request URL: https://duckdbdemo.project.cwi.nl//query?callback=jQuery351010110534406317129_1629874584547&q=SELECT%20distinct%20l_shipinstruct%20FROM%20lineitem%20order%20by%201%20desc&_=1629874584573
Request Method: GET
Status Code: 503 Service Temporarily Unavailable
```

<img width="881" alt="Screen Shot 2021-08-25 at 8 57 13 AM" src="https://user-images.githubusercontent.com/7788766/130741822-c1ce4a2c-375b-4888-8a37-ea0cdf83b3ef.png">

**Comment by hannesmuehleisen** [comment]
Thanks for reporting that, we will look into it!

**Comment by sadikovi** [comment]
Thank you. A few notes on how to reproduce:
1. Run the default query "SELECT * FROM lineitem"
2. Run "SELECT distinct l_shipinstruct FROM lineitem" or "SELECT distinct l_shipinstruct FROM lineitem order by 1 desc" a few times. Please bring up the developer console to see the requests. After 3-5 query attempts you should see the spinning indicator and requests failing or the webpage incorrectly rendering table.

It is not always reproducible though so you might need to try a few times.

**Comment by Mause** [comment]
Given we've removed the old live demo, I'm closing this
