### ISSUE TITLE
Add a warning banner for outdated docs pages

### ISSUE THREAD

**Issue by Mause** [duckdb/duckdb-web#675]
We've had a couple of people looking at outdated docs, having come from Google, without realising.

A warning banner would probably help with this.

A good example is the SQLAlchemy docs: https://docs.sqlalchemy.org/en/14/

![image](https://user-images.githubusercontent.com/1405026/230758414-1c3255a1-1d54-42a6-90b7-57d93e4a1c7d.png)

**Edit by Gabor:** I propose adding a banner for all the outdated versions (currently up to v0.8.1) *and also the latest snapshot version* (`dev`).
Rationale: Sometimes people read the documentation of the bleeding edge release and then wonder why the features they are trying do not work in their local (stable) DuckDB installation.

**Comment by sumitshinde-84** [comment]
i would like to work on this issue can you please assign it to me ?

**Comment by Mause** [comment]
You're welcome to give it a go!

**Comment by sumitshinde-84** [comment]
@Mause Please let me know if there are any other tasks or issues I can help with.

**Comment by Tishj** [comment]
To add to this, maybe we should also add a similar banner to the `dev` version of the docs to indicate that content on this page might not be available on the latest release.

And perhaps we should not default to `dev` version of the docs, unless it's the only version available.

**Comment by szarnyasg** [comment]
Related to #1732

**Comment by szarnyasg** [comment]
This will be done when rolling out the next design for the docs. We do the project management for the docs in Trello, so I'm closing this issue to avoid duplication.
