### ISSUE TITLE
Inconsistent installation instructions between installation page and main page

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb-web#694]
On the [main page](https://duckdb.org), installation instructions are as follows (for MacOS)

```
https://github.com/duckdb/duckdb/releases/download/v0.7.1/duckdb_cli-osx-universal.zip
```

On the [installation page](https://duckdb.org/docs/installation/), homebrew is mentioned:

```
Homebrew: brew install duckdb
GitHub Binary: https://github.com/duckdb/duckdb/releases/download/v0.7.1/duckdb_cli-osx-universal.zip
```

This should probably be unified

**Comment by Mause** [comment]
Can probably use jekyll includes for this? https://jekyllrb.com/docs/includes/
