### ISSUE TITLE
Docs refer to `duckdb` executable for Windows, but packaged executable named `duckdb.exe`

### ISSUE THREAD

**Issue by ned2** [duckdb/duckdb-web#699]
The [installation instructions](https://duckdb.org/docs/installation/) instruct people to run `./duckdb` on Windows, however the packaged DuckDB executable for Windows is named `duckdb.exe`.

As discussed in the [CLI API](https://duckdb.org/docs/api/cli). There is also a difference in invocation between PowerShell and cmd.exe: in PowerShell  it should be `./duckdb.exe` and for cmd.exe it should be `duckdb.exe`. Could be worth documenting this on the installation page as well..

The CLI API page could potentially also mention the different name of `duckdb.exe` on Windows.

A minor thing, but might confuse some folks.

**Comment by Mause** [comment]
Hey there, on windows you can omit the extension of an executable when you run it, so I'm not sure this is actually required?

**Comment by ned2** [comment]
ahhhhhh well TIL haha

This is where I reveal myself as a non-Windows user :P (I'm putting together a tutorial that needs to target all of Windows/macOS/Linux)

so yes indeed, not an issue. thanks!

**Comment by ned2** [comment]
Although, there could still be an argument for having two invocation options for Windows in the installation instructions page:

    ./duckdb  # PowerShell
    duckdb    # cmd.exe

**Comment by Mause** [comment]
I think the default error message is doing pretty well as is ;)
![Screenshot 2023-04-21 155953](https://user-images.githubusercontent.com/1405026/233578558-1f80a022-1eaf-4d32-a0d5-1c00a85dafd1.png)

**Comment by ned2** [comment]
ahah yes, fair! thanks for assuaging me of my concerns :)

**Comment by Mause** [comment]
> ahah yes, fair! thanks for assuaging me of my concerns :)

No worries! Windows is an odd beastie indeed 😅
