### ISSUE TITLE
Documentation doesn't list CHR() function

### ISSUE THREAD

**Issue by lukaseder** [duckdb/duckdb-web#709]
The `CHR()` function seems to be implemented as "expected" from other SQL dialects:

```sql
select ascii(chr(68)), chr(ascii('D'))
```

But it isn't documented here:
https://duckdb.org/docs/sql/functions/char

**Comment by Mause** [comment]
Interestingly it's listed on the numeric functions page: https://github.com/duckdb/duckdb-web/blob/3e2e8eda6e0c2226bb52521b37cafee1edfe208f/docs/sql/functions/numeric.md?plain=1#L42

**Comment by Alex-Monahan** [comment]
Moved it over!
