### ISSUE TITLE
Document ALTER VIEW

### ISSUE THREAD

**Issue by lukaseder** [duckdb/duckdb-web#714]
It appears that `ALTER VIEW v RENAME TO w` is valid syntax. Browsing the source code, I can see how this can be supported already:
https://github.com/duckdb/duckdb/blob/master/src/parser/parsed_data/alter_info.cpp

Other `ALTER` commands seem available too (`ALTER_SCALAR_FUNCTION` and `ALTER_TABLE_FUNCTION`).

Yet the documentation doesn't list this syntax yet:
https://duckdb.org/docs/sql/statements/alter_table

**Comment by lukaseder** [comment]
Other syntax elements also seem to be supported but not (yet?) documented, e.g. `ALTER TABLE .. ALTER .. ( SET NOT NULL | DROP NOT NULL )`

Are these known issues? Is it worth creating an issue for each one encountered? Or is updating the documentation already on the roadmap? I don't want to create / engage in unnecessary busywork if these things are already known...

**Comment by szarnyasg** [comment]
@lukaseder thanks for reporting it and apologies that this has fallen on the wayside since April. I've fixed it now.

> Are these known issues? Is it worth creating an issue for each one encountered? Or is updating the documentation already on the roadmap? I don't want to create / engage in unnecessary busywork if these things are already known...

Our goal is to have all available features mentioned in the documentation. If there is a missing keyword/function/etc. and there is no open issue about it, please create one and we'll try to amend it.

**Comment by lukaseder** [comment]
> @lukaseder thanks for reporting it and apologies that this has fallen on the wayside since April

I'm not in a hurry :)

> Our goal is to have all available features mentioned in the documentation. If there is a missing keyword/function/etc. and there is no open issue about it, please create one and we'll try to amend it.

Sure, I'll keep it in mind for the future. Thanks.
