### ISSUE TITLE
Bug - missing connect statement in docs

### ISSUE THREAD

**Issue by bjornasm** [duckdb/duckdb-web#731]
In [How to create a table from a Pandas DataFrame](https://duckdb.org/docs/guides/python/import_pandas#how-to-create-a-table-from-a-pandas-dataframe) version dev/0.7.1 we can see the following code snippet:

```
import duckdb
import pandas

# connect to an in-memory database
my_df = pandas.DataFrame.from_dict({'a': [42]})

# create the table "my_table" from the DataFrame "my_df"
duckdb.sql("CREATE TABLE my_table AS SELECT * FROM my_df")

# insert into the table "my_table" from the DataFrame "my_df"
duckdb.sql("INSERT INTO my_table SELECT * FROM my_df")
```

However the code following `# connect to an in-memory database` is missing, which we can retrieve from any of the older versions:

`con = duckdb.connect()`

As this is such a small bug I hope its ok to sneak in a feature request: If I am right I do not think you have to use a in-memory database, you could just as well write `con = duckdb.connect('mydatabase')` - as these are intro documents it could maybe be benefial to be clear about that? In example:

```
import duckdb
import pandas

# connect to an in-memory database or an database on disk by specifying duckdb.connect('yourdatabase.db')
con = duckdb.connect() 
my_df = pandas.DataFrame.from_dict({'a': [42]})

# create the table "my_table" from the DataFrame "my_df"
duckdb.sql("CREATE TABLE my_table AS SELECT * FROM my_df")

# insert into the table "my_table" from the DataFrame "my_df"
duckdb.sql("INSERT INTO my_table SELECT * FROM my_df")
```

**Comment by Alex-Monahan** [comment]
I believe the docs are correct - no explicit connect is required anymore, unless you don't want to use the default in-memory connection. I think our goal was to show the simplest example, and have the other details in reference material.

**Comment by bjornasm** [comment]
Thank you for your answer @Alex-Monahan  - but if no explicit connect is required anymore - isn't it misleading to specify `# connect to an in-memory database` as the code udner the comment is making a dataframe, not connecting to a dataframe? Maybe "No explicit connect is required to use the in memory connection" is more suitable?

**Comment by Alex-Monahan** [comment]
Good catch! I updated those comments. Please let me know if there is more improvement I can make @bjornasm!
