### ISSUE TITLE
Documentation From/Join

### ISSUE THREAD

**Issue by ml31415** [duckdb/duckdb-web#732]
Looking at: https://duckdb.org/docs/sql/query_syntax/from

There is an example for a conditional join:
```-- return the regions for the nations
SELECT n.*, r.*
FROM l_nations n, JOIN l_regions r ON (n_regionkey = r_regionkey)
```
I guess this should have dots instead of underscores in the ON clause.

Also a bit deeper down the page:
```
SELECT *
FROM trades t ASOF LEFT JOIN prices p 
  ON t.symbol = p.symbol AND t.when >= p.when
```
This example is contained twice, while the text announces an example with `USING` for the second example.

**Comment by Alex-Monahan** [comment]
Thanks for helping with this! Does that mean this issue can be closed?

**Comment by ml31415** [comment]
Nearly. If I'm not mistaken, the `_` still need replacement in the first code box of the section "Conditional Joins" in the ON clause:
```
SELECT n.*, r.*
FROM l_nations n, JOIN l_regions r ON (n_regionkey = r_regionkey)
```

**Comment by szarnyasg** [comment]
@ml31415 the `n_regionkey` and `r_regionkey` are TPC-H attributes, so the expression works fine. There are, however, other issues here:
1) an extra comma which causes a syntax error
2) the schema (or a pointer to it) is missing
