### ISSUE TITLE
https://duckdb.org/docs/sql/functions/timestamp underlines multiple menu items

### ISSUE THREAD

**Issue by domoritz** [duckdb/duckdb-web#74]
<img width="253" alt="Screen Shot 2021-09-11 at 12 22 25" src="https://user-images.githubusercontent.com/589034/132954502-ae6bd315-e549-4e9d-9ee1-57821babdda3.png">

I suspect the check for underlining should be stricter.

**Comment by domoritz** [comment]
Same issue on https://duckdb.org/docs/sql/functions/dateformat

<img width="221" alt="Screen Shot 2021-09-11 at 12 25 37" src="https://user-images.githubusercontent.com/589034/132954588-640c5a50-9ad0-4a85-b20e-b0b422108497.png">

**Comment by szarnyasg** [comment]
This no longer seems to be a problem on Chrome/Firefox. I checked both sites:
- https://duckdb.org/docs/sql/functions/dateformat
- https://duckdb.org/docs/sql/functions/timestamp
