### ISSUE TITLE
SQL UPDATE with JOIN, documentation

### ISSUE THREAD

**Issue by omo** [duckdb/duckdb-web#746]
(Copied from https://github.com/duckdb/duckdb/issues/4939)

----
Hello,

First of all : Duckdb is really great!

Il read in one your papers that duckdb was optimized for massive updates. This is really a need because most of our work is to alter the coding of columns in our input files. About UPDATE with JOIN I guessed on PostgreSQL syntax and found that the following syntax seems to work, but it is not documented.
Is it a bit of the magic of duckdb?

UPDATE t  SET REG_CODE=REGION FROM dep2017 WHERE DEP_CODE=DEP

I am trying to replace REG_CODE with the value REGION coming from another table, obtained from a join over DEP_CODE. DEP and REGION are in dep2017, DEP_CODE and REG_CODE are in t.

Best regards

JL.LIPATZ
Institut National de la Statistique et des Etudes Economiques - FRANCE

----

**Comment by szarnyasg** [comment]
Good point. Funnily enough, mixing `FROM` + `JOIN` + `WHERE` also works but this is quite an advanced query (and quite an ugly statement to be honest):

```sql
CREATE TABLE city (name VARCHAR, revenue BIGINT, country_code VARCHAR);
CREATE TABLE country (code VARCHAR, name VARCHAR, continent_code VARCHAR);
CREATE TABLE continent (code VARCHAR, name VARCHAR);
INSERT INTO city VALUES ('Paris', 700, 'FR'), ('Lyon', 200, 'FR'), ('Brussels', 400, 'BE');
INSERT INTO country VALUES ('FR', 'France', 'EU'), ('BE', 'Belgium', 'EU');
INSERT INTO continent VALUES ('EU', 'Europe');
```

```sql
UPDATE city
SET revenue = revenue + 100
FROM country
WHERE city.country_code = country.code
  AND country.name = 'France';
```

```sql
UPDATE city
SET revenue = revenue + 100
FROM country
JOIN continent ON continent.code = country.continent_code
AND continent.name = 'Europe';
```

**Comment by diulin** [comment]
Although it is shown in syntax diagram, it would be nice to mention explicitly that using table aliases for updated columns in SET will raise an error:

```sql
UPDATE city
SET city.revenue = revenue + 100
FROM country
JOIN continent ON continent.code = country.continent_code
AND continent.name = 'Europe';
``` 
```error
Error: Referenced update column city not found in table!
```
