### ISSUE TITLE
Missing padding above headings

### ISSUE THREAD

**Issue by domoritz** [duckdb/duckdb-web#75]
At https://duckdb.org/docs/sql/functions/dateformat, the headings are missing padding. 

<img width="1059" alt="Screen Shot 2021-09-11 at 12 24 25" src="https://user-images.githubusercontent.com/589034/132954552-a46cb43e-1838-424f-b419-e0059d21aef3.png">

**Comment by hannesmuehleisen** [comment]
@Franz-Kafka can maybe have a look

**Comment by Alex-Monahan** [comment]
This appears to be fixed now!
