### ISSUE TITLE
Improve `Statements` documentation

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb-web#768]
Some statement types are missing from the page:
- CREATE INDEX -- fixed by #1556
- CREATE TYPE -- fixed by #859
- Also https://duckdb.org/docs/sql/statements/drop is missing DROP TYPE

**Comment by 2-5** [comment]
- BEGIN TRANSACTION
- COMMIT
- ROLLBACK
- EXPLAIN

**Comment by 2-5** [comment]
- PREPARE
- EXECUTE

There is no documentation at all about these two statements, I only found out about them by seeing them being used here:
https://duckdb.org/2023/05/26/correlated-subqueries-in-sql.html
