### ISSUE TITLE
Add UnNest to Nested Types Page

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb-web#77]
I just wanted to document this here before I forgot! I'm happy to make this change.

I think that the UnNest function should be mentioned in the Nested types section in addition to the SELECT overview. 

In general, I think there might be a few other Postgres functions that aren't in the docs just yet, but we can track those in separate issues.

**Comment by Mytherin** [comment]
Yes, that makes sense. I think the UNNEST function actually warrants an extra page, since it is a "special" function in the sense that it changes the result cardinality. The functions in the Nested types section could contain UNNEST with a reference to this separate page.

**Comment by Alex-Monahan** [comment]
Looks great, thank you!!
