### ISSUE TITLE
Add documentation for the Benchmark suite

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb-web#770]
This should live under the `Development` tab

**Comment by szarnyasg** [comment]
@Tishj I know this is almost half a year old but did you mean this suite? https://github.com/duckdb/duckdb/tree/main/benchmark

**Comment by szarnyasg** [comment]
ping

**Comment by Tishj** [comment]
https://github.com/duckdb/duckdb/pull/1108

**Comment by Tishj** [comment]
`benchmark/README.md`
