### ISSUE TITLE
Document missing map functions

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb-web#789]
Several map functions (including at least map_keys and map_values) appear to not be documented - they should be added to the documentation.

**Comment by droher** [comment]
Based on the functions catalog, I think there are 3 missing functions - the two you mentioned and `map_entries`. I can put up a PR if you'd like.

**Comment by Alex-Monahan** [comment]
> Based on the functions catalog, I think there are 3 missing functions - the two you mentioned and `map_entries`. I can put up a PR if you'd like.

PRs are always appreciated! Thank you!!
