### ISSUE TITLE
Add documentation for type aliasing

### ISSUE THREAD

**Issue by droher** [duckdb/duckdb-web#802]
Enums are currently the only kind of `CREATE TYPE` statements documented. I just discovered the alias syntax and thought it would be useful for others, e.g.

```
CREATE TYPE my_type AS VARCHAR;
```

```
CREATE TYPE my_struct AS STRUCT (
   foo VARCHAR,
   bar VARCHAR
);
```

I'd be happy to work on this myself - my thought is that it would fit best as a new page inside `docs/sql/data_types/`. Does that make sense? Is there any other related syntax I should add as well? I know there is a good amount of work going on right now on type namespaces that this might overlap with.

**Comment by szarnyasg** [comment]
This was resolved by 8fcb8132ec8ad66400171ad0429bd557c5f40e27.
