### ISSUE TITLE
Improve Documentation: nested alias function readability

### ISSUE THREAD

**Issue by droher** [duckdb/duckdb-web#805]
Roughly half of the list functions in https://duckdb.org/docs/sql/functions/nested are aliases, which makes it a bit noisy to read and find out the available functionality. I'm not sure if/how you'd like to improve this, but my thought would be to add a fifth column, `Aliases`, but I'm not sure if you want to change the formatting for just one table.

**Comment by szarnyasg** [comment]
Hello, thanks for the suggestion. Commit c87f1978f18aad83d11f980fdf094a0d4ad6c167 introduced aliases for nested functions.
