### ISSUE TITLE
Add `con.close()` to persistent storage section in Python Overview page

### ISSUE THREAD

**Issue by ned2** [duckdb/duckdb-web#808]
I was referring to the [persistent storage section](https://duckdb.org/docs/api/python/overview.html#persistent-storage) of the Python Overview page to work out how to save my DB to disk. This page doesn't mention that there are some circumstances where you need to explicitly close the connection, so it took me quite a while to work out that the reason my saved tables weren't appearing in the catalogue of the saved DB was because I hadn't explicitly closed it. I see that this is documented over on [this docs page](https://duckdb.org/docs/api/python/dbapi#connection), but I only found this after struggling with this problem for a while. 

It would be good to add reference to the need to close the DB in some circumstances. I was thinking maybe just a final line in the code snippet with `con.close()` and a comment indicating when this is explicitly needed.

Would be happy to submit a PR.

**Comment by szarnyasg** [comment]
Fixed by #812
