### ISSUE TITLE
Update example Colab notebook to fix bugs

### ISSUE THREAD

**Issue by danthegoodman1** [duckdb/duckdb-web#813]
The Colab notebook found in https://duckdb.org/docs/guides/python/jupyter.html has a few issues with it:

![image](https://github.com/duckdb/duckdb-web/assets/17806508/20768dc8-f62c-4c06-81cf-180f9e232925)

Fixed by either separating to different cells:
![image](https://github.com/duckdb/duckdb-web/assets/17806508/61cd8c88-a07f-403b-a3c5-d2d2bf063217)

Or by removing the `%config SqlMagic.autopandas = True` line.

---
The second issue is:
![image](https://github.com/duckdb/duckdb-web/assets/17806508/28963412-9739-48cc-8bec-cd48cef99ccd)

This is fixed by changing 
`short-trips` -> `short_trips`:
```
%%sql --save short_trips --no-execute
SELECT *
FROM 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-01.parquet'
WHERE trip_distance < 6.3
```

**Comment by danthegoodman1** [comment]
I would be happy to PR, but don't think I can do anything similar with a notebook. These fixes are super quick however.

**Comment by Mause** [comment]
@Alex-Monahan I assume this is your notebook? Maybe we can pin the dependency versions too

**Comment by Alex-Monahan** [comment]
Thank you for your help finding and fixing these issues! I made the fixes in the notebook and filed a bug report with the JupySQL folks since this used to work.

https://github.com/ploomber/jupysql/issues/674
