### ISSUE TITLE
Add Scalar UDF Note about Cached/Constant Folding

### ISSUE THREAD

**Issue by paultiq** [duckdb/duckdb-web#815]
Per https://github.com/duckdb/duckdb/issues/7773, Scalar UDFs return the same result even for non-deterministic functions. 

In my opinion: This, at least, should be documented as a 0.8.0 limitation on the appropriate page, probably [Python Function API](https://duckdb.org/docs/api/python/function)

**Comment by Tishj** [comment]
This is no longer the case, through `side_effects` you can communicate whether the method is deterministic or not
<https://duckdb.org/docs/api/python/function#side-effects>
