### ISSUE TITLE
git fetch --tags, or how to have CI working

### ISSUE THREAD

**Issue by carlopi** [duckdb/duckdb-web#823]
Currently I believe tags have to be pushed, something like:
```
git clone https://github.com/duckdb/duckdb
cd duckdb
git fetch --tags
git remote add your_remote  PATH/TO/REMOVE
git push your_remote v0.8.0
```
is needed to have CI work properly, possibly something else also.

Unsure whether this is docs or main repo issue, but for now it could be for sure patched by documenting what's expected.

This came up at various times, like https://github.com/duckdb/duckdb/pull/7864 or with new devs.

**Comment by Tishj** [comment]
Seems to already be documented on main repo:
<https://github.com/duckdb/duckdb/blob/master/CONTRIBUTING.md#testing>

**Comment by carlopi** [comment]
Thanks, I had not looked for it in the most obvious place.

I also find the explanation is somehow misleading / could be improved (as in if default remote is yours, then I'd say you pull from `duckdb/duckdb`).

I still think some end-to-end guide, ideally mostly via code snippets, could be useful for newer contributors (both external and internal), and seems significative enough to be present both in docs AND contributing.

**Comment by szarnyasg** [comment]
Let's revisit this sometime soon. What sort of built guide do we want to provide _as part of the docs_?

Currently, we have this: https://duckdb.org/dev/building

**Comment by hannes** [comment]
@Mytherin we should probably only have one place where we document dev info, either website or markdown in repo. either is fine with me
