### ISSUE TITLE
Document what casts are implemented for each type

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb-web#836]
We should probably add something similar to what we did for the `core_functions` in that every type should likely have a `json` file describing what it can cast to, then we can leverage that to also generate a table of type -> type casts

That would also help development, to know which casts are missing

**Comment by szarnyasg** [comment]
Produced this:
![Screenshot 2023-12-10 at 11 35 17](https://github.com/duckdb/duckdb-web/assets/1402801/b39dd5cb-ce0f-4d1a-bcee-84979d611c21)
