### ISSUE TITLE
Is make_timestampz(microseconds) deprecated?

### ISSUE THREAD

**Issue by bjornasm** [duckdb/duckdb-web#852]
From [the documentation](https://duckdb.org/docs/sql/functions/timestamptz) we have the following table:

| make_timestamptz(microseconds) | The timestamp with time zone for the given µs since the epoch |make_timestamptz(1667810584123456) | 2022-11-07 16:43:04.123456-08 |
|-----------------|------------------------|------------------|---------------------|

However when I try to follow the example:

```sql
v0.8.0 e8e4cea5ec
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D SELECT make_timestamptz(1667810584123456);
Run Time (s): real 0.001 user 0.000361 sys 0.000144
Error: Binder Error: No function matches the given name and argument types 'make_timestamptz(BIGINT)'. You might need to add explicit type casts.
	Candidate functions:
	make_timestamptz(BIGINT, BIGINT, BIGINT, BIGINT, BIGINT, DOUBLE) -> TIMESTAMP WITH TIME ZONE
	make_timestamptz(BIGINT, BIGINT, BIGINT, BIGINT, BIGINT, DOUBLE, VARCHAR) -> TIMESTAMP WITH TIME ZONE

LINE 1: SELECT make_timestamptz(1667810584123456);
               ^
```

**Comment by Mause** [comment]
Looks like the documentation is a bit out of date here - as the error message indicates, the function signature has changed, but it still exists.

```
v0.8.1 6536a77232
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
⚫◗ set timezone = 'UTC'; -- for reproducible results
⚫◗ select make_timestamptz(9999, 1, 1, 1, 1, 1, 1);
┌──────────────────────────────────────────┐
│ make_timestamptz(9999, 1, 1, 1, 1, 1, 1) │
│         timestamp with time zone         │
├──────────────────────────────────────────┤
│ 9999-01-01 01:01:01+00                   │
└──────────────────────────────────────────┘
⚫◗ select make_timestamptz(9999, 1, 1, 1, 1, 1, 'Australia/Sydney');
┌───────────────────────────────────────────────────────────┐
│ make_timestamptz(9999, 1, 1, 1, 1, 1, 'Australia/Sydney') │
│                 timestamp with time zone                  │
├───────────────────────────────────────────────────────────┤
│ 9998-12-31 14:01:01+00                                    │
└───────────────────────────────────────────────────────────┘
```

**Comment by Mause** [comment]
Actually, it looks like the `make_timestamptz(US)` version is newer than the latest release version (https://github.com/duckdb/duckdb/pull/7597), so should be available in the next release

**Comment by bjornasm** [comment]
Thanks @Mause ! That is great news - felt like I found a little easter egg!

**Comment by nodakai** [comment]
Tripped over the same issue.

@Mause Would it be possible to add "available since version x.y" to the reference manual? It could save us some trouble in the future...

**Comment by Mause** [comment]
> Tripped over the same issue.
> 
> @Mause Would it be possible to add "available since version x.y" to the reference manual? It could save us some trouble in the future...

I was actually thinking about that this morning, and automating it using the function docs rework I'm working on right now
