### ISSUE TITLE
Update documentation on excel import to use excel extension rather than spatial extension

### ISSUE THREAD

**Issue by bjornasm** [duckdb/duckdb-web#862]
I wanted to file a PR that fixes this myself, but I could not find the documentation of the excel extension - sorry for just filing issues rather than doing some of the work myself.

In the [documentation for excel import ](https://duckdb.org/docs/guides/import/excel_import) we can see f.ex:

```sql
install spatial; -- Only needed once per DuckDB connection
load spatial; -- Only needed once per DuckDB connection

SELECT * FROM st_read('test_excel.xlsx', layer='Sheet1');
```

However it seems a bit too much (and maybe wrong?) to install and use the `spatial extension` to read an excel file. One reason for initially doing this might have been that the `spatial extension`  had some logic to read excel files, so it was convenient to just use that. But now there is an `excel extension` in the list of extensions, and I assume that it has methods to read excel files. I suggest that the documentation on excel imports is updated using the excel extension instead of spatial (and if excel currently does not offer some `excel_read('excelfile', sheetname='')` implement it as a function outside of spatial. If anything just as a copy/alias of the st_read() functionality, I think its more clear and understandable to have functions to import from excel separated from other libraries - as it can be a bit confusing to refer to the spatial library and unwanted to use the whole spatial library to import an excel file if you are not working with spatial data.

**Comment by Mause** [comment]
The excel extension only contains some Excel style formatting functions, not a way to read Excel files.

This has come up before, if you want to contribute a page explaining this, by all means

**Comment by bjornasm** [comment]
Thank you for your help @Mause  - upon doing an other search (I should start relying less on google and rather search here on github, apologies) I see that there have been an [attempt on a PR](https://github.com/duckdb/duckdb/pull/6037) for this feature - so this means that st_read() is the only method to read excel files as it is now and the documentation is correct. I don't think I am able to explain the choice of st_read vs an excel_read.
