### ISSUE TITLE
INSTALL and LOAD httpfs didn't perform in a batch as instructed

### ISSUE THREAD

**Issue by alexbodn** [duckdb/duckdb-web#864]
hello friends,

thanks a lot for wonderful duckdb.
i managed to try it, but encountered a small problem.

the suggestion to run
%%sql
INSTALL httpfs;
LOAD httpfs;
didn't work for me, instead i could run %sql with each of the separate lines.

thanks again,
alex

**Comment by edublancas** [comment]
hey @alexbodn, we fixed the issue reported by @Alex-Monahan in https://github.com/ploomber/jupysql/issues/674 and it'll be part of the next release

I ran:

```
In [1]: %load_ext sql
Found pyproject.toml from '/Users/eduardo/dev/jupysql'

In [2]: %sql duckdb://

In [3]: %%sql
   ...: INSTALL httpfs;
   ...: LOAD httpfs;
   ...:
   ...:
Running query in 'duckdb://'
Out[3]:
+---------+
| Success |
+---------+
+---------+

In [4]: quit
Closing duckdb://
```

in the development version and it's also fixed so it looks like it was the same problem.
