### ISSUE TITLE
CSV docs with delimiter parameter instead of delim

### ISSUE THREAD

**Issue by Cabeda** [duckdb/duckdb-web#868]
The examples of reading CSV with explicit delim incorrectly call the param as `delimiter` instead of `delim`(see [CSV Auto Detection page](https://duckdb.org/docs/data/csv/auto_detection.html)).

Should we update the docs accordingly? Happy to push a PR for this simple change

**Comment by szarnyasg** [comment]
@Cabeda Thanks for reporting this. Sure, PRs are welcome!
