### ISSUE TITLE
Wrong Icon for open source

### ISSUE THREAD

**Issue by iacore** [duckdb/duckdb-web#872]
https://github.com/duckdb/duckdb-web/blob/66d3642fa8f9d22a94e9cf426af7a6d1cae951e9/why_duckdb.md?plain=1#L49

This, is the peace sign.

![image](https://github.com/duckdb/duckdb-web/assets/74560659/4fd925fb-1aba-4fdb-8622-45f0d8b5ee4a)

This, is the open source sign.

![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Open_Source_Initiative.svg/457px-Open_Source_Initiative.svg.png?20230505191658)
https://commons.wikimedia.org/wiki/File:Open_Source_Initiative.svg

Sorry for the nickpicking. Otherwise nice website!

**Comment by szarnyasg** [comment]
Thanks raising this issue. We discussed this internally but decided to keep the old (peace) logo on the front page.
