### ISSUE TITLE
tldr page

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb-web#892]
@Alex-Monahan @Mause I created a first version of a tldr page here: https://github.com/tldr-pages/tldr/pull/10549

I'm opening this issue to have a pointer for it and discuss if any changes need to be made.

Using `$ tldr --render pages/common/duckdb.md`, it renders like this:

![Screenshot 2023-07-27 at 10 13 08](https://github.com/duckdb/duckdb-web/assets/1402801/17c45e3a-d1b9-4010-85ec-c6fabfbd5c59)

**Comment by Alex-Monahan** [comment]
Very neat! I'm not sure how many examples are too many, but another one that might be handy is a way to run a SQL script without keeping the shell open:

```sql
duckdb -c ".read path/to/script.sql"
```

The other trick that I find folks really like is reading/writing stdin/stdout for CSVs:
```sql
cat test.csv | duckdb -c "COPY (FROM read_csv_auto('/dev/stdin')) TO '/dev/stdout' WITH (FORMAT CSV, HEADER)"
```

**Comment by szarnyasg** [comment]
We are limited to 8 instructions by tldr's rules. So, I guess,  we should drop `-help` and add the ones you suggested?

**Comment by szarnyasg** [comment]
@Alex-Monahan I updated the PR at https://github.com/tldr-pages/tldr/pull/10549

**Comment by szarnyasg** [comment]
Merged in tldr-pages.

**Comment by szarnyasg** [comment]
Mentioned the tldr page in the docs in 52e2af2113b5cb9d4cb4174aabe39b1c66b1085d
