### ISSUE TITLE
Add jaccard(), levenshtein(), and other sequence comparisons to Array docs

### ISSUE THREAD

**Issue by NickCrews** [duckdb/duckdb-web#899]
There are several comparison functions that are documented in the Strings section, that also seem to work on Arrays (because they both are sequences/collections of things). These should be discoverable from the Arrays page.

We could
1. Rename the [Text Similarity Functions](https://duckdb.org/docs/sql/functions/char.html#text-similarity-functions) section to "Sequence Comparisons", and describe how they work for Arrays as well.
2. Move that section to its own page.
3. Link to that section from the Arrays page.

I would vote for just 1 and 3, I'm not sure it deserves its own page just for that.

**Comment by szarnyasg** [comment]
As discussed in https://github.com/duckdb/duckdb/issues/8414, the text similarity functions **do not** work for comparing sequences (lists, arrays).
