### ISSUE TITLE
`Load` disambiguation

### ISSUE THREAD

**Issue by carlopi** [duckdb/duckdb-web#900]
`LOAD` is used both regarding to extensions AND around CSV/JSON/Parquet support, like in "CSV loading" (https://duckdb.org/docs/data/csv/overview#csv-loading).

I guess the word is... loaded (how funny).

I would think that using load exclusively regarding extensions, given there it's a keyword, and move toward 'Import CSV/JSON/Parquet', that seems to be already the predominant use, or some other alternative that makes more sense in context.

**Comment by szarnyasg** [comment]
I took a stab at this. I don't think our users confuse loading a CSV file and loading an extension. So what I ended up doing was actually interspersing load CSV, read CSV and import CSV, which may help a bit with SEO.
