### ISSUE TITLE
Use U.S. English spelling

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb-web#908]
Most of the documentation is already written with US English spelling but there are a few occurrences of `behaviour`, `e.g. `, `i.e. `, etc. These should be fixed.

**Comment by Mause** [comment]
Why are ie or eg an issue?

**Comment by szarnyasg** [comment]
`e.g.`/`i.e.` are currently used both with (US) and without (UK) a trailing comma. Vale is a great pointer! I'll look into it.

**Comment by szarnyasg** [comment]
The docs now mostly use U.S. spelling.
