### ISSUE TITLE
RSS feed?

### ISSUE THREAD

**Issue by sbdchd** [duckdb/duckdb-web#92]
The jekyll docs mention a home grown solution <https://jekyllrb.com/tutorials/convert-site-to-jekyll/#10-rss-feed>, but also link to: https://github.com/jekyll/jekyll-feed

**Comment by Mause** [comment]
Looks like one already exists at https://duckdb.org/feed.xml, there's just no `link` element advertising it

**Comment by hannes** [comment]
Can you PR the addition of the link tag?
