### ISSUE TITLE
Documenting the Python `with` syntax for persistent storage

### ISSUE THREAD

**Issue by erikhuck** [duckdb/duckdb-web#927]
The [documentation on persistent storage](https://duckdb.org/docs/api/python/overview#persistent-storage) instructs Python users to open a connection and then call `.close()` as an additional step. This is the type of pattern that works well with context managers. After guessing that DuckDB had this intuitive use case implemented, I discovered that DuckDB does indeed support a context manager for database connections:
```
with duckdb.connect('path/to/database.db') as con:
```
But this functionality is not indicated in the section of the documentation (that I linked above). This warrants a simple addition of something like, "You can accomplish the same using a context manager as so..." and then providing the same example code but using the `with` statement instead of `con.close()`.

**Comment by szarnyasg** [comment]
Thanks, I implemented this
