### ISSUE TITLE
Making 'Copy' button work Python/node.js installation

### ISSUE THREAD

**Issue by carlopi** [duckdb/duckdb-web#931]
Haven't looked into this, but what I see if I select "Python" in the installation page, then click the 'Copy' button, it seems to be a no-op (= on paste I get back whatever was already in the clipboard).

**Comment by Mause** [comment]
Looks like this is due to how the installation page works at the moment. Rather than showing and hiding elements as required, it rewrites the html of the page, which removes all the event handlers :/

**Comment by Mause** [comment]
Fixed in https://github.com/duckdb/duckdb-web/pull/1130
