### ISSUE TITLE
The internals/ and dev/ pages should be under docs/

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb-web#938]
The **Development** node in the menu tree, which includes the pages from the `internals/` and `dev/` directories should be under the `docs/` directory and it should be included in the archive for each release.

The advantage of this would be that the dev documentation would also be versioned. We can keep `https://duckdb.org/internals/storage` with a redirect.

**Comment by hannes** [comment]
This info is really only relevant to the current version I'd say
