### ISSUE TITLE
"PREDECING" typo

### ISSUE THREAD

**Issue by JackyP** [duckdb/duckdb-web#95]
Hi,

Thanks for an awesome package. Just a small typo that confused me more than it should as I was copy+pasting from examples:

https://duckdb.org/docs/sql/window_functions

```
SELECT points,
    SUM(points) OVER (
        ROWS BETWEEN 1 PREDECING
                 AND 1 FOLLOWING) we
FROM results
```

"PREDECING" should be "PRECEDING"

**Comment by Mytherin** [comment]
Thanks for the report! I have just [pushed a fix](https://github.com/duckdb/duckdb-web/commit/a865ce4aff3e219ad5c4ebd44db6749932c17feb).
