### ISSUE TITLE
[duckdb-wasm] Out in the wild / public examples

### ISSUE THREAD

**Issue by carlopi** [duckdb/duckdb-web#957]
The most common deployment scenario for duckdb-wasm is for it to be used in a website doing some sort of data-wrangling.

Could it make sense to collect somewhere example of usage (https://github.com/duckdb/duckdb-wasm/discussions/1359)? So that it can be used as a reference of sort of what's possible.

I haven't though about this properly, unsure whether there has to be some policy regarding what could end up on the list (I'd say public available, in some form, that would make it accessible). Unsure what other libraries do, I have seen list of links in README's, unsure how they are selected.

Looking for directions, not really urgent.

**Comment by szarnyasg** [comment]
I think this is a great idea but it belongs to the [`awesome-duckdb` repository](https://github.com/davidgasquez/awesome-duckdb), which currently lacks a Wasm section.
