### ISSUE TITLE
Add more language examples to ADBC API docs page

### ISSUE THREAD

**Issue by ianmcook** [duckdb/duckdb-web#962]
The ADBC API docs page ([website](https://duckdb.org/docs/api/adbc), [GitHub](https://github.com/duckdb/duckdb-web/blob/master/docs/api/adbc.md)) added in #911 includes a C++ example. It would be great to add more language examples:

- [ ] Go
- [ ] Java
- [x] Python - #1007 
- [ ] R
- [ ] Ruby

@zeroshade could you take on a couple of these when you have time? Thank you!

**Comment by zeroshade** [comment]
Gonna take a stab at some of these this week!

**Comment by szarnyasg** [comment]
Hi @ianmcook are there any further example pages planned for the ADBC API? If not, let's close this issue as stale.

**Comment by zeroshade** [comment]
I do intend on making more example pages, I just haven't had the time...

**Comment by szarnyasg** [comment]
Closing this now due the lack of activity, feel free to reopen.
