### ISSUE TITLE
hole in profiling documentation page

### ISSUE THREAD

**Issue by benjamin-du** [duckdb/duckdb-web#991]
Hello everyone,

First of all, thank you very much for this impressive and very useful library :)

on this page : https://duckdb.org/dev/profiling

in the "[Explain Statement](https://duckdb.org/dev/profiling#explain-statement)" subsection;

The paragraph says : "We can see that the logical_plan contains the unoptimized query plan, involving a cross product and a LIKE operation"

I can "see" no such thing. The page doesn't seem to contain any logical_plan, nor any other mention to a cross product besides this paragraph.

Could anyone please either provide the schema that contains the logical_plan with the mention to the cross product, or update the wording ?

**Comment by benjamin-du** [comment]
By the way, I can't seem to be able to use the presented commands succesfully.

The following snippet:

`
import pandas as pd
import duckdb
 students = pd.DataFrame({"sid": [1, 2], "name": ["mathew", "james"]})
exams = pd.DataFrame({"sid": [1, 2], "note": ["10", "15"]})
duckdb.query("""EXPLAIN SELECT name FROM students JOIN exams USING (sid) WHERE name LIKE 'Ma%';""")
`

produces incomplete result, both in a notebook and in a terminal:


![image](https://github.com/duckdb/duckdb-web/assets/32103306/217db1fe-5f88-480f-a292-6abedec09641)

**Comment by szarnyasg** [comment]
Hello, you're right that the profiling page is outdated. I submitted a PR #992. If you can have a look, that'd much appreciated!

For the Python/notebook issue, please look around the discussions in https://github.com/duckdb/duckdb/discussions and open one if applicable.
